### ISSUE TITLE
docker pull fails.

### ISSUE THREAD

**Issue by avanishrb** [docker-library/mysql#1001]
Executing docker run or docker pull runs into an error of missing signature.

```console
[avanish-bandekar@******* ~]$ docker pull mysql
Using default tag: latest
Trying to pull repository docker.io/library/mysql ...
Trying to pull repository docker.io/library/mysql ...
missing signature key
[avanish-bandekar@******* ~]$
```

**Comment by LaurentGoderre** [comment]
I wonder if this error is coming from Hub or from a mirror.

Do you have a file `/etc/docker/registry/config.yml` ? If so what's it's content?

**Comment by LaurentGoderre** [comment]
@avanishrb were you able to solve this?

**Comment by avanishrb** [comment]
Apologies, I did not put in much effort to solve this. 

I just used an older version, and it worked for me.
```sh
docker pull mysql:8.0.32
```

**Comment by LaurentGoderre** [comment]
Ok, good to know!

**Comment by yosifkit** [comment]
Probably similar to https://github.com/docker-library/redis/issues/381#issuecomment-1765431018
