### ISSUE TITLE
Unable to create temporary file inside "/tmp"; errno: 13

### ISSUE THREAD

**Issue by jellyleo** [docker-library/mysql#1004]
Installed MySQL 8.0.33 On CentOS Linux release 7.9.2009
![图片](https://github.com/docker-library/mysql/assets/34032791/ff2a1809-4e5a-4d6c-b997-bdedcbf67d2e)
Directory permissions of /tmp on host
![图片](https://github.com/docker-library/mysql/assets/34032791/b8bd12c7-62fd-4c6b-8de9-7d730ff1319b)
Docker image:  8.0.34
Running mysql docker container on same host, and console output: failed to initialize DD Storage Engine
![图片](https://github.com/docker-library/mysql/assets/34032791/20709813-b3fa-4cf9-90b2-326ec705dbe0)

HELP，please !!

**Comment by LaurentGoderre** [comment]
I am unable to reproduce. Do you have more details on how the container was started?
