### ISSUE TITLE
Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.

### ISSUE THREAD

**Issue by rawr51919** [docker-library/mysql#1005]
I get this warning in the MySQL server console when I start a MySQL server in Docker. Is there any easy way to fix this?
```
[Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
```

**Comment by qeepcologne** [comment]
assuming that you did not overwrite that specific config:
add to Dockerfile:
RUN chmod -R 770 /run/mysqld

**Comment by rawr51919** [comment]
I wasn't actually using that particular `chmod` command, but thank you, that helped
Resolved by adding `RUN chmod 1770 /var/run/mysqld` to the Dockerfile
