### ISSUE TITLE
E: Version '5.6.26*' for 'mysql-server' was not found

### ISSUE THREAD

**Issue by marksullivancrowd** [docker-library/mysql#102]
ENV MYSQL_VERSION 5.6.26
dockerfile tries to install 5.6.26 but doesnt exist in repo
5.6.27 exists

apt-cache show mysql-server
Package: mysql-server
Source: mysql-community
Version: 5.6.27-1debian8
Architecture: amd64
Maintainer: MySQL Release Engineering <mysql-build@oss.oracle.com>
Installed-Size: 46
Depends: mysql-community-server (= 5.6.27-1debian8)
Homepage: http://www.mysql.com/
Priority: optional
Section: database
Filename: pool/mysql-5.6/m/mysql-community/mysql-server_5.6.27-1debian8_amd64.deb
Size: 11414
SHA256: d1502c5370d45157a97e921049889dd83835e05d2bf7be311ceb84570903ab5d
SHA1: bcbdf3dc66fa2c4278665c6231686f185d0d3f15
MD5sum: f322d9e94a5fd838f693241d1c88c118
Description: MySQL Server meta package depending on latest version
 The MySQL(TM) software delivers a very fast, multi-threaded, multi-user,
 and robust SQL (Structured Query Language) database server. MySQL Server
 is intended for mission-critical, heavy-load production systems as well
 as for embedding into mass-deployed software. MySQL is a trademark of
 Oracle. This is a meta package that depends on the latest mysql server
 package available in the repository.
Description-md5: 40f35c3f688a48dea4283a87850ef877

**Comment by sherter** [comment]
#103 resolves this (but why not simply use the prebuilt image?)

**Comment by marksullivancrowd** [comment]
Completely agree, not an issue if you pull the main image, just raising it for attention.
