### ISSUE TITLE
Docker build not working in macOS 14.1.2 - Apple silicon

### ISSUE THREAD

**Issue by marcelo-xyz** [docker-library/mysql#1021]
**Host:** macOS 14.1.2 (23B92)
**Command:** `sudo docker build -t mysql8:v8.0-debian11 /path/to/dockerfile/at/8.0/`

The `/path/to/dockerfile/at/8.0/` in the command above is just to illustrate my local path used as context for the `docker build`. This path leads to a directory which contains the exactly copy of https://github.com/docker-library/mysql, with the only tweak being a symlink of **/8.0/Dockerfile.debian** as **/8.0/Dockerfile**, to enable the build.

Please find attached a full log of the command.

Thank you!

[2023-12-21_145534Z.txt](https://github.com/docker-library/mysql/files/13743406/2023-12-21_145534Z.txt)

<img width="1128" alt="2023-12-21_145534Z" src="https://github.com/docker-library/mysql/assets/83043147/27c89f48-9cd9-4f37-9590-fe840fd992e7">

**Comment by LaurentGoderre** [comment]
If i remember correctly Debian doesn't have arm64 packages for mysql and DOI doesn't have an arm64 variant for Debian either. You should either use the oraclelinux variant if native arm64 is important or use Mac's emulation to build it and run it as amd64

```
sudo docker build --platform linux/amd64 -t mysql8:v8.0-debian11 /path/to/dockerfile/at/8.0/
```

**Comment by marcelo-xyz** [comment]
Hey Laurent, thank you for the speedy response.

The `--platform linux/amd64` did the trick.

Have a good one!
