### ISSUE TITLE
How to install mysqlbinlog tool in arm64 8.0.36 version

### ISSUE THREAD

**Issue by xkz130** [docker-library/mysql#1032]
I hope to install the mysqlbinlog tool when compiling mysql8 using Dockerfile.debian, but the installation failed. What should I do? thanks
![image](https://github.com/docker-library/mysql/assets/46994912/3bac80f8-a4b2-4cdd-860f-db61b36807b4)

**Comment by LaurentGoderre** [comment]
Are you on a Mac with Apple M1 or M2 chip? if so, you should use `--platform=linux/amd64' because mysql doesn't have arm64 binaries in debian.

**Comment by xkz130** [comment]
> Are you on a Mac with Apple M1 or M2 chip? if so, you should use `--platform=linux/amd64' because mysql doesn't have arm64 binaries in debian.

I am an ARM machine and I need to install the mysqlbinlog tool in the ARM version of MySQL. However, it is only available in MySQL: 8.0.36-debian and not in the ARM version, so I need to install it. However, I am unable to install it at this time

**Comment by tianon** [comment]
You'll probably have to switch from using upstream's Docker-crafted packages to using their larger generic packages.

See https://dev.mysql.com/doc/mysql-installation-excerpt/8.3/en/linux-installation-rpm.html for upstream documentation along those lines.  Doing so is unfortunately out of scope for this repository. :bow: :heart:
