### ISSUE TITLE
broken versioning strategy

### ISSUE THREAD

**Issue by streamnsight** [docker-library/mysql#104]
Not sure if this is the place but I'm getting frustrated with the repo info list not keeping track of the older version:

I use Docker but my base image is Ubuntu, so I have to build my own... I follow the same 'recipe' as in the original debian-based image, but change the apt-get update list to the ubuntu version...

Problem is: that changes several times a year and that breaks my builds. 
So, yes ideally I should update, but I should be able to find the older version if I wish to, so I can upgrade on my own timeframe, not because my build broke.

today, it was 5.6.26 not found when running `apt-get install -y mysql-server="${MYSQL_VERSION}"`

I'd appreciate to understand how I can keep access to the old version on apt-get
Thanks

**Comment by sherter** [comment]
That's really an issue with the apt-repository provided by the mysql folks. You could just leave the `"${MYSQL_VERSION}"` part out: `apt-get install -y mysql-server`
This should install the latest available version.

**Comment by thaJeztah** [comment]
Indeed, that's not a docker issue, you'll have the same problem if you're trying to apt-get install on a physical Ubuntu machine.

> I use Docker but my base image is Ubuntu, so I have to build my own..

Just curious; why would you need to build your own? If you run MySQL in a separate container, it shouldn't matter that its base image (Ubuntu, Debian, CentOS, whatever) is different than the distro your app container is based on

**Comment by streamnsight** [comment]
@thaJeztah I am just trying to be consistent: if you use images from all over the place, you end up with all sorts of flavors of Linux and you clog up your host. The idea behind docker is to make use of the hierarchy of images and basing all the infra on one distro is much more efficient.

however, it take the point about the apt-get repo. sorry for the noise.

**Comment by sherter** [comment]
> The idea behind docker is to make use of the hierarchy of images and basing all the infra on one distro is much more efficient.

I think you are optimizing on the wrong end. Docker is much more about the "package _once_ and run everywhere" idea. Who cares about a few hundred MB disk space? That's really not an issue.

**Comment by ltangvald** [comment]
@streamnsight You might considering reporting the issue to bugs.mysql.com (Category MySQL Package Repos and Docker images).
@sherter Removing the version is a good idea in general since (at least now) the repo doesn't support multiple versions and it would save a bit of effort when updating for new releases. Thanks :)

**Comment by tianon** [comment]
> @sherter Removing the version is a good idea in general since (at least now) the repo doesn't support multiple versions and it would save a bit of effort when updating for new releases. Thanks :)

https://github.com/docker-library/official-images#repeatability :wink:

**Comment by ltangvald** [comment]
Yeah, good point :)
