### ISSUE TITLE
Skip SSL

### ISSUE THREAD

**Issue by qmonmert** [docker-library/mysql#1053]
Since `8.4.0`, this command `mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp` is on error:
```
[ERROR] [MY-000068] [Server] unknown option '--skip-ssl'.
```

I tried with `--ssl-mode=DISABLED` the command `mysqld --lower_case_table_names=1 --ssl-mode=DISABLED --character_set_server=utf8mb4 --explicit_defaults_for_timestamp` but it doesn't work:
```
[ERROR] [MY-000067] [Server] unknown variable 'ssl-mode=DISABLED'.
```

Have you an idea?

Thanks a lot

**Comment by tianon** [comment]
I don't see anything related in the MySQL 8.4 release notes, but I also don't see _any_ SSL-related flags in https://dev.mysql.com/doc/refman/8.4/en/server-options.html, so this looks like it's likely an intentional upstream change.

**Comment by qmonmert** [comment]
@tianon indeed but I saw that on the doc https://dev.mysql.com/doc/refman/8.4/en/connection-options.html#option_general_ssl-mode
![image](https://github.com/docker-library/mysql/assets/9989211/4fedae35-43e0-4ef0-a938-3ee80f57f5e9)
but it doesn't work on my example 🧐

**Comment by yosifkit** [comment]
The `--ssl-mode` flag is for the `mysql` client, not the server.
```console
$ docker run -it --rm mysql:8.4 mysqld --help | grep ssl-mode
$ # empty result
$ docker run -it --rm mysql:8.4 mysql --help | grep ssl-mode
  --ssl-mode=name     SSL connection mode.
```

And the `skip-ssl` flag is no longer mentioned:
```console
$ docker run -it --rm mysql:8.0 mysqld --help --verbose | grep -B2 skip-ssl
  --ssl               Enable SSL for connection (automatically enabled with
                      other flags).
                      (Defaults to on; use --skip-ssl to disable.)
--
    --ssl-session-cache-mode
                      Is TLS session cache enabled or not
                      (Defaults to on; use --skip-ssl-session-cache-mode to disable.)
$ docker run -it --rm mysql:8.3 mysqld --help --verbose | grep -B2 skip-ssl
  --ssl               Enable SSL for connection (automatically enabled with
                      other flags).
                      (Defaults to on; use --skip-ssl to disable.)
--
    --ssl-session-cache-mode
                      Is TLS session cache enabled or not
                      (Defaults to on; use --skip-ssl-session-cache-mode to disable.)
$ docker run -it --rm mysql:8.4 mysqld --help --verbose | grep -B2 skip-ssl
  --ssl-session-cache-mode
                      Is TLS session cache enabled or not
                      (Defaults to on; use --skip-ssl-session-cache-mode to disable.)
```

I guess by removing the `--ssl` server option, they also meant that `skip-ssl` was removed too:

>The --ssl and --admin-ssl server options, as well as the have_ssl and have_openssl server system variables, were all deprecated in MySQL 8.0.26, and are all removed in this release. Use [--tls-version](https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_tls_version) and [--admin-tls-version](https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_admin_tls_version) instead.
>
>\-https://dev.mysql.com/doc/relnotes/mysql/8.4/en/news-8-4-0.html#mysqld-8-4-0-deprecation-removal

**Comment by qmonmert** [comment]
thanks @yosifkit I close the ticket
