### ISSUE TITLE
Error response from daemon: Conflict. The name "mysql" is already in use by container 3aa7b9d9e78b. You have to delete (or rename) that container to be able to reuse that name.

### ISSUE THREAD

**Issue by a1exus** [docker-library/mysql#106]
Am I doing something wrong or ...

```
root@alexus:~/_docker# docker run --name mysql -d mysql:latest
3aa7b9d9e78bb70aec0e1bfa6369d277851eb15afdde50ee13c4573c74c42f5d
root@alexus:~/_docker# docker stop mysql
mysql
root@alexus:~/_docker# docker run --name mysql -d mysql:latest
Error response from daemon: Conflict. The name "mysql" is already in use by container 3aa7b9d9e78b. You have to delete (or rename) that container to be able to reuse that name.
root@alexus:~/_docker# 
```

How do I start then stop then start mysql docker container again?

**Comment by ltangvald** [comment]
"run" will always start a new container, which is why you're seeing the name conflict.
I suggest going through the command line documentation. "pause" and "unpause" might be what you're looking for (https://docs.docker.com/reference/commandline/cli/).

**Comment by a1exus** [comment]
i'm looking to restart mysql container (due to reflect my.cnf changes), (un)pause won't work for me...

**Comment by thaJeztah** [comment]
I think you're looking for [docker restart](https://docs.docker.com/reference/commandline/restart/)

**Comment by a1exus** [comment]
thanks for that docker 101), I'm still new to this whole docker and i'm learning as I go, thanks again!

**Comment by thaJeztah** [comment]
No problem! If you need more help, the #docker IRC channel is usually a good place to ask questions
