### ISSUE TITLE
internal users authentication plugin method

### ISSUE THREAD

**Issue by qeepcologne** [docker-library/mysql#1063]
i upgraded some mysql installations to 8.4.0 (non docker) and always the plugin of the internal users (mysql.*) are upgraded to caching_sha2_password.
strangely this is not done for our docker installation:

mysql> select user,host,plugin from mysql.user;

upgraded docker image:
| healthchecker    | localhost | mysql_native_password |
| mysql.infoschema | localhost | caching_sha2_password |
| mysql.session    | localhost | mysql_native_password |
| mysql.sys        | localhost | caching_sha2_password |
| root             | localhost | caching_sha2_password |

fresh docker image:
| root             | %         | caching_sha2_password |
| mysql.infoschema | localhost | caching_sha2_password |
| mysql.session    | localhost | caching_sha2_password |
| mysql.sys        | localhost | caching_sha2_password |
| root             | localhost | caching_sha2_password |

(the mysql.session user is still mysql_native_password)
i know how to change authentication method for our and the root user, but i no idea for the mysql.* users password.
https://dba.stackexchange.com/questions/330384/how-do-i-change-the-authentication-plugin-for-users-mysql-sys-mysql-session-et

**Comment by tianon** [comment]
This seems like really strange behavior -- however, I think it's more of a question about _upstream_ behavior than it is anything particular to this image?  You might have better luck in a MySQL support forum. :bow:

**Comment by qeepcologne** [comment]
you're right, i first had 3 non dockerized installations without this issue, it first happed on docker container, but now i have another 2 non-dockerized installations with that issue
