### ISSUE TITLE
please add a mysql-router to the library package

### ISSUE THREAD

**Issue by lfarkas** [docker-library/mysql#1066]
as I read in #955 you do not maintain mysql-router. unfortunately the mysql version https://hub.docker.com/r/mysql/mysql-router is rather outdated.
it'd be useful to either add a separate mysql-router to the library or even better to include in this container the router too. since you already add the tools repo for the dockerfile (for the mysql-shell you can also install the mysql-router from the same place. it's only a 4MB extra space compared to the current container size 160MB (from which the shell is 44MB) is nothing and would be very useful for many.

**Comment by tianon** [comment]
If I'm understanding correctly, MySQL Router is effectively a separate (companion) product, right?  Also, usage of it is optional, and only for a pretty narrow set of use cases?

(It's effectively impossible for users to _remove_ it if we include it by default, but as you say, it should be pretty easy for users who want/need it to install it themselves. :innocent:)

**Comment by lfarkas** [comment]
it's as separate as mysql-shell which is also included, and it's effectively impossible for users to remove it as mysql-shell.
everybody who create and use mysql in a cluster (which is an option in mysql 8.x) must have to use it. whether it's narrow or wide it's a relative...

**Comment by tianon** [comment]
The difference there is that MySQL Shell is intended to be _the_ MySQL client (and intended to replace `mysql(1)` itself), so eventually we'll probably even have to update all our wrapper scripts to use it instead.

**Comment by lfarkas** [comment]
we switch back to mariadb
