### ISSUE TITLE
Why mysql-server, mysql-router... docker images didn't have updated during last year?

### ISSUE THREAD

**Issue by mahmoud-eskandari** [docker-library/mysql#1079]
Hi
Recently MySQL updated to version 9.0 so we need to upgrade MySQL docker images but unfortunately mysql-server, mysql-router and other projects didn't receive updates during last year.

This docker image  updated over 1 year ago.
https://hub.docker.com/r/mysql/mysql-router/tags

**Comment by LaurentGoderre** [comment]
We do not maintain that organization on Hub. This repo is for the Docker Official image for MySQL which was last updated 6 days ago.

**Comment by mahmoud-eskandari** [comment]
OK
Please help me to find latest mysql-router, mysql-shell official images. I can't find them by search on Docker hub.
Thanks
