### ISSUE TITLE
如何使用DBeaver去连接mysql镜像？

### ISSUE THREAD

**Issue by meisir5648** [docker-library/mysql#1085]
1，最新版本的mysql有防火墙吗？我使用DBeaver连接时无响应。
2，是使用localhost去连接，还是使用容器的ip去连接？
<img width="742" alt="image" src="https://github.com/user-attachments/assets/8d3d20a6-2f53-4b28-b352-84222ef76ca2">
<img width="679" alt="image" src="https://github.com/user-attachments/assets/2e7296f2-56aa-472f-ab67-960f4dab0efd">
<img width="679" alt="image" src="https://github.com/user-attachments/assets/6aa75aac-418c-447e-b07b-63af8bcc58d0">

**Comment by tianon** [comment]
If you want to connect to your container over localhost on your host, you'll need to "publish" the port (`-p` / `--publish` flag on `docker run`).
