### ISSUE TITLE
mysql:8.0.35-debian : Xray major vulnerabilities reported

### ISSUE THREAD

**Issue by RishiDixit1** [docker-library/mysql#1086]
Hi Team,

We are using docker image of mysql:8.0.35-debian version when we do a xray scan on this image, we have found major  vulnerabilities.
Due to infra restriction we can't upgrade to the latest version of mysql 8.0.39, we are requesting you to fix the attached vulnerabilities in 8.0.35 version.
please provide an ETA on this.

images : 
mysql:8.0.35-debian-11-r3
mysqld-exporter:0.15.1-debian-11-r1

[mysql-8.0.35-debian-xray-vulns.xlsx](https://github.com/user-attachments/files/16990849/mysql-8.0.35-debian-xray-vulns.xlsx)

**Comment by tianon** [comment]
I'm sorry, but the 8.0.35 image is EOL, has not been updated since January, and we have no plans to update it at this time.  Updating to the latest release of MySQL or building your own image are your most effective solutions for recourse.
