### ISSUE TITLE
Run mysqltuner.pl inside

### ISSUE THREAD

**Issue by GMELUM** [docker-library/mysql#1089]
I'm trying to run mysqltuner.pl inside my MySQL Docker image to analyze its configuration, but I'm hitting a wall.  Neither Perl nor wget are working inside the image.  What should I do to get this working?

I'm trying to do this:

```
docker exec -t -i mysql /bin/bash
wget https://raw.githubusercontent.com/major/MySQLTuner-perl/master/mysqltuner.pl
perl mysqltuner.pl
```

**Comment by LaurentGoderre** [comment]
If you are using the default variant (oraclelinux) you need to use this first

```
microdnf install wget perl
```

**Comment by tianon** [comment]
Looking at https://github.com/major/MySQLTuner-perl, I would actually suggest you run MySQL tuner in a separate container (perhaps [the `perl` images](https://hub.docker.com/_/perl) are of interest to you? :eyes:) and use `--host` to connect to it via Docker's network (just like any other application using the database might).

**Comment by GMELUM** [comment]
For me, the solution was:

```
microdnf install wget perl
```

I didn't consider the second option because I suspect that the Perl script would require full access to the server, processor and RAM information.

**Comment by tianon** [comment]
https://github.com/major/MySQLTuner-perl#specific-usage suggests that even locally, they prefer connecting via TCP, so that's not likely :eyes:
