### ISSUE TITLE
No amd64 support in 9.1

### ISSUE THREAD

**Issue by joreize** [docker-library/mysql#1090]
Seems like there is currently no support for amd64 in the current 9.1 Image.

`` docker pull mysql:9.1.0
Error response from daemon: no match for platform in manifest: not found``

**Comment by jnoordsij** [comment]
All architectures are built individually and thus may not be available at the same time. Therefore a tag might already be present, but not have all supported architectures available. Just wait for a bit and the tag should appear soon. See also https://github.com/docker-library/faq?tab=readme-ov-file#an-images-source-changed-in-git-now-what

Note: by the looks of https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/mysql/ the amd64 job is failing, so probably the wait will be slightly longer as manual intervention is required.

**Comment by tianon** [comment]
We had an unfortunate glitch due to https://github.com/docker-library/meta-scripts/pull/85 (technically https://github.com/docker-library/meta/pull/42); fixed in https://github.com/docker-library/meta/commit/81d985b7c400b1dfa2ef52ffb8107087d22004ff; builds should be coming Soon™ :heart:

**Comment by tianon** [comment]
All fixed now :partying_face:
