### ISSUE TITLE
Pulling mysql:5.7.12 from docker registry gives a "missing signature key" error

### ISSUE THREAD

**Issue by elishagreenwald** [docker-library/mysql#1096]
Hi when running `docker pull mysql:5.7.12` I get a "missing signature key" error. I checked with someone else to ensure it's not just my setup and they get the same error. Did something recently change? Thanks!

**Comment by yuvall-cyera** [comment]
Happened to us too
In other docker client we get:
```
Error response from daemon: [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/library/mysql:5.6.17 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```

Sounds like changing the manifest version should fix that

**Comment by tianon** [comment]
There's now a fix in place in Docker Hub for the original pulling issue (schema1 images should pull successfully again in tools which support them).

If you have a tool which does not support them and you still need to work with them, I have written https://github.com/tianon/oci-schema1 to help perform the conversion without any runtime support (`bash` + `jq` + a little `crane`).
