### ISSUE TITLE
Container fails to start if log-bin is used with writeable datadir

### ISSUE THREAD

**Issue by ltangvald** [docker-library/mysql#113]
If the user specifies a custom config that enabled binary logging, and the mysql user has full write access to the folder, the --verbose --help command used to extract datadir will write an index file to it, causing the following initialize step to fail because there are files in datadir.

To reproduce:
...
docker run -e MYSQL_ROOT_PASSWORD=rot -v /tmp/data:/var/lib/mysql mysql:latest --log-bin=somename --server-id=1
...
where /tmp/data is writeable.

A possible workaround is to add --log-bin-index=/tmp/junk.index to the --verbose --help command. 
This is a bug in the server, similar to #69

**Comment by ltangvald** [comment]
Related bugs.mysql.com issue: http://bugs.mysql.com/bug.php?id=78957

**Comment by ndelitski** [comment]
+1

**Comment by tianon** [comment]
This has been fixed now, right? :smile:

**Comment by ltangvald** [comment]
Yeah, this bug was fixed in 5.7.10 (only affected 5.7.9)
