### ISSUE TITLE
Grant remote access MYSQL_USER

### ISSUE THREAD

**Issue by armpogart** [docker-library/mysql#116]
As this container is often used as linked container and it allows setting `MYSQL_USER`, `MYSQL_PASSWORD` and `MYSQL_DATABASE` and it grants priviliges to that user on that database, it would be helpful to have a way to grant remote access priviliges to that user also. For now on linked container case creating that user through these options is useless for me as I need to connect as root to grant remote priviliges.

**Comment by tianon** [comment]
https://github.com/docker-library/mysql/blob/e9ac4f4efb9168e0e25cc1075ca6b14853a525db/5.7/docker-entrypoint.sh#L71-L75 -- we already use `@'%'`, where `%` is the wildcard, so this should already be functional in the way that you describe. :confused:

**Comment by armpogart** [comment]
I see, but why then I get the error when connecting to the linked container?

Running the command from main container
````
mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "SELECT User FROM mysql.user;"
````
I get `ERROR 1045 (28000): Access denied for user 'effio_user'@'172.17.0.137' (using password: YES)`

While `root` user connects without any problems.

**Comment by tianon** [comment]
The user created is only granted access to the database created, so it
won't be able to read from "mysql.user". :smile:

**Comment by armpogart** [comment]
ah, ok :thumbsup:
This explains everything. All is working as expected. My mistake, sorry.

**Comment by tianon** [comment]
No worries, glad we got it figured out!
