### ISSUE TITLE
LOAD DATA INFILE solution

### ISSUE THREAD

**Issue by ain** [docker-library/mysql#118]
It's often desirable that one could use `LOAD DATA INFILE` which currently fails over `secure-file-priv`. Would be nice to have `ENV` option to allow it, for instance.

Esp. on larger projects it is crucial to be able to effectively import large amounts of data from a file.

**Comment by yosifkit** [comment]
The default config of the server from the apt repo is to only allow files from `/var/lib/mysql-files/` to be loaded with `LOAD DATA INFILE` ([mysql docs](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_secure_file_priv)).  It would become unwieldy if we had an environment variable for every mysql option.  I would suggest either mounting your files in that directory and putting an import script into `/docker-entrypoint-initdb.d/` to load it, or add a mysql config file to `/etc/mysql/conf.d/` to change the `secure-file-priv` value to something more convenient.

**Comment by ain** [comment]
Thanks for heads up! 

Turns out [mysql2 Rails gem](https://github.com/brianmario/mysql2) has `local_infile: true` which basically refers to `LOAD DATA LOCAL INFILE` and it works out of the box with the mysql image. 

I think we can consider the topic closed.
