### ISSUE TITLE
mysql `MYSQL_DATABASE` env Variable

### ISSUE THREAD

**Issue by waleedsamy** [docker-library/mysql#121]
when initializing Mysql with different databases only one `MYSQL_DATABASE` is be available in linked container, what if i like to add multiple databases, i added them in [/docker-entrypoint-initdb.d/](https://github.com/docker-library/mysql/blob/master/5.6/docker-entrypoint.sh#L81-L88), how can i get information about these DBs like credentials and DB's name form linked container.

or mysql container is designed to has only one DB, and i should provide container for each DB!

**Comment by tianon** [comment]
I personally prefer having a separate container for each database (which mimics production deployments and helps keep separation of concerns).  There's also some discussion of mutli-database over in https://github.com/docker-library/mysql/pull/18, however.
