### ISSUE TITLE
MYSQL_ROOT_PASSWORD special character missing with docker-compose.yml configuration

### ISSUE THREAD

**Issue by elpirata15** [docker-library/mysql#123]
`docker version`
```
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7
 Built:        
 OS/Arch:      linux/amd64
```
`docker-compose version`
```
docker-compose version: 1.5.0
docker-py version: 1.5.0
CPython version: 3.4.3+
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015
```

`uname -a`
`
Linux debian01 4.2.0-1-amd64 #1 SMP Debian 4.2.5-1 (2015-10-27) x86_64 GNU/Linux
`

I'm trying to setup basicmysql container but I got an error when I try to setup the enviroment with MYSQL_ROOT_PASSWORD value starting with special character '$$'

`docker-compose.yml`
```
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: $$.example
```

HOW TO REPRODUCE

`1. docker-compose up `
`2. docker exec -it container_name bash `
`3. echo $MYSQL_ROOT_PASSWORD `

You will get something like this.

```
root@0adb2477c855:/# echo $MYSQL_ROOT_PASSWORD
$.example
```

NOTE:
When docker run one line command the password with special characters works properly.
`docker run --name mymysql -e MYSQL_ROOT_PASSWORD='$$.example' mysql`

Regards,

**Comment by obi1kenobi** [comment]
Check out the `Variable substitution` section here:
https://docs.docker.com/compose/compose-file/

It states that $ENV_VAR substitutions are allowed in the docker-compose.yml file. That means that `$$` is the escape sequence that represents the `$` character, making this intended behavior of docker-compose.
