### ISSUE TITLE
关于外部容器link入sql容器的问题

### ISSUE THREAD

**Issue by Coderhypo** [docker-library/mysql#127]
我在daocloud部署一个mysql到vps，并把vps下/root的一个文件夹映射到容器里的/var/lib/mysql

我打算把一个.sql文件导入的数据库中，然后准备用下面这种方式链接数据库
```
docker run --rm -it -v $(pwd):/root --link dao_BlogDB_1 daocloud.io/library/mysql mysql -u root -p 
```

然后，在输入密码后出现这个问题。
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

后来经过发现是权限问题，需要进入链接容器 ‘chown -R mysql:mysql /var/lib/mysql’，再进行sql登录。

是不是我外挂 Volume的方式不对？因为第一次用docker还不是很熟悉。

**Comment by yosifkit** [comment]
Looks like you need to specify a host:
```console
$ docker run --rm -it -v $(pwd):/root --link dao_BlogDB_1 daocloud.io/library/mysql mysql -h dao_BlogDB_1 -u root -p
```

Alternatively, you could just mount in your sql file to `/docker-entrypoint-initdb.d/` and it would be run just after the database is initially created when making a new container. (https://github.com/docker-library/docs/tree/4231b03395af279bfe2bf10b07a2b0221b8c4c48/mysql#initializing-a-fresh-instance)
```console
$ docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d -v $(pwd):/docker-entrypoint-initdb.d/ mysql
```

**Comment by Coderhypo** [comment]
Thank you for your answer. Solve the problem, did not start in English, forgive my bad manners

**Comment by tianon** [comment]
No worries; glad we got it figured out! :+1:
