### ISSUE TITLE
Connection lost on import of database

### ISSUE THREAD

**Issue by ianks** [docker-library/mysql#13]
This keeps happening about 30 minutes into import. There are no interesting messages in the logs. Not sure what is going on here.

```
ERROR 2013 (HY000): Lost connection to MySQL server during query
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    6
Current database: dev_imobitrax
```

**Comment by yosifkit** [comment]
Closing, reopen/post if there is any info that can reproduce or solve the issue.

**Comment by jboynton** [comment]
I had this problem with a large import and it turned out the host VM RAM wasn't set high enough. Doubled it from 1 GB to 2 GB and the import succeeded.

**Comment by marsh0lion** [comment]
This is a general issue with MySQL (see https://stackoverflow.com/questions/10474922/error-2006-hy000-mysql-server-has-gone-away). To fix this with Docker (or at least lessen the likelyhood of it happening) add ' --max_allowed_packet=1073741824' (or to some other appropriately large number) to your startup command

**Comment by timclifford** [comment]
As @marsh0lion said `fin start --max_allowed_packet=1073741824` allowed me to import my 250mb db
