### ISSUE TITLE
container fails to start with error message mkdir: can not create directory ''

### ISSUE THREAD

**Issue by gggeek** [docker-library/mysql#133]
This has happened twice: on an ubuntu mate and on a ubuntu desktop computer.

The env vars and volume mounts are fine, as the same docker-compose definition works on other machines.

I tried to debug the error by starting the container in a way that I get shell access even if the entrypoint fails, but it seems that this operation is not so easy:

docker run -ti mysql:5.6 --entrypoint='' bash

still seems to go trough entrypoint.sh ?

I think that having the container stay alive even if the mysql server does not start might be useful. Even if it is not the default configuration, at least it could be better documented in the readme ?

**Comment by gggeek** [comment]
ps: not clearly specified, but tested using the 5.6 version

**Comment by ltangvald** [comment]
You should be able to get shell access by simply running
 docker run -it mysql:5.6 /bin/bash

It'll still start the normal entrypoint script, but if you look at https://github.com/docker-library/mysql/blob/master/5.6/docker-entrypoint.sh you can see that unless the command given is mysqld, it won't really do anything.

You can also still see the logs of the container (though they might not contain the information you need) by running
 docker logs <container>

And you can get the list of stopped containers by running
 docker ps -a

**Comment by ltangvald** [comment]
If you don't see anything helpful in the logs, which version of Ubuntu and Docker are you using?

**Comment by gggeek** [comment]
Docker version 1.9.1, build a34a1d5, Ubuntu 14.04

**Comment by gggeek** [comment]
ps:

docker logs => the error msg I gave

docker ps => Exit 1

**Comment by ltangvald** [comment]
Does it only happen with docker compose, or also if you use the command-line to start the image?
Could you post the run command/yaml file?

**Comment by gggeek** [comment]
So far, it happened always (on those 2 host computers).
At this very moment, I managed to start the container and log into it - with the db down - and I get another funny error:

root@mysql:/# /etc/init.d/mysql status
mysqld: error while loading shared libraries: libpthread.so.0: cannot open shared object file: Permission denied
MySQL Community Server  is not running.

**Comment by ltangvald** [comment]
Any chance the permissions on the volumne mounts are set up differently on the machines where it works and the ones where it doesn't? Disks aren't full?

**Comment by gggeek** [comment]
The fs permission on the volume mounts are ok, as in some cases mysql managed to write data in there. There is plenty of space on disk :-(

**Comment by ltangvald** [comment]
Does it work if you strip it down completely, i.e. just do docker run -e MYSQL_ROOT_PASSWORD=pass mysql:5.6 ?

**Comment by gggeek** [comment]
nopes

**Comment by gggeek** [comment]
Not sure if it helps, but it seems that the container works on ubuntu 14 with kernel
3.13.0-74-generic #118-Ubuntu,
whereas where it does not work kernel is
3.19.0-42-generic #48~14.04.1-Ubuntu SMP

**Comment by robsoncompuff** [comment]
I had same problem here. The issue was caused by a declaration in my.cnf (!import /etc/mysql/conf.d), you just have to comment this line or make sure this directory exists. (like it should exist on other machines)

**Comment by gggeek** [comment]
My bad, in fact the completely stripped down command does work.
Also, adding more cli switches, to emulate what docker-compose is doing also works:

docker run -e MYSQL_ROOT_PASSWORD=pass mysql:5.6 ===> ok
docker run -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_USER=user_test -e MYSQL_PASSWORD=NotSoSecret -e MYSQL_DATABASE=test_db -p 3307:3306 -v /var/www/workspace/test/data/mysql:/var/lib/mysql mysql:5.6 ===> ok

here is the docker-compose definition:

mysql:
    image: mysql:5.6
    hostname: mysql
    container_name: test_mysql
    privileged: true
    ports:
        - "3307:3306"
    volumes:
        - ./data/mysql/:/var/lib/mysql
    env_file:
        - docker-compose.env
        - docker-compose.env.local
    cap_add:
        - SYS_PTRACE

and in the env file:

DEV_UID=1000
DEV_GID=1000
SYMFONY_ENV=dev
MYSQL_ROOT_PASSWORD=QuiteSecret
MYSQL_USER=test_user
MYSQL_PASSWORD=NotSoSecret
MYSQL_DATABASE=test_db
PMA_HOST=mysql

**Comment by gggeek** [comment]
AAAND, I found a way to make a difference:

docker run -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_USER=user_test -e MYSQL_PASSWORD=NotSoSecret -e MYSQL_DATABASE=test_db -p 3307:3306 -v /var/www/workspace/test/data/mysql:/var/lib/mysql mysql:5.6 ===> ok

docker run -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_USER=user_test -e MYSQL_PASSWORD=NotSoSecret -e MYSQL_DATABASE=test_db -p 3307:3306 -v /var/www/workspace/test/data/mysql:/var/lib/mysql --privileged=true mysql:5.6 ===> KO

so it seems that running the container as privileged causes problems

**Comment by gggeek** [comment]
Can close - I think this is a duplicate of other issues, such as https://github.com/docker/docker/issues/7512.
The container now runs with non privileged mode, at it still accessible from the other containers.

**Comment by ltangvald** [comment]
Looks like it, yes. Glad you got it working :)
