### ISSUE TITLE
5.7 fails to initialize database when using binary logging

### ISSUE THREAD

**Issue by cabernet-zerve** [docker-library/mysql#135]
If binary logging is enabled, entrypoint.sh fails to initialize a new database because server-id is not specified. Even if you provide --server-id in your command, it is not used in the following line:

```
mysqld --initialize-insecure=on --datadir="$DATADIR"
```

Should this be modified to use "$@" instead of "mysqld", or perhaps providing an arbitrary server-id value on the command line.

**Comment by yosifkit** [comment]
We did just swap that today (https://github.com/docker-library/mysql/blob/2e1fda0b2ca389a9e9d242042e56526a2f08988c/5.7/docker-entrypoint.sh#L24). There should be an updated image on the hub later today.

**Comment by cabernet-zerve** [comment]
Thanks @yosifkit, didn't see that pushed to hub last week, do you know if it's scheduled to go out this week?

**Comment by yosifkit** [comment]
Sorry, the change is in a PR, https://github.com/docker-library/official-images/pull/1376;  it should be merged and built tomorrow morning and hopefully pushed by the afternoon (I'll try to get `mysql` to the front of the `pushing` line).
