### ISSUE TITLE
A use-case for just using the MySQL as a client to a remote DB in the readme

### ISSUE THREAD

**Issue by ericandrewlewis** [docker-library/mysql#137]
I'd like to use the container just for the MySQL client. Can we add this use case and suggestions for usage in the readme?

**Comment by yosifkit** [comment]
Similar to [this section](https://github.com/docker-library/docs/tree/3058d2688084833be07a3e3fd876d41149048c54/mysql#connect-to-mysql-from-the-mysql-command-line-client)?

In other words drop the linking and swap in your credentials:
```console
$ docker run -it --rm mysql mysql -h mysql.local  -P 3306 -uroot -p supersecret
```

**Comment by ericandrewlewis** [comment]
Exactly.
