### ISSUE TITLE
Fails to provision with sql if I use a volume at /var/lib/mysql

### ISSUE THREAD

**Issue by byrnedo** [docker-library/mysql#141]
If I mount a volume at `/var/lib/mysql` then any scripts I place in `/docker-entrypoint-initdb.d` won't get run. Shouldn't the entrypoint script check that `/var/lib/mysql` is empty, not that it doesn't exist?

**Comment by ltangvald** [comment]
The entrypoint script checks for the existence of $DATADIR/mysql, with default $DATADIR being /var/lib/mysql
So it would check for /var/lib/mysql/mysql. Are you sure the volume you mount is empty?

**Comment by byrnedo** [comment]
Good point. Will have a look.

**Comment by byrnedo** [comment]
My bad, the volume wasn't empty.
