### ISSUE TITLE
Initialization from database dumps does not work correctly

### ISSUE THREAD

**Issue by rothnic** [docker-library/mysql#142]
See the documentation [here](https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance).

If I mount in one or more `.sql` files into this directory then mysql errors on initialization saying that no database is selected: `ERROR 1046 (3D000) at line 22: No database selected`. This is because I didn't provide a database name environment variable, because I expected the names of the databases to be derived from the `.sql` files.

When I add the database env variable `MYSQL_DATABASE` then each of the `.sql` files are imported into that same database, potentially overwriting tables.

So for each `.sql` file in the directory it should take the name of the file without the extension and that would be used for importing the database. The only way for me to work around this was to rename my two dumps to not have an extension, then add a shell script that manually does the operations that I'd expect to happen. If this as expected, then this behavior should be added to the docs.

**Comment by tianon** [comment]
IMO, this should be solved by adding `USE xyz-databse;` to the top of your `.sql` dump files.

The [`--databases`/`-B` flag to `mysqldump`](https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_databases) will do this automatically:

> `CREATE DATABASE` and `USE` statements are included in the output before each new database.

**Comment by dunnleaddress** [comment]
I added the param: MYSQL_DATABASE in my configuration as such:

mysql:
 image: mysql:5.5.53
 environment:
   MYSQL_ROOT_PASSWORD: pass
   MYSQL_DATABASE: watcher
 ports:
   - 3307:3306
 volumes:
   - ./db-dump:/docker-entrypoint-initdb.d
