### ISSUE TITLE
mysqld: Shutdown complete

### ISSUE THREAD

**Issue by zhkmxx9302013** [docker-library/mysql#156]
I got a log file like the folloing code. I don't know whether the my.conf is wrong or not.

> 2016-03-28 01:15:08:Digest: sha256:721f2f56a7b298ce4ab4edb9278be6d14b3facea0a99c45cec90ce139d4c55a4
> 2016-03-28 01:15:08:Status: Image is up to date for daocloud.io/library/mysql:5.5.48
> 2016-03-28 01:15:12:Creating dao_zhao_mysql_1...
> 2016-03-28 01:15:13:160327 17:15:13 [Note] mysqld (mysqld 5.5.48) starting as process 1 ...
> 2016-03-28 01:15:13:160327 17:15:13 [Note] Plugin 'FEDERATED' is disabled.
> 2016-03-28 01:15:13:mysqld: Table 'mysql.plugin' doesn't exist
> 2016-03-28 01:15:13:160327 17:15:13 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: The InnoDB memory heap is disabled
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: Mutexes and rw_locks use GCC atomic builtins
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: Compressed tables use zlib 1.2.3
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: Using Linux native AIO
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: Initializing buffer pool, size = 128.0M
> 2016-03-28 01:15:13:InnoDB: mmap(137363456 bytes) failed; errno 12
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: Completed initialization of buffer pool
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: Fatal error: cannot allocate memory for the buffer pool
> 2016-03-28 01:15:13:160327 17:15:13 [ERROR] Plugin 'InnoDB' init function returned error.
> 2016-03-28 01:15:13:160327 17:15:13 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2016-03-28 01:15:13:160327 17:15:13 [ERROR] Unknown/unsupported storage engine: InnoDB
> 2016-03-28 01:15:13:160327 17:15:13 [ERROR] Aborting
> 2016-03-28 01:15:13:
> 2016-03-28 01:15:13:160327 17:15:13 [Note] mysqld: Shutdown complete
> 2016-03-28 01:15:13:
> 2016-03-28 01:15:13:160327 17:15:13 [Note] mysqld (mysqld 5.5.48) starting as process 1 ...
> 2016-03-28 01:15:13:160327 17:15:13 [Note] Plugin 'FEDERATED' is disabled.
> 2016-03-28 01:15:13:mysqld: Table 'mysql.plugin' doesn't exist
> 2016-03-28 01:15:13:160327 17:15:13 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: The InnoDB memory heap is disabled
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: Mutexes and rw_locks use GCC atomic builtins
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: Compressed tables use zlib 1.2.3
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: Using Linux native AIO
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: Initializing buffer pool, size = 128.0M
> 2016-03-28 01:15:13:InnoDB: mmap(137363456 bytes) failed; errno 12
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: Completed initialization of buffer pool
> 2016-03-28 01:15:13:160327 17:15:13 InnoDB: Fatal error: cannot allocate memory for the buffer pool
> 2016-03-28 01:15:13:160327 17:15:13 [ERROR] Plugin 'InnoDB' init function returned error.
> 2016-03-28 01:15:13:160327 17:15:13 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2016-03-28 01:15:13:160327 17:15:13 [ERROR] Unknown/unsupported storage engine: InnoDB
> 2016-03-28 01:15:13:160327 17:15:13 [ERROR] Aborting
> 2016-03-28 01:15:13:
> 2016-03-28 01:15:13:160327 17:15:13 [Note] mysqld: Shutdown complete
> 2016-03-28 01:15:13:
> 2016-03-28 01:15:14:160327 17:15:14 [Note] mysqld (mysqld 5.5.48) starting as process 1 ...
> 2016-03-28 01:15:14:160327 17:15:14 [Note] Plugin 'FEDERATED' is disabled.
> 2016-03-28 01:15:14:mysqld: Table 'mysql.plugin' doesn't exist
> 2016-03-28 01:15:14:InnoDB: mmap(137363456 bytes) failed; errno 12
> 2016-03-28 01:15:14:160327 17:15:14 InnoDB: Completed initialization of buffer pool
> 2016-03-28 01:15:14:160327 17:15:14 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2016-03-28 01:15:14:160327 17:15:14 [ERROR] Unknown/unsupported storage engine: InnoDB
> 2016-03-28 01:15:14:160327 17:15:14 [ERROR] Aborting
> 2016-03-28 01:15:14:
> 2016-03-28 01:15:14:
> 2016-03-28 01:15:15:160327 17:15:15 [Note] Plugin 'FEDERATED' is disabled.
> 2016-03-28 01:15:15:160327 17:15:15 InnoDB: The InnoDB memory heap is disabled
> 2016-03-28 01:15:15:InnoDB: mmap(137363456 bytes) failed; errno 12
> 2016-03-28 01:15:15:160327 17:15:15 InnoDB: Fatal error: cannot allocate memory for the buffer pool
> 2016-03-28 01:15:15:160327 17:15:15 [ERROR] Plugin 'InnoDB' init function returned error.
> 2016-03-28 01:15:15:160327 17:15:15 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2016-03-28 01:15:15:160327 17:15:15 [ERROR] Unknown/unsupported storage engine: InnoDB
> 2016-03-28 01:15:15:160327 17:15:15 [ERROR] Aborting
> 2016-03-28 01:15:15:160327 17:15:15 [Note] mysqld: Shutdown complete
> 2016-03-28 01:15:15:160327 17:15:15 [Note] mysqld: Shutdown complete
> 2016-03-28 01:15:15:
> 2016-03-28 01:15:17:160327 17:15:17 [Note] mysqld (mysqld 5.5.48) starting as process 1 ...
> 2016-03-28 01:15:17:160327 17:15:17 [Note] Plugin 'FEDERATED' is disabled.
> 2016-03-28 01:15:17:mysqld: Table 'mysql.plugin' doesn't exist
> 2016-03-28 01:15:17:160327 17:15:17 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
> 2016-03-28 01:15:17:160327 17:15:17 InnoDB: The InnoDB memory heap is disabled
> 2016-03-28 01:15:17:160327 17:15:17 InnoDB: Mutexes and rw_locks use GCC atomic builtins
> 2016-03-28 01:15:17:160327 17:15:17 InnoDB: Compressed tables use zlib 1.2.3
> 2016-03-28 01:15:17:160327 17:15:17 InnoDB: Using Linux native AIO
> 2016-03-28 01:15:17:160327 17:15:17 InnoDB: Initializing buffer pool, size = 128.0M
> 2016-03-28 01:15:17:InnoDB: mmap(137363456 bytes) failed; errno 12
> 2016-03-28 01:15:17:160327 17:15:17 InnoDB: Fatal error: cannot allocate memory for the buffer pool
> 2016-03-28 01:15:17:160327 17:15:17 [ERROR] Plugin 'InnoDB' init function returned error.
> 2016-03-28 01:15:17:160327 17:15:17 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2016-03-28 01:15:17:160327 17:15:17 [ERROR] Unknown/unsupported storage engine: InnoDB
> 2016-03-28 01:15:17:160327 17:15:17 [ERROR] Aborting
> 2016-03-28 01:15:17:160327 17:15:17 [Note] mysqld: Shutdown complete
> 2016-03-28 01:15:17:
> 2016-03-28 01:15:20:160327 17:15:20 [Note] mysqld (mysqld 5.5.48) starting as process 1 ...
> 2016-03-28 01:15:20:160327 17:15:20 [Note] Plugin 'FEDERATED' is disabled.
> 2016-03-28 01:15:20:mysqld: Table 'mysql.plugin' doesn't exist
> 2016-03-28 01:15:20:160327 17:15:20 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
> 2016-03-28 01:15:20:160327 17:15:20 InnoDB: The InnoDB memory heap is disabled
> 2016-03-28 01:15:20:160327 17:15:20 InnoDB: Mutexes and rw_locks use GCC atomic builtins
> 2016-03-28 01:15:20:160327 17:15:20 InnoDB: Compressed tables use zlib 1.2.3
> 2016-03-28 01:15:20:160327 17:15:20 InnoDB: Initializing buffer pool, size = 128.0M
> 2016-03-28 01:15:20:160327 17:15:20 InnoDB: Completed initialization of buffer pool
> 2016-03-28 01:15:20:160327 17:15:20 InnoDB: Fatal error: cannot allocate memory for the buffer pool
> 2016-03-28 01:15:20:160327 17:15:20 [ERROR] Unknown/unsupported storage engine: InnoDB
> 2016-03-28 01:15:20:
> 2016-03-28 01:15:20:
> 2016-03-28 01:15:27:160327 17:15:27 [Note] Plugin 'FEDERATED' is disabled.
> 2016-03-28 01:15:27:160327 17:15:27 InnoDB: Mutexes and rw_locks use GCC atomic builtins
> 2016-03-28 01:15:27:160327 17:15:27 InnoDB: Compressed tables use zlib 1.2.3
> 2016-03-28 01:15:27:160327 17:15:27 InnoDB: Initializing buffer pool, size = 128.0M
> 2016-03-28 01:15:27:160327 17:15:27 InnoDB: Completed initialization of buffer pool
> 2016-03-28 01:15:27:160327 17:15:27 InnoDB: Fatal error: cannot allocate memory for the buffer pool
> 2016-03-28 01:15:27:160327 17:15:27 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2016-03-28 01:15:27:160327 17:15:27 [ERROR] Unknown/unsupported storage engine: InnoDB
> 2016-03-28 01:15:27:160327 17:15:27 [ERROR] Aborting
> 2016-03-28 01:15:27:
> 2016-03-28 01:15:27:160327 17:15:27 [Note] mysqld: Shutdown complete
> 2016-03-28 01:15:40:160327 17:15:40 [Note] mysqld (mysqld 5.5.48) starting as process 1 ...
> 2016-03-28 01:15:40:160327 17:15:40 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
> 2016-03-28 01:15:40:160327 17:15:40 InnoDB: The InnoDB memory heap is disabled
> 2016-03-28 01:15:40:160327 17:15:40 InnoDB: Compressed tables use zlib 1.2.3
> 2016-03-28 01:15:40:160327 17:15:40 InnoDB: Initializing buffer pool, size = 128.0M
> 2016-03-28 01:15:40:InnoDB: mmap(137363456 bytes) failed; errno 12
> 2016-03-28 01:15:40:160327 17:15:40 [ERROR] Plugin 'InnoDB' init function returned error.
> 2016-03-28 01:15:40:160327 17:15:40 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2016-03-28 01:15:40:160327 17:15:40 [ERROR] Aborting
> 2016-03-28 01:15:40:
> 2016-03-28 01:15:40:160327 17:15:40 [Note] mysqld: Shutdown complete
> 2016-03-28 01:15:40:
> 2016-03-28 01:16:06:160327 17:16:06 [Note] mysqld (mysqld 5.5.48) starting as process 1 ...
> 2016-03-28 01:16:06:160327 17:16:06 [Note] Plugin 'FEDERATED' is disabled.
> 2016-03-28 01:16:06:mysqld: Table 'mysql.plugin' doesn't exist
> 2016-03-28 01:16:06:160327 17:16:06 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
> 2016-03-28 01:16:06:160327 17:16:06 InnoDB: The InnoDB memory heap is disabled
> 2016-03-28 01:16:06:160327 17:16:06 InnoDB: Mutexes and rw_locks use GCC atomic builtins
> 2016-03-28 01:16:06:160327 17:16:06 InnoDB: Compressed tables use zlib 1.2.3
> 2016-03-28 01:16:06:160327 17:16:06 InnoDB: Using Linux native AIO
> 2016-03-28 01:16:06:160327 17:16:06 InnoDB: Initializing buffer pool, size = 128.0M
> 2016-03-28 01:16:06:InnoDB: mmap(137363456 bytes) failed; errno 12
> 2016-03-28 01:16:06:160327 17:16:06 InnoDB: Completed initialization of buffer pool
> 2016-03-28 01:16:06:160327 17:16:06 InnoDB: Fatal error: cannot allocate memory for the buffer pool
> 2016-03-28 01:16:06:160327 17:16:06 [ERROR] Plugin 'InnoDB' init function returned error.
> 2016-03-28 01:16:06:160327 17:16:06 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 2016-03-28 01:16:06:160327 17:16:06 [ERROR] Unknown/unsupported storage engine: InnoDB
> 2016-03-28 01:16:06:160327 17:16:06 [ERROR] Aborting
> 2016-03-28 01:16:06:
> 2016-03-28 01:16:06:160327 17:16:06 [Note] mysqld: Shutdown complete
> 2016-03-28 01:16:06:
> 2016-03-28 01:16:58:160327 17:16:58 [Note] mysqld (mysqld 5.5.48) starting as process 1 ...
> 2016-03-28 01:16:58:160327 17:16:58 InnoDB: The InnoDB memory heap is disabled
> 2016-03-28 01:16:58:160327 17:16:58 InnoDB: Compressed tables use zlib 1.2.3
> 2016-03-28 01:16:58:160327 17:16:58 InnoDB: Fatal error: cannot allocate memory for the buffer pool
> 2016-03-28 01:16:58:160327 17:16:58 [ERROR] Plugin 'InnoDB' init function returned error.
> 2016-03-28 01:16:58:160327 17:16:58 [ERROR] Aborting
> 2016-03-28 01:16:58:
> 2016-03-28 01:16:58:160327 17:16:58 [Note] mysqld: Shutdown complete
> 2016-03-28 01:16:58:
> 2016-03-28 01:18:40:160327 17:18:40 [Note] mysqld (mysqld 5.5.48) starting as process 1 ...
> 2016-03-28 01:18:40:160327 17:18:40 [Note] Plugin 'FEDERATED' is disabled.
> 2016-03-28 01:18:40:mysqld: Table 'mysql.plugin' doesn't exist
> 2016-03-28 01:18:40:160327 17:18:40 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
> 2016-03-28 01:18:40:160327 17:18:40 InnoDB: The InnoDB memory heap is disabled
> 2016-03-28 01:18:40:160327 17:18:40 InnoDB: Mutexes and rw_locks use GCC atomic builtins
> 2016-03-28 01:18:40:160327 17:18:40 InnoDB: Compressed tables use zlib 1.2.3
> 2016-03-28 01:18:40:160327 17:18:40 InnoDB: Using Linux native AIO
> 2016-03-28 01:18:40:160327 17:18:40 InnoDB: Initializing buffer pool, size = 128.0M
> 2016-03-28 01:18:40:InnoDB: mmap(137363456 bytes) failed; errno 12
> 2016-03-28 01:18:40:160327 17:18:40 InnoDB: Completed initialization of buffer pool
> 2016-03-28 01:18:40:160327 17:18:40 [Note] mysqld: Shutdown complete

**Comment by tianon** [comment]
This sounds like either you're out of memory, or you're trying to run mysql
on top of vboxsf's shared file system via
boot2docker/docker-machine/toolbox?
