### ISSUE TITLE
Docker: Mysql crashes after few seconds when it has been started

### ISSUE THREAD

**Issue by manueljordan** [docker-library/mysql#157]
Hello

The problem is explained in detail in:
[Docker: Mysql crashes after few seconds when it has been started](http://stackoverflow.com/questions/36264243/docker-mysql-crashes-after-few-seconds-when-it-has-been-started)

Thanks

**Comment by drewish** [comment]
That question has an accepted answer so can we assume this is fixed?

**Comment by manueljordan** [comment]
Yes, it works or is fixed. You can close this thread.

Thanks

**Comment by tianon** [comment]
Thanks!
