### ISSUE TITLE
Try to load sample data Sakila failed

### ISSUE THREAD

**Issue by ccp999** [docker-library/mysql#16]
Hi,

This is not an issue with your script but I failed to make an enhancement.  I want to load Sample data, Sakila (http://dev.mysql.com/doc/sakila/en/index.html) when the image run.

I added few lines in entrypoint.sh of both 5.6 and 5.7 sub directory  

echo 'FLUSH PRIVILEGES ;' >> "$TEMP_FILE"

	if [ "$MYSQL_SAKILA" ]; then
		SCHEMA_FILE='/tmp/sakila-db/sakila-schema.sql'
		DATA_FILE='/tmp/sakila-db/sakila-data.sql'

		cat "$SCHEMA_FILE" >> "$TEMP_FILE"
		cat "$DATA_FILE" >> "$TEMP_FILE"
	fi
	set -- "$@" --init-file="$TEMP_FILE"
fi

chown -R mysql:mysql /var/lib/mysql
exec "$@"

the newly added sql files loaded, but partly only and logs show:

2014-09-26 17:51:49 1 [Note] Execution of init_file '/tmp/mysql-first-time.sql' started.
ERROR: 1064  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER ;;' at line 1
2014-09-26 17:51:49 1 [Note] Execution of init_file '/tmp/mysql-first-time.sql' ended.

the same files can be loaded successfully from in mysql shell
source /tmp/sakila-db/sakila-schema.sql;
source /tmp/sakila-db/sakila-data.sql;

do you know any reason?

**Comment by icotix** [comment]
I figured out how Puppet does it (https://github.com/puppetlabs/puppetlabs-mysql/blob/master/manifests/db.pp). It's in that file ll. 60-70. It seems to me like they invoke the mysql executable and pipe the given sql file into it. I think something like that should be possible in the entrypoint shell file?

**Comment by yosifkit** [comment]
Looks like should be solved now that we run the full mysqld when importing provided sql files.

Closing old issue, if you feel this was closed in error please let us know.

**Comment by karlhorky** [comment]
We ran into this problem today when we were trying to automatically import a stored procedure into MySQL every time the container starts (in case the stored procedure code has changed since last start, eg. from a `pull` or something). The `--init-file` option will not work because it doesn't support `DELIMITER`s.

Can someone offer insight into how to do this with Docker and MySQL? We're using the `mariadb` image: https://hub.docker.com/_/mariadb/
