### ISSUE TITLE
Need some flag, that database initialization complete

### ISSUE THREAD

**Issue by aborilov** [docker-library/mysql#160]
I have some cases when MySQL can be stopped while database still initializing. In `docker-entrypoint.sh`, we just check that dir exists and if it not exist, create it and then initialize database, but if MySQL will be stopped after dir created but before database complete initialization, on next start we will have not properly initialized database. In my case, I have database without `MYSQL_USER` and can't connect to it.

I think we need to add some flag(file), that will be added only after database complete initialization.

**Comment by ltangvald** [comment]
But the image should also work with a database not initialized by the docker image. Checking for a flag we create would break this. Though we toyed with this idea for a slightly different use-case (running mysql_upgrade) before.

 --initialize (5.7) will refuse to run if there are any files in datadir, so if the database is in a half-complete state it won't work.

**Comment by aborilov** [comment]
> But the image should also work with a database not initialized by the docker image. Checking for a flag we create would break this.

that's true.
May be then we can do like in [centurylink/mysql](https://hub.docker.com/r/centurylink/mysql/) docker image:

```
if [[ $MYSQL_DATABASE != "" ]]; then
    echo "CREATE DATABASE IF NOT EXISTS \`$MYSQL_DATABASE\` CHARACTER SET utf8 COLLATE utf8_general_ci;" >> $tfile

    if [[ $MYSQL_USER != "" ]]; then
        echo "GRANT ALL ON \`$MYSQL_DATABASE\`.* to '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';" >> $tfile
    fi
fi
```

try to create db and add user every start?

**Comment by tianon** [comment]
See the discussion in #2 (and other linked issues there).
