### ISSUE TITLE
Error response from daemon: Container command 'docker-entrypoint.sh' not found or does not exist..

### ISSUE THREAD

**Issue by bernex** [docker-library/mysql#163]
I'm copied two files from 5.7 folder:

Run: `docker build -t mysql2 .` and `docker run -it -p 3306:3306 -t mysql2`

```
Error response from daemon: Container command 'docker-entrypoint.sh' not found or does not exist..
```

Why?

**Comment by thaJeztah** [comment]
If you're on Windows, make sure the `docker-entrypoint.sh` file is using the right line-endings (linux, not windows)

**Comment by yut148** [comment]
It I also became the same error.
I tried in the kitematic.
Is there a mistake in the Dockerfile?
$ uname -a
Linux default 4.4.8-boot2docker #1 SMP Mon Apr 25 21:57:27 UTC 2016 x86_64 GNU/Linux

**Comment by thaJeztah** [comment]
@yut148 hard to tell, the error message can have different causes; can be an issue in the Dockerfile, or the file you've set as entrypoint / cmd

**Comment by yut148** [comment]
Hi Mr.  @thaJeztah 
Thank you for reply.
My reply was delayed. I'm sorry.

This is no problem in a different environment.
I have tried the procedure wrote to the bottom.

I am now, can not be used temporarily before kitematic environment
Now I can not see properly.

But I think the permission of the problem.
entrypoint.sh

I thought this
It is amended as line 62.

61:RUN ln -s usr/local/bin/docker-entrypoint.sh /entrypoint.sh
62:RUN chmod 777 /entrypoint.sh

I do not think is necessarily a good answer.
I think but, however that there is better to work in a variety of environments.
It has no impact on other also by running the chmod with the RUN command.
Please tell me your opinion.

# docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true

git clone.
# git clone https://github.com/docker-library/mysql.git
# cd mysql/5.7

get this two files.
# ls  *
Dockerfile            docker-entrypoint.sh

# md5sum Dockerfile.
50a387bd2848bfd8e822f280109793d1  Dockerfile
# md5sum docker-entrypoint.sh 
7c1bdf8ef0487056753b8fe17fe7f715  docker-entrypoint.sh

build from Dockerfile
# docker build -t mysql2 . 

docker image This was made correctly.
# docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
mysql2                    latest              ea41f399a2f2        6 hours ago         379 MB

It works without problems.
# docker run -it -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=pass -e 
 MYSQL_DATABASE=mydb mysql2
