### ISSUE TITLE
5.7 fails to build Dockerfile due to unconfigured mysql-community-server

### ISSUE THREAD

**Issue by thyrlian** [docker-library/mysql#164]
When I try to build MySQL 5.7 image from the official [Dockerfile](https://github.com/docker-library/mysql/blob/master/5.7/Dockerfile) by myself, it always fails.

Stacktrace:
```console
Setting up mysql-community-server (5.7.12-1debian8) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
No directory, logging in with HOME=/
dpkg: error processing package mysql-community-server (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of mysql-server:
 mysql-server depends on mysql-community-server (= 5.7.12-1debian8); however:
  Package mysql-community-server is not configured yet.

dpkg: error processing package mysql-server (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Processing triggers for systemd (215-17+deb8u4) ...
Errors were encountered while processing:
 mysql-community-server
 mysql-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c { 		echo mysql-community-server mysql-community-server/data-dir select ''; 		echo mysql-community-server mysql-community-server/root-pass password ''; 		echo mysql-community-server mysql-community-server/re-root-pass password ''; 		echo mysql-community-server mysql-community-server/remove-test-db select false; 	} | debconf-set-selections 	&& apt-get update && apt-get install -y mysql-server="${MYSQL_VERSION}" && rm -rf /var/lib/apt/lists/* 	&& rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql' returned a non-zero code: 100
```

I know that the 5.7 image on Docker Hub was successfully generated using the same Dockfile, why not here?  (the only difference could be my docker version / environment I guess)

Actually I've tried to add below command into the Dockerfile, while the error still showed up:
```shell
ARG DEBIAN_FRONTEND=noninteractive
# or
RUN DEBIAN_FRONTEND=noninteractive apt-get install ...
# or
apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" ...
```

But when I built part of the image (without installing mysql-community-server), and setting `DEBIAN_FRONTEND` by hand then install mysql-community-server also by hand via the same script, it worked.

Steps:
1. Build an incomplete image (excluding steps since `apt-get install -y mysql-server="${MYSQL_VERSION}"`);
2. Run the image;
3. Create a bash session in the container: `docker exec -it <CONTAINER_NAME> bash`;
4. Set **DEBIAN_FRONTEND** by: `export DEBIAN_FRONTEND=noninteractive`;
5. Run the same script to install **mysql-community-server**: `apt-get update && apt-get install -y mysql-server="5.7.12-1debian8"`.

And it works this way.  Why it behaves differently though the scripts are equivalent?

Thanks in advance.

**Comment by thyrlian** [comment]
Reproducible with both `Docker version 1.10.3, build 20f81dd` and `Docker version 1.11.0, build 4dc5990` on `Mac OSX 10.11.4`.

**Comment by ltangvald** [comment]
I can't reproduce on trusty with 1.11.0. Might be a race condition, since it works when you do it manually. Will see if I can find a Mac to test :)

**Comment by thyrlian** [comment]
Thanks @ltangvald for helping :)

I'll also find another machine to try it.  BTW, it might not be a race condition, because on my side, when building the Dockerfile by myself, it always fails, not even one single time success :(

**Comment by ltangvald** [comment]
Couldn't reproduce on a machine with OSX 10.10.5

  Setting up mysql-community-server (5.7.12-1debian8) ...
  debconf: unable to initialize frontend: Dialog
  debconf: (TERM is not set, so the dialog frontend is not usable.)
  debconf: falling back to frontend: Readline
  No directory, logging in with HOME=/
  No directory, logging in with HOME=/
  invoke-rc.d: policy-rc.d denied execution of start.
  Setting up mysql-server (5.7.12-1debian8) ...

**Comment by ltangvald** [comment]
The machine didn't have Docker installed, so this was tested from a completely fresh install

**Comment by thyrlian** [comment]
Aha, good to know, thanks.

I'll also try with a different machine and let you know the results.

**Comment by thyrlian** [comment]
Tried with Travis, everything is fine:
```console
Setting up mysql-community-server (5.7.12-1debian8) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
No directory, logging in with HOME=/
No directory, logging in with HOME=/
invoke-rc.d: policy-rc.d denied execution of start.
Setting up mysql-server (5.7.12-1debian8) ...
```

Blame my machine...

Thanks again for the quick response, I'm gonna to close it.

**Comment by thyrlian** [comment]
@ltangvald my colleague just told me that my `debconf-set-selections` error may caused by my `zsh`.  I'll try it out when I have time and post it here.

**Comment by thyrlian** [comment]
Just tried with `zsh` + a brand new docker vm, and everything is fine.  Don't know why the error occurred to me a few days ago.

**Comment by boussou** [comment]
I came across the yes Unix binary, which is incredibly stupid: it just endlessly types y (try it, you can just run yes in your terminal)

so the following just works (I used this in a dockerfile)
      
    yes | apt-get install mysql-community-server

**Comment by yosifkit** [comment]
`apt-get` already has an option for assuming yes as the answer to all prompts (https://manpages.debian.org/bullseye/apt/apt-get.8.en.html#OPTIONS)
```console
apt-get install -y mysql-community-server
```

**Comment by boussou** [comment]
> `apt-get` already has an option for assuming yes as the answer to all prompts (https://manpages.debian.org/bullseye/apt/apt-get.8.en.html#OPTIONS)
> 
> ```
> apt-get install -y mysql-community-server
> ```

Yes, I know, but with mysql it does not work. it enters interactive mode anyway so with docker it ends up in failed build.

**Comment by yosifkit** [comment]
Ah, yes; debconf (the thing doing the interactive bits) doesn't get anything from the `-y` or take a hint from the fact that there is no TTY. So it either requires the config up front (like we do in the [Dockerfile](https://github.com/docker-library/mysql/blob/dfb9d3429d157b60b56d998118fbb7e20482b58b/template/Dockerfile.debian#L64-L73)) or you should be able to run the `apt-get install -y ...` with `DEBIAN_FRONTEND=noninteractive` set.
```dockerfile
RUN set -e; \
    apt-get update; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y [packages]

# alternative && version
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y [packages]
```

**Comment by boussou** [comment]
Interesting idea. I will try this even if there is  in beginning of the Dockerfile

    
      ENV DEBIAN_FRONTEND noninteractive
