### ISSUE TITLE
SELECT ... INTO OUTFILE generated files cannot be SOURCE'd in Dockerized MySQL container

### ISSUE THREAD

**Issue by ye** [docker-library/mysql#166]
Following [Peter Zeitsev's note to mass killing sleeping processes](https://www.percona.com/blog/2009/05/21/mass-killing-of-mysql-connections/) (most likely connection pooling leaks?),  but it didn't work on a dockerized MySQL container although it surely was generated.

``` shell
$ docker run -it --link mysql:mysql --rm mysql sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD" --default-character-set=utf8mb4'
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 30119
Server version: 5.6.30 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select concat('KILL ',id,';') from information_schema.processlist where user='root' into outfile '/tmp/a.txt';
Query OK, 1 row affected (0.01 sec)

mysql> source /tmp/a.txt;
ERROR: 
Failed to open file '/tmp/a.txt', error: 2

mysql> select concat('KILL ',id,';') from information_schema.processlist where user='root' into outfile '/tmp/a.txt';
ERROR 1086 (HY000): File '/tmp/a.txt' already exists

mysql> ^DBye
maven@debian-8:~$ docker run -it --link mysql:mysql --rm mysql /bin/bash
root@bc7fc955d025:/# 
```

**Comment by yosifkit** [comment]
Is this all in a `docker exec`?  What is the ownership and permissions of the temporary file?

**Comment by ye** [comment]
@yosifkit updated issue description. I use `docker run` as instructed in the [official docker hub receipt](https://hub.docker.com/_/mysql/). If I run the shell in docker, it gives me `root`. Since there is no `USER` instruction in the [current MySQL 5.6 Dockerfile](https://github.com/docker-library/mysql/blob/d7e71447ff3ad3c579ac3cca8c0dc090d11d4baf/5.6/Dockerfile) I assume the ownership and permission should be `root`.

**Comment by yosifkit** [comment]
I think I see the issue: the `select into outfile` is creating a file in the mysql server container file system while `source` is reading a file from the client file system.  I think swapping to use `docker exec` should work.

```console
$ # Something like this
$ docker exec -it mysql sh -c 'exec mysql -uroot -p"$MYSQL_ROOT_PASSWORD" --default-character-set=utf8mb4
```

Reference:
> from the mysql docs for [`select into`](https://dev.mysql.com/doc/refman/5.7/en/select-into.html)
> The SELECT ... INTO OUTFILE statement is intended primarily to let you very quickly dump a table to a text file on the server machine

**Comment by ye** [comment]
Thank you @yosifkit it does seem to work indeed. Perhaps this should be noted on https://hub.docker.com/_/mysql/ ?

**Comment by ye** [comment]
I do think the README page should have a mention of using `docker exec` if one wants to access local volumes. But otherwise consider this is closed.

**Comment by tianon** [comment]
Sorry for the delay!  Personally, I think this is esoteric enough a use case to not really be necessary to document (folks looking for it should be able to find this issue and thus discussion without too much trouble).

Glad you got it working though!
