### ISSUE TITLE
With Debian6 eol, MySQL 5.5 will no longer be updated for any deb platforms.

### ISSUE THREAD

**Issue by ltangvald** [docker-library/mysql#168]
MySQL 5.5 was only supported on Debian 6, and since that's now eol we can't expect any new 5.5 packages to be released for any Debian/Ubuntu platforms.

A few options:
Keep it at the current version:
Not a good idea, since no more updates will be released, security or otherwise

Change to a different base image:
Oracle's own Docker images use OracleLinux as a base, and it will still get packages. The base image is much larger than Debian's, but currently this won't affect the total size much (actually make it smaller) since we use a custom rpm for Docker with various things removed. Main disadvantage is that it would break any images that are based on the image and then do anything deb-specific (e.g. apt). There are also some differences in the default config and file locations (my.cnf is in /etc/ instead of /etc/mysql/) that we'd need to deal with.

Drop it:
Do we know how much use there is of the 5.5 image? Is there any way to see download figures for a single tag?

**Comment by yosifkit** [comment]
Alternative option is to move to Ubuntu:14.04.  This wouldn't have the deb-specific issue that Oracle Linux has while still getting us to a supported OS.

We definitely should not just keep it as is and should switch to Oracle, Ubuntu, or drop it.

I could email the guys at Docker and see if we can get any stats on recent 5.5, 5.6, and 5.7 image downloads; what sort of threshold would we consider small enough that we're "safe" to stop supporting?  Or maybe we just switch to Ubuntu for 5.5 and add Oracle Linux variants to everything (and when we get to 5.8, switch over to Oracle-only)?

**Comment by ltangvald** [comment]
If we switch to distro native packages, we could just use the 5.5 that's in Debian? The 5.5 in Ubuntu is pretty much identical to the one in Debian.

The problem with Oracle Linux as a base image is that it's so big compared to Debian. We're doing some work on optimizing size for Docker, so we'll see what comes of that.

--
Lars

**Comment by yosifkit** [comment]
I would rather stick with the upstream packages and downloads since the Debian packagers might not follow what MySQL recommends. For example, they could change the default `my.cnf`.

I was suggesting that we swap out Debian on the `5.5` image since the [supported platforms page](https://www.mysql.com/support/supportedplatforms/database.html) shows the "EOL Notice" (and swap in a "supported" distro, which it appears "Ubuntu 14.04" still is, and is relatively similar to Debian which should keep the "downstream breakage" and size difference to a minimum).

**Comment by tianon** [comment]
Is this still relevant?  From what I can tell, we've never actually used packages for installing MySQL 5.5, and have always downloaded the released binary tarballs instead (to this very day, in fact).

If we need to swap the base to stay upstream-supported, I'm still +1 on doing so (especially if we can keep the downstream impact minor).  I imagine most folks are simply running this image as-is, perhaps with some adjusted configuration, so even if we swapped to Ubuntu the downstream impact should be low (and hopefully the usage of MySQL 5.5 in the wild is low as well, further decreasing the impact).

**Comment by ltangvald** [comment]
Hi
Sorry for the slow response.
No, this isn't relevant any longer (with regards to switching base, I'm starting work on porting over upstream's templated setup so we can provide both without increasing maintenance load)
