### ISSUE TITLE
Provide example of providing custom image with contributed data

### ISSUE THREAD

**Issue by kostajh** [docker-library/mysql#169]
In the docs, we have this line:

> You can easily populate your mysql services by mounting a SQL dump into that directory and provide custom images with contributed data.

Could someone provide an example of how to do this for the project docs? I've searched a bit and have found a bunch of folks saying that they couldn't figure out how to do this, and no specific examples of how to make this work.

**Comment by tianon** [comment]
Sorry for the delay!  See https://github.com/docker-library/docs/tree/cc947df91fedc48232d3772d01f61a8874e126f9/mysql#initializing-a-fresh-instance, which is included in the current set of docs.

It really is as simple as dropping `.sql` files in `/docker-entrypoint-initdb.d`, either via something like `-v /path/on/host/to/some-file.sql:/docker-entrypoint-initdb.d/some-file.sql` on a `docker run` line or `COPY some-file.sql /docker-entrypoint-initdb.d/` in a `Dockerfile`.
