### ISSUE TITLE
is there any instruction for extending it

### ISSUE THREAD

**Issue by junneyang** [docker-library/mysql#174]
eg:

FROM mysql:5.6
xxx
xxx
xxx

thanks a lot!

**Comment by ltangvald** [comment]
In general it will depend a lot on what you want to do. The main thing to keep in mind is probably the entrypoint script, which will always run when the image is started:
https://github.com/docker-library/mysql/blob/master/5.7/docker-entrypoint.sh

**Comment by junneyang** [comment]
@ltangvald 
thanks, does the docker-entrypoint.sh excute before the CMD or after the CMD?
it seems that the docker-entrypoint.sh not run at all.

1、Dokerfile:
FROM mysql:5.6
COPY run.sh /
RUN chmod a+x /run.sh
CMD ["/bin/bash", "-c", "env && cd / && ./run.sh"]

2、run.sh
#!/bin/bash
set -x

mysqld &
CONNECTED=$(netstat -alnt | grep -c ":3306 ")
while [ ${CONNECTED} -eq 0 ]; do
    echo "MYSQL NOT CONNECTED YET";
    sleep 5;
    CONNECTED=$(netstat -alnt | grep -c ":3306 ")
done

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" -e "SHOW DATABASES;"
tail -f /var/log/mysql/error.log

3、mysql log：
![qq 20160527101605](https://cloud.githubusercontent.com/assets/6802322/15595744/35c8cf96-23f4-11e6-8ec5-45988add7554.png)

is there any problem in my Dockerfile or run.sh？
thanks！

**Comment by ltangvald** [comment]
CMD will be sent as an argument to docker-entrypoint.sh, so whether it gets executed depends on the entrypoint script. The entrypoint script in the mysql image will execute any command that _isn't_ "mysqld" unaltered.

The problem seems to be that you changed the CMD from mysqld to bash, meaning database initialization is skipped, causing the error you see.

**Comment by junneyang** [comment]
@ltangvald 
thanks a lot, i see.

so,after i change my run.sh script 
from: mysqld &
to: /entrypoint.sh mysqld &

it works!
