### ISSUE TITLE
mysql fails to start since arbitrary --user values were allowed

### ISSUE THREAD

**Issue by bhearsum** [docker-library/mysql#175]
I pulled in the latest mysql image recently and found that mysqld was failing to start. After some debugging, I realized that I removed the new if block added in https://github.com/docker-library/mysql/commit/a6f4c23621421bb708ad44616532d3d1cf44f6bf#diff-17ed820d5141a5e8565a0431e5385daeR24, mysqld started fine.

I couldn't find any additional logs when poking around the image interactively, but I did notice that mysqld was attempting to start in a loop (I'd see one pid for it, then it would disappear, then another). The only output I had was:

```
* Working around permission errors in Docker on Mac locally by making sure that "mysql" uses the same uid and gid as the host volume
-- Setting mysql user to use uid 0
usermod: no changes
-- Setting mysql group to use gid 0

* Starting MySQL
```

**Comment by bhearsum** [comment]
Oops, just realized that I have a workaround for the issue that that commit fixed. Removing the workaround fixes me.

**Comment by drewish** [comment]
@bhearsum so you were using something like: https://github.com/docker-library/mysql/issues/99 ? did you just ditch the script or did you start passing in a user?

**Comment by bhearsum** [comment]
Yeah, I was using that script. Deleting the script got my image working again on Linux, but not on Mac :(. Still looking for a workaround for that.

**Comment by drewish** [comment]
Yeah I'm using the beta on Mac and that work around script is now no longer necessary.

**Comment by bhearsum** [comment]
The beta of Docker and/or Docker Compose?

**Comment by drewish** [comment]
Exactly, with the new stuff I was able to just use the image's stock entry point and skip the work around:
```
entrypoint: /entrypoint.sh mysqld --user=mysql --console --explicit_defaults_for_timestamp=OFF
```

**Comment by bhearsum** [comment]
Ah, cheers. I didn't realize it wasn't released yet!

**Comment by dmitrym0** [comment]
@bhearsum, @drewish  can you shed some light on what you did to make this work without the workaround script?

**Comment by drewish** [comment]
@dmitrym0 I'm not sure what more detail I can provide. What are you trying?

**Comment by bhearsum** [comment]
@dmitrym0 Using the latest Beta (DockerToolbox-1.11.1b.pkg) it just worked without the script. Unfortunately, you have to sign up and wait for an invite code to get the Beta.
