### ISSUE TITLE
--user flag ignored

### ISSUE THREAD

**Issue by davidsteinsland** [docker-library/mysql#176]
Perhaps I may be mistaken here, but is the `--user` flag ignored?

Running the mysql container with `--user=root` or even `--user=foobar` results in nothing: the entrypoint is running as user `999` (mysql).

This is because of this line:

``` sh
# allow the container to be started with `--user`
[...]
exec gosu mysql "$BASH_SOURCE" "$@"
```

The `--user` flag is only allowed when `mysqld` is running as root. So why are you `exec`'ing `$BASH_SOURCE` as the mysql user? Because the mysql user is not a sudo user, it can never be allowed to fork the process as another user.

Test by setting `user = root` in `/etc/mysql/my.cnf` and running with `--user=root`:

```
2016-06-02 06:56:44 0 [Note] mysqld (mysqld 5.6.30-log) starting as process 1 ...
2016-06-02 06:56:44 1 [Warning] Can't create test file /var/lib/mysql/c73526b12455.lower-test
2016-06-02 06:56:44 1 [Warning] Can't create test file /var/lib/mysql/c73526b12455.lower-test
2016-06-02 06:56:44 1 [Warning] One can only use the --user switch if running as root

mysqld: File '/var/lib/mysql/mysql-bin.index' not found (Errcode: 13 - Permission denied)
2016-06-02 06:56:44 1 [ERROR] Aborting

2016-06-02 06:56:44 1 [Note] Binlog end
2016-06-02 06:56:44 1 [Note] mysqld: Shutdown complete
```

**Comment by yosifkit** [comment]
Are you passing the `--user` flag to `docker` or `mysqld`?  The current script does not support modifying the user in mysql's configuration.

Many users are wary of the "running as root in a container" so rather than relying on them to supply `user` in their mysql config, they must either be fine with the container automatically chowning the data directory to `mysql` and then immediately stepping down from `root` to `mysql`, or supplying a user as an argument to `docker run` (ie `docker run --user 1000 -d mysql`) and being responsible for permissions of any mounted directories used by `mysqld`.

**Comment by tianon** [comment]
We could try to parse MySQL's flags for a `--user`, but I think the returns over just using `docker run --user` directly (and never having `root` inside the container at all) greatly outweigh the added maintenance burden of doing so.

**Comment by dmitrym0** [comment]
Don't mean to hijack, but @tianon can you help me understand how *mysql* manages to own the files in the host mounted volume? That is, `docker run -v mysql:/var/lib/mysql` -- the files in mysql on the host are owned by the UID of the *mysql* user in the container. I'm trying to replicate this in my own container but I'm not having much luck, even though the directory is owned by the application user. I looked at *docker-entrypoint.sh*, but I can't really make sense of it. Can you help me understand how *mysql* user inside the container ends up owning *new* files in the host mounted volume?

**Comment by tianon** [comment]
@dmitrym0 the bit you're looking for is https://github.com/docker-library/mysql/blob/c7c1d85475749066b229691ade668bc49139d52f/5.7/docker-entrypoint.sh#L24-L30, which is perhaps easier to understand pre-`--user`-support: https://github.com/docker-library/mysql/blob/3288a66368f16deb6f2768ce373ab36f92553cfa/5.7/docker-entrypoint.sh#L31-L32

**Comment by dmitrym0** [comment]
@tianon many thanks! I discovered that I accidentally started a service with root, instead of the application user. That certainly screwed things up! Thanks again.

**Comment by tianon** [comment]
Closing since this appears solved. :+1:
