### ISSUE TITLE
E: Version '5.7.13-1debian8' for 'mysql-server' was not found

### ISSUE THREAD

**Issue by mmkonrad** [docker-library/mysql#177]
We receive same error as  [issue 139](https://github.com/docker-library/mysql/issues/139)
with red output as stated in the headline.

Even though we considered your update [Update to 5.7.13-1debian8, 5.6.31-1debian8, 5.5.50 ](https://github.com/docker-library/mysql/commit/f7a67d7634a68d319988ad6f99729bfeaa84ceb2) we continue to receive this error.

Thus I looked into the apt [package list of debian](https://packages.debian.org/stable/database/).
There is no mysql-server package of this version. Only 5.5.49-0+deb8u1.

If I use this package with `MYSQL_MAJOR 5.5` and `MYSQL_VERSION 5.5.49-0+deb8u1` it resolves into this error: 
```
W: Failed to fetch http://repo.mysql.com/apt/debian/dists/jessie/InRelease  Unable to find expected entry 'mysql-5.5/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

and as already seen in the stated issue:

```
The command '/bin/sh -c {               echo mysql-community-server mysql-community-server/data-dir select '';          echo mysql-community-server mysql-community-server/root-pass password '';            echo mysql-community-server mysql-community-server/re-root-pass password '';            echo mysql-community-server mysql-community-server/remove-test-db select false;      } | debconf-set-selections      && apt-get update && apt-get install -y mysql-server="${MYSQL_VERSION}" && rm -rf /var/lib/apt/lists/*  && rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql /var/run/mysqld  && chown -R mysql:mysql /var/lib/mysql /var/run/mysqld  && chmod 777 /var/run/mysqld' returned a non-zero code: 100
```

What shall we do now, any ideas?

**Comment by mmkonrad** [comment]
About the title change: we also tried different versions before checking the official package list

**Comment by ltangvald** [comment]
Hi,

There are no 5.5 packages on repo.mysql.com, as upstream does not publish true apt packages for MySQL 5.5, only simple tarballs. I believe the commit your refer to hasn't been published to the image yet.

You can build the image from the github source by checking out the github source and running
 docker build -t <imagename> 5.5/ from the source tree (replacing 5.5 with 5.6 or 5.7 if desired)

**Comment by mmkonrad** [comment]
very weird....
Now the build has gone through...

There were no changes within your dockerfile except these two lines. We added some stuff afterwards for our own purposes, but they couldn't affect your part and the build crashed long before our changes could get applied.

Nevertheless now it works. Thank You!!

**Comment by klsetzer** [comment]
5.7.14-1debian8 works as of today.

**Comment by max123max** [comment]
Today I got below error:

E: Version '5.7.14-1debian8' for 'mysql-server' was not found

Any suggestions??

**Comment by yosifkit** [comment]
The apt repo only contains one version at a time, so it is now `5.7.15-1debian8`.  Which is reflected in the most recent [Dockerfile](https://github.com/docker-library/mysql/blob/9f95658f528699d2c2017ca42ad163a9d5c5e7c1/5.7/Dockerfile#L33).  Older docker images are available through a docker pull, but will not be updated with base image fixes.
