### ISSUE TITLE
"Tag 5.7.13 not found in repository docker.io/library/mysql"

### ISSUE THREAD

**Issue by jboynton** [docker-library/mysql#183]
Trying to build an image using `FROM mysql:5.7.13` in a Dockerfile yields the error `Tag 5.7.13 not found in repository docker.io/library/mysql`, and when building `FROM mysql:5.7`, the MySQL version in the built image is 5.7.12.

The [Repo Description page](https://hub.docker.com/_/mysql/) says that 5.7.13 is a supported tag.

**Comment by yosifkit** [comment]
It should be there now.

**Comment by jboynton** [comment]
Thanks!
