### ISSUE TITLE
Load host folder to container got problem with running mysql

### ISSUE THREAD

**Issue by baozilala** [docker-library/mysql#190]
docker run -it -d -p 80:80 -v /Users/xxx/Docker/lamp/data/mysql:/var/lib/mysql -v /Users/xxx/Docker/lamp/www:/var/www/html 293ef2f50d98

_if i run command without " -v /Users/xxx/Docker/lamp/www:/var/www/html ", mysql could run normally_

I used 
     `docker run -it -d -p 80:80 -v /Users/xxx/Docker/lamp/data/mysql:/var/lib/mysql -v /Users/xxx/Docker/lamp/www:/var/www/html 293ef2f50d98`
to load host folder to container and mysql service couldn't run correctly ,error code is:
[....] Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . .[FAI failed!

i tried mysql -uroot -p i got error:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

also i checked  /var/lib/mysq permissions:
drwxrwxrwx  6 root root  204 Jul 11 03:11 mysql

when i use command: service mysql start, /var/lib/mysql folder will generate 3 log files.
ib_logfile0    -  5.2mb
ib_logfile1    -  5.2mb
ibdata1    -  18.9mb

and I searched many many websites but can't find a solution. anyone know what's going on here?

**should i run php env & mysql in different containers?**

**Comment by yosifkit** [comment]
I guess I should've made my https://github.com/docker-library/mysql/issues/66#issuecomment-232518594 over here.

> should i run php env & mysql in different containers?

Yes, containers let us have separation of concerns and with the layered file systems used by docker the images can share their space used, like `FROM debian:jessie`.

**Comment by baozilala** [comment]
Thank you for answering this simple question which is important to me.

**Comment by baozilala** [comment]
Thanks for helping me!
I give up to build my own MySQL container and I pull from docker hub, it works great. thanks.
