### ISSUE TITLE
Allow multiple volumes to be mounted as init scripts for mysql

### ISSUE THREAD

**Issue by mtzmontiel** [docker-library/mysql#192]
Currently this image loads only the first level on path: 

```
 /docker-entrypoint-initdb.d/
```

So if some wanted to use multiple volumes mounted under that only the lowest level would be executed.

I want to use volumes or to order init scripts in a more meaningful manner:

```
/docker-entrypoint-initdb.d/00-create-schemas.sql
/docker-entrypoint-initdb.d/10-myschema-seed/10-schema-1.sql
/docker-entrypoint-initdb.d/20-myschema-seed/10-schema-2.sql
/docker-entrypoint-initdb.d/30-myschema-seed/10-schema-3.sql
```

**Comment by tianon** [comment]
Closing for the same reasons as the associated PR: https://github.com/docker-library/mysql/pull/193

**Comment by tianon** [comment]
(Suggested workaround is to drop a short `.sh` file instead which sources additional directories.)
