### ISSUE TITLE
signalling for indicating init process is finished

### ISSUE THREAD

**Issue by hans-d** [docker-library/mysql#2]
when doing a scripted deploy, and the mysql image is deployed for the first time, it would be useful that a script can wait for the init process (eg creation of database) to be finished (without having to sleep for some time). Eg a touched file in /var/lib/mysql that is only available when the init process has run.

**Comment by ltangvald** [comment]
When starting the server, you can pass the --socket=<file> option to the server. The presence of the socket file should indicate that the server is ready.

**Comment by Toub** [comment]
I experience the same issue.

I am using ansible to automated my deployment, so immediately after have started this container, I try to create databases and users, then to connect a few servers to it.

I guess this is the responsibility of mysql container to accept connections immediately once it is started from docker point of view.

**Comment by tianon** [comment]
Sorry for the delay, but I'm going to close, since I don't see a sane way for us to possibly implement this -- I'd recommend trying one of the solutions above (especially attempting to connect externally, perhaps even via Docker's own `HEALTHCHECK` feature).  Sorry!
