### ISSUE TITLE
Problem with `/bin/bash -c` running mysql deamon

### ISSUE THREAD

**Issue by silgon** [docker-library/mysql#202]
I'm trying the `mysql` container. The `CMD` parameter for that container is `mysqld`. Therefore, the following parameters are the same.

```
docker run --name db -e MYSQL_ROOT_PASSWORD=proot --rm mysql
docker run --name db -e MYSQL_ROOT_PASSWORD=proot --rm mysql mysqld
```

Now the problem arrives when I want to use multiple commands. In order to use multiple commands in a docker container you have to use `/bin/bash -c`. I exemplify by using only the `mysqld` command:

```
docker run --name db -e MYSQL_ROOT_PASSWORD=proot --rm mysql /bin/bash -c "mysqld"
```

This command throws me the following error.

```
mysqld: Table 'mysql.plugin' doesn't exist
```

And then mysql deamon stops and I don't understand the reason.

I want to use the `/bin/bash -c` syntax because I want to use multiple commands like first starting the deamon and then something else `mysqld & some other command`. I don't want to create another container as a workaround for this problem.

Sidenote: I'm using `--rm` because I'm troubleshooting, otherwise I'll use `-d` to detach the container.

**Comment by yosifkit** [comment]
The entyrypoint scipt only does the initdb if `mysqld` is the argument; in your case it sees `bash` and so skips the initdb and just runs `bash` with its arguments.  If you are just trying to run some setup scripts once mysql is running have you looked at [`/docker-entrypoint-initdb.d/`](https://github.com/docker-library/docs/tree/5d45830797c837126d7802b0fab114075dac11b6/mysql#initializing-a-fresh-instance)?  You can put any `.sh` files or `.sql` files in there and they will be run/imported before the mysql service is available outside the container.

**Comment by silgon** [comment]
Ok, that solves my problem. I'll try it out. Thanks! =)

**Comment by wilcool** [comment]
god! I finally found what I needed..
