### ISSUE TITLE
Change current container port

### ISSUE THREAD

**Issue by adityosnrost** [docker-library/mysql#203]
Hi,

I would like to change my current container port of MySQL into another one. Let say that current setting is on port 7000 and I would like to change it into 8000. From what I found from surfing internet, is this:

1. Stop current container
2. Build an image from current container using commit
3. Run new container using committed image from container before.

But, when I check it, every settings and data on my old MySQL container is not migrated. Anyone has a thought about this?

Thanks

**Comment by ltangvald** [comment]
By default, the data in the container will be stored in a volume location, which will not be included when committing the container to a new image. https://docs.docker.com/engine/tutorials/dockervolumes/ is a helpful resource about volumes.

A simple way to keep your data from container to container is to mount the data directory to a location on your host machine with the -v flag, so something like:
  docker run -v /path/to/data:/var/lib/mysql [other options] mysql

**Comment by adityosnrost** [comment]
Hi,

Thank you so much for your reply. Now, I understand about data storage for docker. Really helpful guide.
So, for my case, if I can locate the volume data of my old container and used it / mount it into my new MySQL container, I can find the same data and settings just like the previous container used, right ?

Thanks

**Comment by ltangvald** [comment]
Yes, inspecting the container you should see something like:
"Mounts": [
            {
                "Name": "5104ce3aef9ba073d205fd7bc693882adcca2397b052eb69204818c99de4fc44",
                "Source": "/docker/volumes/5104ce3aef9ba073d205fd7bc693882adcca2397b052eb69204818c99de4fc44/_data",
                "Destination": "/var/lib/mysql",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],

Where the "Source" path is the data location on your host machine

**Comment by adityosnrost** [comment]
Thank you so much for your help. This is really helpful knowledge of using MySQL with Docker.

**Comment by ltangvald** [comment]
You're welcome! :)
