### ISSUE TITLE
Access denied for user 'root'@'172.17.0.1' (using password: YES)

### ISSUE THREAD

**Issue by eldermoraes** [docker-library/mysql#217]
Hi,

I have just created a new container with this command:

`docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=myql -d mysql:latest`

When I try to connect with MySQL Workbench (using localhost) I get the message:

_Access denied for user 'root'@'172.17.0.1' (using password: YES)_

Any help?

**Comment by ltangvald** [comment]
The above works for me. You're sure you're entering the correct password (it's myql, not mysql)?

**Comment by eldermoraes** [comment]
Shame on me! Sorry...

**Comment by ltangvald** [comment]
np :)

**Comment by rcarmonad** [comment]
1 hour with the same problem and it WAS the password.

**Comment by xyrin-amit** [comment]
Access denied for user 'c77512ad-9b1d-4782-81a4-9c0c7f90c54a'@'172.21.0.7'

**Comment by manishsinh** [comment]
ERROR 1130 (HY000): Host '172.17.0.1' is not allowed to connect to this MySQL server

got the same problem but not because of password

**Comment by cccccong** [comment]
Why is IP 172.17.0.1 different from what I set

**Comment by htnphu** [comment]
lol, anybody help me with this problem :((

**Comment by htnphu** [comment]
To fix this, you need to create a new user with access from 172.17.0.1. If you do not want to allow root connections from 172.17.0.1, you can create a new user with access from that IP address.

To do this, connect to your MySQL server as the root user and run the following command:

1. CREATE USER 'localhost'@'172.17.0.1' IDENTIFIED BY 'your_new_password';
2. GRANT ALL PRIVILEGES ON [your_db_to_connect].* TO 'localhost'@'172.17.0.1';

Once you have granted the new user the necessary privileges, you can use it to connect to your MySQL server from 172.17.0.1.

const connection = mysql.createConnection({
    host: "localhost",
    port: port,
    user: "your_user",
    password: "your_new_password",
    database: "your_db_to_connect",
  });

**Comment by buithanhlong091295** [comment]
> To fix this, you need to create a new user with access from 172.17.0.1. If you do not want to allow root connections from 172.17.0.1, you can create a new user with access from that IP address.
> 
> To do this, connect to your MySQL server as the root user and run the following command:
> 
> 1. CREATE USER 'localhost'@'172.17.0.1' IDENTIFIED BY 'your_new_password';
> 2. GRANT ALL PRIVILEGES ON [your_db_to_connect].* TO 'localhost'@'172.17.0.1';
> 
> Once you have granted the new user the necessary privileges, you can use it to connect to your MySQL server from 172.17.0.1.
> 
> const connection = mysql.createConnection({ host: "localhost", port: port, user: "your_user", password: "your_new_password", database: "your_db_to_connect", });

thank you so much bro, I wasted a whole day for this f*cking problem, you're my hero
