### ISSUE TITLE
mysql:5.6 shuts down in init and doesn't come back with docker-compose

### ISSUE THREAD

**Issue by kaihendry** [docker-library/mysql#224]
![mysql-5 6](https://cloud.githubusercontent.com/assets/765871/19470286/716dccbc-9551-11e6-868d-7a6e4ae58d07.png)

When I run `docker run -it --rm -e MYSQL_ALLOW_EMPTY_PASSWORD=true  mysql:5.6` I notice it stop and restart.  I don't know why.

However when I run it via `docker-compose up` & this http://s.natalian.org/2016-10-18/docker-compose.yml I notice it similarly start up & shutdown in init, but then it doesn't restart.

What am I missing?

**Comment by ltangvald** [comment]
Does your docker run command also work when you add a -p 3306:3306?

**Comment by ltangvald** [comment]
The stop and restart is because the entrypoint script in the image will start the server temporarily for things like running init scripts and setting up the root user correctly, so that's normal. Are there any error messages in the logs?

**Comment by kaihendry** [comment]
No error messages. It just exists?
```
~$ docker logs mysql_1
Error: No such container: mysql_1
```

I moved directory and then did a `docker-compose up` and it worked. I am not sure what went wrong.
