### ISSUE TITLE
docker commit the changes,but start error

### ISSUE THREAD

**Issue by wangyiran126** [docker-library/mysql#225]
i want to save docker neo4j database,and then restart it to continue use the data.
first i run the command to start neo4j
`docker run --publish=7474:7474 --publish=7687:7687 --volume=/Users/wangyiran/project/testplatformV6/data/neo4j1 neo4j:3.0`
after insert some data, i want to commit the changes
i use `docker ps` to find the neo4j continer id `429a3584673b`
then i run the command to commit the change
` docker commit 429a3584673b copy`
i checked the images through `docker images`,the `copy` exits

but when i want to restart the `copy` image
`docker start copy`
the report 
> Error response from daemon: No such container: copy
> Error: failed to start containers: copy

**Comment by ltangvald** [comment]
This seems to be in the wrong (mysql) section, but:
The commit command stores copy as an image, not a container, so you'd need to run «docker run copy» to create and start a container from the image.

**Comment by wangyiran126** [comment]
i run `docker run copy2`,but http://localhost:7475/browser/ cannot reached
