### ISSUE TITLE
Provide mechanism to extend mysql image with additional SQL init scripts

### ISSUE THREAD

**Issue by yarosla** [docker-library/mysql#24]
Please provide mechanism to extend this image by providing additional SQL scripts to be executed upon initial server startup.

See official [postgres](https://registry.hub.docker.com/_/postgres/) image for example on how this can be done (“How to extend this image” section in readme).

You can arrange special directory for SQL files. All `*.sql` files found in that directory shall be appended to `$TEMP_FILE` that will be passed as `--init-file` parameter to MySQL.

**Comment by johngian** [comment]
This would be really useful.
+1

**Comment by jorgemoralespou** [comment]
It is not very usable without this feature. I have done as williamsdev in his PR for make it woking for me, but something from the official images should come, as it does in the postgres one.

**Comment by ltangvald** [comment]
The changes we suggested in #53 should make this simpler to add, too, as the init sql is now just passed to the mysql client.

**Comment by tophsic** [comment]
+1

Actually, I did a similar thing as @williamsbdev in #31

**Comment by sherter** [comment]
+1
any news on this?

**Comment by sweco-semhul** [comment]
+1

**Comment by probepark** [comment]
+1

**Comment by ltangvald** [comment]
This would be fairly simple to add with the new system for initializing the database used in #53.
However, that change is meant to be a temporary workaround, so it's probably best to do this in a way that doesn't depend on it.

**Comment by tianon** [comment]
@ltangvald does that mean we're going to have a proper way to invoke instructions against `/var/lib/mysql` properly ala `postgres --single` without the silly limitations `--init-file` has? :smile:

**Comment by roytruelove** [comment]
+1
