### ISSUE TITLE
Separate setup part from entrypoint script

### ISSUE THREAD

**Issue by strarsis** [docker-library/mysql#242]
When a service/startup manager (e.g. [chaperone](https://github.com/garywiz/chaperone)) should 
be used, the startup with pid check/restarting is handled by it instead.

The setup part in the entrypoint script (that runs sh scripts or import sql dump files) should 
be separately callable by the startup manager as service dependency, without starting mysqld.

**Comment by yosifkit** [comment]
This is possible with the customization added in https://github.com/docker-library/mysql/pull/471. For example, just doing the initialization parts: https://github.com/docker-library/mysql/pull/423#issuecomment-562355462.
