### ISSUE TITLE
Looking for a detailed mySQL my.cnf configuration made for Docker 

### ISSUE THREAD

**Issue by pascalandy** [docker-library/mysql#244]
When launching a mysql container without any custom configs, we can see **two configs** within a container:

### 1)
```
cat /etc/mysql/conf.d/docker.cnf

[mysqld]
skip-host-cache
skip-name-resolve
```

### 2) 
```
cat /etc/mysql/mysql.conf.d/mysqld.cnf

[... comments...]

[mysqld]
pid-file	= /var/run/mysqld/mysqld.pid
socket		= /var/run/mysqld/mysqld.sock
datadir		= /var/lib/mysql
#log-error	= /var/log/mysql/error.log
# By default we only accept connections from localhost
#bind-address	= 127.0.0.1
# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0
```

### Question
Does it means that every other configs are plain vanilla from the mysql team?
Maybe I missed some?

### Here is my config
I'm looking for a great config so I started one here - https://gist.github.com/pascalandy/3ffb1b443fd143382a7cd2d4dae9a144

Curious to know what you guys is thinking about it.

Cheers!
twitter.com/_pascalandy

**Comment by ltangvald** [comment]
For the most part the config is completely vanilla, yes.
The problem with including a large custom config is that for the most part, the optimal configuration is very dependent on the database (size, performance requirements, etc.), and including a minimum config makes it easier to customize.

Having an online config repository for various scenarios does make sense (but maybe moreso as something upstream can manage), but setting a large, complex default config will create too many issues, I think.

**Comment by tianon** [comment]
Agreed, this image currently sticks as close as possible to the default upstream-provided configuration, and any other tweaks are very likely to be environment-specific.  As such, I'm going to close this; thanks!
