### ISSUE TITLE
Docker looses Database Connection

### ISSUE THREAD

**Issue by bevans** [docker-library/mysql#246]
I am new to Docker so any help would be appreciated. 

Docker will loose connection to an external database at various times, and this seems to happen for no reason. I have seen "Broken Pipe" in the log files only once. The other times the connection is dropped there has not been anything in the logs suggesting a failed connection until something tries to use it and then I get the standard JAVA sql error "The connection does not exist."

I would like to write a healthcheck to make sure that the external database is accessible. If it is not accessible I would like the docker container to restart automatically. How can I make this happen? I have seen the healthcheck option on the docker site, (https://docs.docker.com/engine/reference/builder/#healthcheck), but it does not mention an external server or database. I am also not sure how to restart on a failed connection attempt based on what the docker site states. Docker's examples shows to curl localhost with an exit 1 which mean to exit the docker as being unhealthy. That is fine, but how do I restart docker after that?

**Comment by ioggstream** [comment]
To restart the container automatically,   set the given option at "docker
rum" time.

About container stopping, try to re produce the issue.

R

Il 27 dic 2016 22:23, "bevans" <notifications@github.com> ha scritto:

**Comment by bevans** [comment]
@ioggstream 
The container does not stop, it just looses database connection. The connection was there on Friday when I went home, but by Monday morning the connection had been lost. This has happened twice where we had a weekend involved. The container has been up and used for a while. There has been a few weekends since this container has been put into use, but only the two times was the connection lost over a weekend. As for re-producing this, It seems that its because the container is not being used for a certain length of time, but we are not sure how long the container sits idle before it looses connection That does not really matter to me. What I want to know is how to detect if there is a connection to the database and if there is not a connection then I want the container to restart automatically. I have found how to do to restart, but I have found nothing to tell me how to determine if there is a connection to the database.

**Comment by ioggstream** [comment]
Iiuc:

- the mysql container is always up and running
- the application loses the connectivity to the db,  probably due to idle
time (this is tunable in mysql)
- in this case, you want to restart the app container
- you can check connected clients with 'show process list;'

Is that your case?

Why the app doesn't try to reconnect?


Peace, R


Il

**Comment by bevans** [comment]
You have one part that is not correct. 
The database is on a completely different server... the DB is not in or near a docker instance. That is what I meant when I said it is "external" so the "docker ps" does not show anything for the DB, just the app container that uses the DB. Sorry for the confusion. 
The rest of what you have stated is correct.
Yes, the DB connection is lost, probably due to idle.
Yes, when the DB connection is lost I want to restart the app container.

**Comment by ioggstream** [comment]
2016-12-28 0:04 GMT+01:00 bevans <notifications@github.com>:
> The database is on a completely different server...
How are you using this docker mysql image then?

> Yes, the DB connection is lost, probably due to idle.
> Yes, when the DB connection is lost I want to restart the app container.
imho the app should take care of reconnecting.

**Comment by ioggstream** [comment]
2016-12-28 16:53 GMT+01:00 bevans <notifications@github.com>:

> I am not using a mysql image

This bugtrack is for the mysql image ;)

Can you please close it and file it on the github of the image you use?

Peace,
R.
