### ISSUE TITLE
 [ERROR] InnoDB: mmap(137428992 bytes) failed; errno 12

### ISSUE THREAD

**Issue by otaroo** [docker-library/mysql#248]
| 2016-12-29T15:17:43.788366Z 0 [Note] mysqld (mysqld 5.7.17) starting as process 1 ...
db_1         | 2016-12-29T15:17:43.828795Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1         | 2016-12-29T15:17:43.829157Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1         | 2016-12-29T15:17:43.829561Z 0 [Note] InnoDB: Uses event mutexes
db_1         | 2016-12-29T15:17:43.829880Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1         | 2016-12-29T15:17:43.830462Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
db_1         | 2016-12-29T15:17:43.830593Z 0 [Note] InnoDB: Using Linux native AIO
db_1         | 2016-12-29T15:17:43.833323Z 0 [Note] InnoDB: Number of pools: 1
db_1         | 2016-12-29T15:17:43.838835Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1         | 2016-12-29T15:17:43.851010Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1         | 2016-12-29T15:17:43.851927Z 0 [ERROR] InnoDB: mmap(137428992 bytes) failed; errno 12
db_1         | 2016-12-29T15:17:43.852152Z 0 [ERROR] InnoDB: Cannot allocate memory for the buffer pool
db_1         | 2016-12-29T15:17:43.852458Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
db_1         | 2016-12-29T15:17:43.852561Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
db_1         | 2016-12-29T15:17:43.852657Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
db_1         | 2016-12-29T15:17:43.852745Z 0 [ERROR] Failed to initialize plugins.
db_1         | 2016-12-29T15:17:43.852838Z 0 [ERROR] Aborting
db_1         |
db_1         | 2016-12-29T15:17:43.856389Z 0 [Note] Binlog end
db_1         | 2016-12-29T15:17:43.857391Z 0 [Note] Shutting down plugin 'MyISAM'
db_1         | 2016-12-29T15:17:43.857947Z 0 [Note] Shutting down plugin 'CSV'
db_1         | 2016-12-29T15:17:43.860146Z 0 [Note] mysqld: Shutdown complete

**Comment by ioggstream** [comment]
2016-12-29 16:22 GMT+01:00 otaroo <notifications@github.com>:

> db_1 | 2016-12-29T15:17:43.851927Z 0 [ERROR] InnoDB: mmap(137428992 bytes)
> failed; errno 12
>

Seems your innodb_buffer_pool_size is bigger than the --memory allowed.

Peace,
R.
