### ISSUE TITLE
MySQL 5.7 error with alter table modify syntax and datetime type

### ISSUE THREAD

**Issue by pgeof** [docker-library/mysql#250]
If I run a new mysql:5.7 container and execute this piece of SQL :
```sql
create database test default character set utf8 default collate utf8_general_ci;
use test;
create table test (id int not null primary key auto_increment, column1 datetime not null);
alter table test modify column1 datetime not null after id;
```
I got this return after the last line : 
> ERROR 1138 (22004): Invalid use of NULL value

This issue appears only with the version 5.7. It works with 5.5 and 5.6.

**Comment by tianon** [comment]
Have you looked through any of https://dev.mysql.com/doc/relnotes/mysql/5.7/en/, https://dev.mysql.com/doc/refman/5.7/en/upgrading-from-previous-series.html, and/or https://dev.mysql.com/doc/refman/5.7/en/mysql-nutshell.html to see if there's any hints as to what's changed which might cause this?

**Comment by tianon** [comment]
(Either way, it's likely either an intentional change or a bug in 5.7, and not really related to anything special we've done in this image.)

**Comment by pgeof** [comment]
I didn't see any informations about a change.
Anyway you're right it's more like a general bug with mysql 5.7.

**Comment by ltangvald** [comment]
This issue is new in 5.7.17 (it works in the 5.7.16 image).

This is most likely related to the last entry in https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-17.html and how the server internally handles the «after <column>» operation.

I'll pass it on upstream, thanks :)
