### ISSUE TITLE
Is the history for mysql is disabled by default for the MySQL server ? 

### ISSUE THREAD

**Issue by krisnik** [docker-library/mysql#258]
MySQL writes commands history to the ~/.mysql_history file. I am not able to find that in the docker container.  Is logging disabled by default ? 

Thanks in advance.

**Comment by ioggstream** [comment]
2017-01-18 10:45 GMT+01:00 Nikhil Vedurumudi <notifications@github.com>:
>
> MySQL writes commands history to the ~/.mysql_history file.

It's the mysql client. See ```man mysql | less  +/"^MYSQL LOGGING"```
