### ISSUE TITLE
gpgkey cannot be retrieved

### ISSUE THREAD

**Issue by shitalm** [docker-library/mysql#263]
Not able to build from the Dockerfile. Running this on OS X and Docker for Mac

> gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net
> gpgkeys: key B42F6819007F00F88E364FD4036A9C25BF357DD4 can't be retrieved
> gpg: no valid OpenPGP data found.
> gpg: Total number processed: 0

But when I retrieve the same key on host (my mac) then it succeeds.
```
gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: directory `/Users/shital/.gnupg' created
gpg: new configuration file `/Users/shital/.gnupg/gpg.conf' created
gpg: WARNING: options in `/Users/shital/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/Users/shital/.gnupg/secring.gpg' created
gpg: keyring `/Users/shital/.gnupg/pubring.gpg' created
gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net
gpg: /Users/shital/.gnupg/trustdb.gpg: trustdb created
gpg: key BF357DD4: public key "Tianon Gravi <tianon@tianon.xyz>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

```
I can also successfully build on a centos server.
```
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: keyring `/tmp/tmp.sQeD1cISKM/secring.gpg' created
gpg: keyring `/tmp/tmp.sQeD1cISKM/pubring.gpg' created
gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net
gpg: /tmp/tmp.sQeD1cISKM/trustdb.gpg: trustdb created
gpg: key BF357DD4: public key "Tianon Gravi <tianon@tianon.xyz>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

```

Looks like an issue with docker on mac.

**Comment by yosifkit** [comment]
Sometimes it is the network connection of the VM, sometimes it is the route to the `ha.pool`, or even members of the pool being down. Have you tried restarting the docker daemon or docker VM?

**Comment by shitalm** [comment]
Multiple times. Same behavior. Also when its failing inside Mac on docker,  it's working on docker host at the same time.

**Comment by tianon** [comment]
GPG keyservers being flaky is a problem we see all too often -- closing since there's not really anything actionable here.  As a workaround, I'd recommend either pulling the pre-built images as-is (and perhaps building upon them via `FROM mysql:XXX` in a derivative `Dockerfile`) or adjusting the keyserver to one which your own local environment has an easier time fetching from (such as `hkp://keyserver.ubuntu.com:80` or similar).
