### ISSUE TITLE
Update auto_increment value is not working

### ISSUE THREAD

**Issue by MFoly** [docker-library/mysql#269]
alter table auto_increment is not working properly in initdb scripts.
I attached a sample configuration with the issue [docker-test.zip](https://github.com/docker-library/mysql/files/787416/docker-test.zip)

**Comment by jiangjingjiu** [comment]
I've met the same problem, especially for sql below:
ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8

I tried to rewrite sql like "Alter Table..."，it's not ok.
Have you found any ways to avoid this ? Or any work around ?

**Comment by jiangjingjiu** [comment]
I've found  the reason.
Please see link below:
http://serverfault.com/questions/228690/mysql-auto-increment-fields-resets-by-itself

It seems like the mysql bug, not docker.

**Comment by MFoly** [comment]
Yes , worked for me by adding dummy record after updating the auto_increment key. Many thanks for the help
