### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by ivor52** [docker-library/mysql#272]
over on the [documentation page ](https://hub.docker.com/_/mysql/), usage instructions refer to starting the mysql docker container using --link, followed by instructions for apps to connect to this container.

but this is outdated docker functionality: --link option is deprecated and will eventually be going away.

can the documentation be appropriately updated to use the docker bridge network that is automatically set up by the docker engine itself?

**Comment by tianon** [comment]
See https://github.com/docker-library/docs/pull/1063 and https://github.com/docker-library/docs/issues/786 for several recent discussions of this exact topic.
