### ISSUE TITLE
Every Project with the same IP

### ISSUE THREAD

**Issue by s1dekick223** [docker-library/mysql#278]
Hey guys,

My problem is: I've 4 Docker projects right now and i can only use one because on the other projects when i try to log into mySQL to import the db, the issue is coming up. '''#1130 - Host 'x.x.x.y' is not allowed to connect to this MySQL server''' (y=is new new number for every project).
How i cant setup my docker so that all my projects are running over x.x.x.1 so i can connect with mySQL.

Thanks 

s1de

**Comment by yosifkit** [comment]
If you are using the default mysql image and running it similar to below, then there is no restriction placed on where the root user can connect from; any container should be able to connect.  If you already have a database initialized, then you just need to update the user table; something similar to http://stackoverflow.com/a/14779244.

```console
$ docker run -d --name sql -e MYSQL_ROOT_PASSWORD=12345 mysql:5.7
# container id
$ docker run -it --rm mysql:5.7 mysql -h172.17.0.x -uroot -p12345
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.17 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```

**Comment by tianon** [comment]
Closing since this appears solved! :+1:
