### ISSUE TITLE
Error on mysql startup with `--initialize-insecure`

### ISSUE THREAD

**Issue by luhkevin** [docker-library/mysql#280]
I was running mysql:5.7 with volume mounts and encountered this error: 

```
2017-04-08T00:44:56.022067Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2017-04-08T00:44:56.022080Z 0 [ERROR] Aborting
```

I see that we pass the `--initialize-insecure` flag in the entrypoint, but the conditions for "initialization" are if `$DATADIR/mysql` is empty: https://github.com/docker-library/mysql/blob/master/5.7/docker-entrypoint.sh#L80

According to this [reference](https://dev.mysql.com/doc/refman/5.7/en/data-directory-initialization-mysqld.html),  `--initialize-insecure` will fail if the data directory is nonempty.

So wouldn't this create a race condition if I exit mysql during the initialization process, before the `mysql` directory has a chance to be created?

**Comment by ltangvald** [comment]
We don't really know a surefire way to make it robust, but there may be cases where the datadir is not empty and the initialize can succeed (files starting with . or directories the user explicitly set with --ignore-db-dir, while if datadir/mysql (the system tables) is missing, mysql can't be expected to work.
The error message from the server explains the issue fairly well, I think

**Comment by luhkevin** [comment]
Yeah, I think the files that were in the directory were `ibdata1` or `ib_logfile`. 
Don't see `--ignore-db-dir` passed anywhere.

**Comment by qdequippe** [comment]
I have exactly the same problem, @luhkevin did you find a way to fix it?

**Comment by tianon** [comment]
I think unless we have a reliable way to reproduce this, there's not much more we can do to help -- this does indeed sound like a previous initialization which failed, causing subsequent runs to also fail.  Since we can't reproduce, I'm going to close, but if a reliable reproducer can be found, a new detailed issue would be appreciated!  Thanks!

**Comment by Jumaev** [comment]
Facing the same problem here pls could any one explain the solution neatly

**Comment by ltangvald** [comment]
@Jumaev: When the container starts, if /var/lib/mysql/mysql does not exist, mysqld --initialize-insecure will be executed. --initialize requires /var/lib/mysql to be empty (but can be configured to ignore specific files).

If you're seeing this issue, presumably you're mounting /var/lib/mysql to the host, with something like
 -v /somepath/mysqldata:/var/lib/mysql
For this to work, /somepath/mysqldata/ must either contain a functional database, or be completely empty.

**Comment by kuhnroyal** [comment]
No, just a normal folder in Ubuntu, nothing shared or the like.
