### ISSUE TITLE
Version 5.7.17-1debian8 not found for 5.7

### ISSUE THREAD

**Issue by luhkevin** [docker-library/mysql#281]
I'm getting this on build for 5.7:
E: Version '5.7.17-1debian8' for 'mysql-server' was not found

**Comment by ltangvald** [comment]
Server versions were just updated for the new release (so it's 5.7.18 now). Update your local branch and it should build.

**Comment by ltangvald** [comment]
Closing this since it's not an issue with the Docker image, but that upstream repo only serves the newest version
