### ISSUE TITLE
Please add environment variables for setting the collation and character set of the default database

### ISSUE THREAD

**Issue by nkovacs** [docker-library/mysql#297]
Gitlab CI cannot pass command line arguments to containers: https://gitlab.com/gitlab-org/gitlab-ce/issues/22787
The only way to configure service containers is to use environment variables: https://docs.gitlab.com/ce/ci/services/mysql.html#use-mysql-with-the-docker-executor

**Comment by yosifkit** [comment]
Same comment as https://github.com/docker-library/mariadb/issues/109#issuecomment-302548750.

**Comment by tianon** [comment]
As noted above (and in the documentation for the image), the appropriate solution here is to simply include `--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci` in your command when running (or in your configuration in a derivative image).
