### ISSUE TITLE
Building source code on amazon ec2 instance taking too much time.

### ISSUE THREAD

**Issue by ahsan-AJ** [docker-library/mysql#298]
I uploaded the Mattermost Source code to an amazon ec2 ubuntu 16.04 instance.
On running the command 'make run' it starts the whole process of installing dependencies etc.
But when it starts webpack watching files, it gets too slow and sometimes it gets hanged up so I have to reboot the server because of this. 
How do I resolve this ?

**Comment by yosifkit** [comment]
wrong repo. :smile:
