### ISSUE TITLE
max_connections & wait-timeout

### ISSUE THREAD

**Issue by BirkhoffLee** [docker-library/mysql#299]
Hey there, how do I increase the max_connections? Sorry if that this question might be dumb, but I couldn't find a page saying how to increase the max_connections of the official mysql container.

By the way I want to modify the default wait-timeout value too, how to do that?

Thanks in advance.

**Comment by ioggstream** [comment]
You should pass the value:

  - via  a custom my.cnf
  - via a parameter at server startup 

See https://hub.docker.com/_/mysql/

If ok, pls close this tkt.

**Comment by BirkhoffLee** [comment]
thanks!

**Comment by jialechan** [comment]
hello @BirkhoffLee , do you found solustion?

**Comment by jialechan** [comment]
OK, like this wokrs for me:
docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag --max_connections=10000
