### ISSUE TITLE
a

### ISSUE THREAD

**Issue by hengshaog** [docker-library/mysql#300]
阿里云服务器，第一次安装过mysql，当时改了账户和密码，就等不进入，后来一会学长让我用docker，我就用docker了，结果docker-compose 每次都报错，1.[ERROR] Could not open /var/lib/log/slow.log for logging (error 13). Turning logging off for the whole duration of the MySQL server process. To turn it on again: fix the cause, shutdown the MySQL server and restart it.
2.Server hostname (bind-address): '*'; port: 3306
3.Can't start server : Bind on unix socket: Permission denied.
4.Do you already have another mysqld server running on socket: /var/run/mysqld/mysqld.sock ?
帮帮忙，都快一周了！

**Comment by hengshaog** [comment]
更换了几次系统，现在是ubuntu 16.04 64位，输入netstat -ntl 3306端口没有被占用。

**Comment by hengshaog** [comment]
docker-compose.yml文件代码：
mysql:
  image: daocloud.io/mysql:5.6.36
  restart: always
  ports:
    - "3306:3306"
  volumes:
    - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    - ./data/database:/usr/data
    - ./data/log:/var/lib/log
    - ./data/mysqld:/var/run/mysqld
  environment:
    - MYSQL_USER=xxx
    - MYSQL_ROOT_PASSWORD=xxx
  privileged: true
  container_name: mysql

**Comment by hengshaog** [comment]
xxx  没有被我删除了 ^_^

**Comment by ltangvald** [comment]
Looks like the permissions set on ./data/log do not allow MySQL to write to it. The mysql user needs read and write access to the logging directory.

**Comment by hengshaog** [comment]
怎么设置log权限

**Comment by hengshaog** [comment]
以成功解决，谢谢！

**Comment by martianyi** [comment]
I think you could close the issue for now because the author has already solved it.
