### ISSUE TITLE
How to re-build image with tmpfs /var/lib/mysql by default

### ISSUE THREAD

**Issue by Webysther** [docker-library/mysql#301]
On docker-compose or even docker run is easy to setup mysql to mount `/var/lib/mysql` on tmpfs (memory), have a simple way to re-build the official image to use tmpfs by default?

**Comment by yosifkit** [comment]
Nope, `tmpfs` mounts can only be defined at run time. :cry:

**Comment by Webysther** [comment]
Well, the last chance is try ask feature for gitlab runner, thanks.

https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1454
