### ISSUE TITLE
Running a shell script on each container startup (mysql:5.6)

### ISSUE THREAD

**Issue by lukpre** [docker-library/mysql#304]
Hey everyone

I do have a question regarding running a shell script on every container startup using the official mysql:5.6 image. Currently i have been using the standard image and entrypoint, that have sourced different databases via /docker-entrypoint-initdb.d this all works great. 

Now i do have a shell script which queries a database to check different values from the db against environment variables on the system. This also works well, when i run the script from within the container (manually) or when i put it into the /docker-entrypoint-initdb.d folder. 

My Problem now is, that /docker-entrypoint-initdb.d doesn't help for me task, because i need to run the script not only on the container creation, rather then on every start of the container. 

Adding it to the official entrypoint script itself didn't help, because i need the databases sourced and mysqld to be running before the script does its job. And since mysqld just gets called from the CMD statement i am a bit stuck.

So i was wondering if anybody here could give me an advice how to properly implement this, or update the entrypoint script correspondingly.

Thank you very much.

**Comment by eugeneievlev** [comment]
Hello!

If I understood right you need run something like SHOW VARIABLES inside MySQL.

You can run container with published port, and work with MySQL directly through this port.

```
docker run -d -p 3306:3306 mysql:tagname
mysql -u<username> -p<userpass> --port=<portnumber> -h<hostname>
```

Hope this will help!

**Comment by ltangvald** [comment]
One suggestion would be to override the entrypoint script with one you make yourself, that wraps the original script:
docker run --entrypoint "/customentrypoint.sh" -v <path>:/customentrypoint.sh ... mysql:5.6
Where custromentrypoint.sh is a wrapper for the normal one that:
* Runs the standard /entrypoint.sh in the background
* Waits for the server to be started and ready
* Runs your script against the server
* Blocks indefinitely as long as the server is up (i.e. does a mysqladmin ping every few seconds)

**Comment by tianon** [comment]
Closing, since I don't think this is something this image reasonably can support out-of-the-box without additional functionality in MySQL itself, and given that there's a reasonable workaround described above for folks who absolutely require this.
