### ISSUE TITLE
Docker 5.8 Image - Mysql doesn't start

### ISSUE THREAD

**Issue by martijnhiemstra** [docker-library/mysql#315]
I run the following command to install the latest mysql server image.

    docker run -d --name=mysql -e MYSQL_ROOT_PASSWORD=myPassword -v /var/mysql/data:/var/lib/mysql mysql/mysql-server:latest

I then see this in the log:
    
    [Entrypoint] MySQL Docker Image 5.7.19-1.1.0
    [Entrypoint] Starting MySQL 5.7.19-1.1.0

And then the image stops running. This is the only logs that I can find. What is going on?

**Comment by ltangvald** [comment]
Hi,

First note is that this is for the upstream image, not the one maintained in docker-library. We made a mistake with it and didn't set the server to log to std-out, so you don't see the server log when running docker logs command (we're working on finding a way to fix this without breaking existing use-cases).

Simplest way to get the log when the container stops like this is to create a log file, ensure it's fully writeable, and add -v <logfilepath>:/var/log/mysqld.log to your run command, and you should see the server log in it.

Most likely the server isn't able to handle the files present in /var/mysql/data. Which MySQL version is it for?

**Comment by martijnhiemstra** [comment]
Anybody reading this, I found out it didn't start because I didn't have enough memory left on my machine. Always check to see if there is enough memory for the mysql container to start. At least 512MB preferably more like 1 GB.

**Comment by tianon** [comment]
Glad you got it solved!
