### ISSUE TITLE
[mysql 5.7] mysqld --initialize-insecure is failed

### ISSUE THREAD

**Issue by applyforprofessor** [docker-library/mysql#317]
The entrypoint.sh file called mysqld with **--initialize-insecure.**
`
echo '[Entrypoint] Initializing database'
"$@" --initialize-insecure
echo '[Entrypoint] Database initialized'
`

The script show '[Entrypoint] Initializing database' and **exit** when i executed `docker run -v /hostdir:/var/lib/mysql mysql:5.7 `. I think the init is failed, but it create _ib_logfile1_ , _ib_logfile101_ and _ibdata1_.(**they don't creaet with mysqld --help, because i remove they before initialized**)

**fllow is output of log**
- docker@myvm-root:/Users/liujialong/docker/image/mysql-docker/5.7$ docker run -v /Users/liujialong/docker/web/mysql/data:/var/lib/mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 mysql:5.7
- [Entrypoint] MySQL Docker Image 5.7.19-1.1.0
- start
- mysqld
- /var/lib/mysql/
- total 110592 -rw-r----- 1 1000 ftp 50331648 Aug 15 19:37 ib_logfile1 -rw-r----- 1 1000 ftp 50331648 Aug 15 19:37 ib_logfile101 -rw-r----- 1 1000 ftp 12582912 Aug 15 19:37 ibdata1
- [Entrypoint] Delete /var/lib/mysql/ib_logfile1
- [Entrypoint] Delete /var/lib/mysql/ib_logfile101
- [Entrypoint] Delete /var/lib/mysql/ibdata1
- total 0
- _**[Entrypoint] Initializing database**_
- docker@myvm-root:/Users/liujialong/docker/image/mysql-docker/5.7$ ls

**Comment by tianon** [comment]
This sounds similar to https://github.com/docker-library/mysql/issues/280, so my comment there applies:

> I think unless we have a reliable way to reproduce this, there's not much more we can do to help -- this does indeed sound like a previous initialization which failed, causing subsequent runs to also fail.  Since we can't reproduce, I'm going to close, but if a reliable reproducer can be found, a new detailed issue would be appreciated!  Thanks!
