### ISSUE TITLE
UTC-8 support

### ISSUE THREAD

**Issue by abdollahpour** [docker-library/mysql#32]
The default encoding for databse is not UTF-8.
I have created new Docker image with /etc/my.cnf :

    [mysqld]
    character-set-server = utf8
    collation-server = utf8_unicode_ci
    skip-character-set-client-handshake

and it works for Chinses. I  think more than half of the world's population need utf-8 support!

**Comment by gaomd** [comment]
We had a PR https://github.com/docker-library/mysql/pull/14 last year, but not merged yet. :(

**Comment by yosifkit** [comment]
Fixed by https://github.com/docker-library/docs/pull/502
