### ISSUE TITLE
ERROR 1045 (28000): Access denied for user 'root'@'cc5c5b533260' (using password: YES)

### ISSUE THREAD

**Issue by jinpan163** [docker-library/mysql#323]
docker run --name my-mysql -p 3306:3306 /app/docker-conf/mysql/conf:/etc/mysql -v /app/docker-conf/mysql/data:/app/mysql/data -e MYSQL_ROOT_PASSWORD=123456 -d mysql

docker exec -it my-mysql sh -c 'exec mysql -h127.0.0.1 -P3306 -uroot -p123456'

ERROR:
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'cc5c5b533260' (using password: YES)

**Comment by haf2000** [comment]
how do you fix it :'( :'(

**Comment by haf2000** [comment]
:( :( :(
