### ISSUE TITLE
Place temporary files in volume

### ISSUE THREAD

**Issue by mmdeas** [docker-library/mysql#328]
AFAICT, in these images, mysql will put temporary files in /tmp (Debian default) and these files can grow to be quite large. However, this folder is not put in a volume. Would it not be better to do so?

I'm happy to make a PR if this makes sense.

**Comment by thaJeztah** [comment]
@tianon @ltangvald wdyt?

**Comment by tianon** [comment]
IMO ideally yes, that would make sense, although using `--tmpfs` in combination with a pre-defined volume was completely broken last time I tested, so `/tmp` as a `VOLUME` by default is going to be somewhat restricting on users of the image. :disappointed:

**Comment by tianon** [comment]
I think at this point, I'm of the opinion that this is worth adding a very short blurb to the documentation, if anything.

**Comment by tianon** [comment]
I've run an instance of `mysql:8` just now and it doesn't seem to actually use `/tmp` for anything anymore:
```console
$ docker diff test
C /run/mysqld
A /run/mysqld/mysqld.pid
A /run/mysqld/mysqld.sock
A /run/mysqld/mysqld.sock.lock
A /run/mysqld/mysqlx.sock
A /run/mysqld/mysqlx.sock.lock
C /tmp
```

**Comment by tianon** [comment]
(Closing given that this appears to be either resolved, or something that's best resolved during deployment, not something we should really update the image for.  We've already got plenty of users salty that we declare a `VOLUME` in the first place. :sweat_smile:)

**Comment by lucastheisen** [comment]
@tianon , i know this is closed, but i cannot understand your statement:

> I've run an instance of mysql:8 just now and it doesn't seem to actually use /tmp for anything anymore

The upstream [documentation](https://dev.mysql.com/doc/refman/8.0/en/temporary-files.html) clearly indicates that `TMPDIR` is used for many things not least of which would be

> ... When sorting (ORDER BY or GROUP BY) ...

This can get really expensive in situations like mine where we run in a rootless container and any filesystem access that is not a bind mount to host folder will go through fuse-overlay and pay a heavy performance cost.

**Comment by tianon** [comment]
So the fix for that would be mounting a volume at runtime on `/tmp`, right? (That's what I meant by "something that's best resolved during deployment" -- we can't really fix that constraint of your environment in the image itself.)
