### ISSUE TITLE
Init script is not run with the environment variables.

### ISSUE THREAD

**Issue by zoonoo** [docker-library/mysql#331]
### Issue
According to the documentation, the initialization script must be run with the appropriate environment variables in the `.env` file, but it does not. 

I have included explicit command to run the script on Dockefile, but error occurs as environmental variable is not used. 

When I run the script from the shell within the container, it works as expected.

### OS Version/build
```
ProductName:	Mac OS X
ProductVersion:	10.12.6
```

### App version
```mysql/mysql-server   8.0```

### Steps to reproduce
`Dockerfile`
```
FROM mysql/mysql-server:8.0
ADD init_db.sh /docker-entrypoint-initdb.d/
RUN printenv
RUN ./docker-entrypoint-initdb.d/init_db.sh
```

`docker-compose.yml`
```
version: '3'

services:
  mysql:
    env_file:
      - db.env
    restart: always
    build:
      context: ./mysql
    volumes:
      - mysql-persistent-volume:/var/lib/mysql
    expose:
      - "3306"

volumes:
  mysql-persistent-volume:
```

`db.env`
```
MYSQL_DB=dbdb
MYSQL_USER=useruser
MYSQL_PASSWORD=password
MYSQL_ROOT_PASSWORD=passw0rd
MYSQL_PORT=3306
```

`init_db.sh`

```
echo '*****************************'
echo $MYSQL_DB
echo $MYSQL_ROOT_PASSWORD
mysql -u root -p$MYSQL_ROOT_PASSWORD -e \
"CREATE DATABASE IF NOT EXISTS $MYSQL_DB;
GRANT ALL PRIVILEGES ON $MYSQL_DB.* TO $MYSQL_USER@'%' IDENTIFIED BY '$MYSQL_PASSWORD' WITH GRANT OPTION;"
echo '*****************************'
```

### OUTPUT
`docker-compose up --build -d --force-recreate django`
```
Building mysql
Step 1/4 : FROM mysql/mysql-server:8.0docker-compose up --build -d --force-recreate django
 ---> ef808dcd341c
Step 2/4 : ADD init_db.sh /docker-entrypoint-initdb.d/
 ---> Using cache
 ---> af35d3264b80
Step 3/4 : RUN printenv
 ---> Running in c79bcf549dda
HOSTNAME=c79bcf549dda
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=1
HOME=/root
_=/usr/bin/printenv
 ---> 1767c227f204
Removing intermediate container c79bcf549dda
Step 4/4 : RUN ./docker-entrypoint-initdb.d/init_db.sh
 ---> Running in a24bef69ceca
*****************************


Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
*****************************

```

**Comment by tianon** [comment]
That final `RUN` line is definitely wrong (`RUN ./docker-entrypoint-initdb.d/init_db.sh`); the whole point of `/docker-entrypoint-initdb.d` is to run scripts during the initialization phase of the container's runtime initialization, which doesn't happen during build time.  If you remove that line from your `Dockerfile`, the container should build and then start properly, and you should see that script run during the first start of the database container.

**Comment by yosifkit** [comment]
Also, as you noticed, `env_file` for a docker-compose setup only apply to the final running container and not during build time.

Since this is not a problem with the image, I'll close the issue.  Also you are using the [`mysql/mysql-server`](https://hub.docker.com/r/mysql/mysql-server/) image, that is not built or managed from this git repository.  The readme on the Docker Hub mentions to make comments on the Docker Hub page or at bugs.mysql.org.  Both images are maintained by MySQL, with this image being a joint effort of the Docker Official Images program and MySQL upstream (the images do maintain similarity to increase ease of use).
