### ISSUE TITLE
Error message is not redirect to stdout/stderr and hence not captured in the Docker, despite what the README says

### ISSUE THREAD

**Issue by sam0737** [docker-library/mysql#334]
Version that used to be working: 5.6.29
Version that I found it is not working: 5.6.38

Repro Step, Problem and Expectation:
===
* Start a 5.6 container
* `docker logs -f <container_id>` should error messages kept spitting by the mysqld
but actually it doesn't as of now.
Actually, even invoking mysqld inside docker - the error message goes to error.log instead of console, so it's a mysqld problem instead of docker.

Technical Description:
====
the default config shipped with mysql seems changed, the `log-error` config is present in `/etc/mysql/mysql.conf.d/mysqld.conf` in v5.6.38, while back in 5.6.29 `/etc/mysql/my.cnf` has `log-error` commented out.

Proposal:
====
Comment out `log-error` in the configuration in entrypoint.sh? Or at least reflect the changes in README, and paste an instruction how we could get the log to docker instead.

It's much more useful to have the log managed by the docker

**Comment by yosifkit** [comment]
Ah, looks like it needs a change similar to https://github.com/docker-library/mysql/pull/199 and https://github.com/docker-library/percona/pull/32.  I made a #336 to ensure that this won't happen again.
