### ISSUE TITLE
Continuously getting a "Access denied for user 'root'@'172.17.0.1' (using password: YES)"

### ISSUE THREAD

**Issue by gnaazr95** [docker-library/mysql#335]
Hi,

I'm continuously getting the error mentioned in the title. I'm currently following this documentation: https://mozilla.github.io/ichnaea/install/deploy.html and am stuck on the step where I have to run this command "docker run -it --rm --env-file env.txt \
    mozilla/location:2.1.0 alembic stamp base"

This is where I am getting the Access denied error. I have both docker and docker-compose set up, when I run docker-compose ps I get the following outout:

Name                Command             State           Ports          
-------------------------------------------------------------------------
name_db_1   docker-entrypoint.sh mysqld   Up      0.0.0.0:3306->3306/tcp

My docker-compose.yml file looks like this:

db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD="password"
    - MYSQL_USER="root"
    - MYSQL_PASSWORD="password"
    - MYSQL_DATABASE="name_db_1"

And this is the env.txt that I am calling on:

DB_HOST=172.17.0.1
DB_USER=root
DB_PASSWORD=password
GEOIP_PATH=/app/geoip/GeoLite2-City.mmdb
REDIS_HOST=localhost

I have set up the privileges on the database also. When I login into the database and run SHOW GRANTS FOR 'root'@'172.17.0.1' I get the following output: 

+----------------------------------------------------------------------+
| Grants for root@172.17.0.1                                           |
+----------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON . TO 'root'@'172.17.0.1' WITH GRANT OPTION |
+----------------------------------------------------------------------+
1 row in set (0.00 sec)

I also get this when I check the grants for 'root'@'%':

+----------------------------------------------------------------------+
| Grants for root@%                                           |
+----------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON . TO 'root'@'%' WITH GRANT OPTION |
+----------------------------------------------------------------------+
1 row in set (0.00 sec)

Any ideas as to what may be going wrong? I've been stuck on this for quite some time...

**Comment by budmc29** [comment]
@Rukeith, @gnaazr95 did you manage to fix the problem?

**Comment by TianShiHeiDe** [comment]
You need to reauthorize root user rights, as the following: 
`grant all privileges *.* on root@'%' identified by 'your password' with grant option;  flush privileges;` 
and then you can access it. Although I don't know why.
