### ISSUE TITLE
docker run not working

### ISSUE THREAD

**Issue by saurcery** [docker-library/mysql#342]
`docker run --name mysql-local -e MYSQL_ROOT_PASSWORD=some-pass -d mysql/mysql-server:tag`
Unable to find image 'mysql/mysql-server:tag' locally
docker: Error response from daemon: manifest for mysql/mysql-server:tag not found.
See 'docker run --help'

**Comment by tianon** [comment]
`:tag` is a placeholder -- you've got to pick a specific version (such as `:5.7`) to run.

Additionally, this repository is for the `mysql` image, not `mysql/mysql-server` (which is in https://github.com/mysql/mysql-docker). :+1:
