### ISSUE TITLE
mysql:latest install mariadb

### ISSUE THREAD

**Issue by OussamaElgoumri** [docker-library/mysql#351]
i run this command

`docker run --name temp-mysql -e MYSQL_ROOT_PASSWORD=pass -d mysql`

but when i access mysql server like this

`mysql -h172.17.0.2 -uroot -ppass`

i get mariadb, **why**?

**Comment by ltangvald** [comment]
Presumably you have MariaDB installed on your host machine (the client is maria, not the server)?

**Comment by ltangvald** [comment]
You can run the client inside the container by running the command:
 docker exec -it temp-mysql mysql -uroot -p

**Comment by OussamaElgoumri** [comment]
@ltangvald thank you, yes i have mariadb client installed on my machine, i used `docker exec -it temp-mysql mysql -uroot -ppass` and i did get into mysql server

**Comment by tianon** [comment]
Glad you got it figured out!
