### ISSUE TITLE
build 5.7 docker image failed 

### ISSUE THREAD

**Issue by kaka89** [docker-library/mysql#363]
Here is my error info:

`
W: Failed to fetch http://security.debian.org/dists/jessie/updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by tianon** [comment]
This has nothing to do with the MySQL image and more to do with Debian's infrastructure, the mirrors your environment happened to pick, or any firewalls/proxies/caches you've got in between your machine and Debian's.
