### ISSUE TITLE
Offer image variants that are based on debian:*-slim

### ISSUE THREAD

**Issue by edmorley** [docker-library/mysql#367]
Hi!

Currently the mysql images use `debian:jessie` as base, which is 50MB. It would be great to add `mysql:*-slim` image variants based on `debian:jessie-slim` (which is only 30MB) or even `debian:jessie-stretch` (which is only 22MB) to reduce the overall image size.

Would a PR for this be accepted? :-)

**Comment by ltangvald** [comment]
Do you have an overview of the differences? We did something similar with the upstream image by going from ol7 to ol7-slim, which e.g. strips out systemd.

**Comment by tianon** [comment]
The main difference between `debian:stretch` and `debian:stretch-slim` is the removal of documentation, man pages, locales, etc.

The full delta can be found by reading https://github.com/debuerreotype/debuerreotype/blob/0.4/scripts/debuerreotype-slimify (which is the script which actually creates the "slim" variants).

**Comment by tianon** [comment]
(I guess https://github.com/debuerreotype/debuerreotype/blob/0.4/scripts/.slimify-excludes is also important :innocent:)
