### ISSUE TITLE
mysql service not coming up for existing data directory mount

### ISSUE THREAD

**Issue by vinaybandakka** [docker-library/mysql#370]
I have data directory with couple of schema and about 25 GB of data. Container starts with volume /var/lib/mysql. When exec to container to see services still mysqld not started by entrypoint script. As you see chown command is still running. Even after 3 hours still chown not finished. It it due to 25GB data mount ? I am using mysql:5.7.20

UID         PID   PPID  C STIME TTY          TIME CMD
root          1      0  0 07:29 ?        00:00:00 /bin/bash /usr/local/bin/docker-entrypoint.sh mysqld
root         18      1  0 07:29 ?        00:00:00 chown -R mysql:mysql /var/lib/mysql/
root         19      0  0 07:31 ?        00:00:00 bash

**Comment by yosifkit** [comment]
That is possible it could take that long on a large database.  I don't have a database of that size to test against.  Any more information about how/where you are running this that would cause limitations on hard drive access?  (`docker version`, `docker info`, `docker run` line or `docker-compose.yaml`, host information).

Since #161 you can also just run a `mysql` container as the owner of the files (so that it can't do the chown):

```console
$ docker run -d --user 1000:1000 -e MYSQL_ROOT_PASSWORD=12345 mysql
```

**Comment by vinaybandakka** [comment]
Thanks yosifkit

I was using the kubernetes to create the mysql container. It look good now after adding below code
```
      securityContext:
        runAsUser: 999
        fsGroup: 999
```
UID for mysql was 999 for me. Thanks again

**Comment by yosifkit** [comment]
Glad that it is working now!

**Comment by User1m** [comment]
@vinaybandakka @yosifkit  when you started the mysql service what was the password you entered to authenticate successfully? I keep getting `su: Authentication failure` when running with `--user 999:999` and `service mysql start` cmd.

Thanks in advance

**Comment by yosifkit** [comment]
@User1m, `service mysql start` shouldn't be used; there is no init system running in the container. Just whatever `entrypoint cmd` is. So using the default `mysql` image and the following is run:

```console
$ docker run -d --user 1000:1000 -e MYSQL_ROOT_PASSWORD=12345 mysql
```

Then during the first few seconds a shell script will be running (`docker-entrypoint.sh`) which will call a few other binaries including running `mysqld` as a background process that is only available via a socket file. After the script finishes creating the user and running any scripts in `/docker-entrypoint-initdb.d/`, it then stops `mysqld` and execs to `mysqld` listening on the network. In the end, this leaves `mysqld` running in the container and nothing else.

**Comment by tianon** [comment]
Either corrupt or your drive is going bad (which is usually when I start to
see IO errors like that).
