### ISSUE TITLE
Create MySQL-Cluster images with ndb_* tooling 

### ISSUE THREAD

**Issue by tiagostutz** [docker-library/mysql#374]
Hi! I've been working with MySQL-Cluster on Docker these days and I missed the ndb_* tooling on the images. I checked the Dockerfile and .sh scripts and noticed that it happens because the image is built with the **minimal** version o mysql-server. Nice approach as the image keeps tiny and our production environment keeps small and with fast boostrap. Turns out that we are developing our MySQL-Cluster platform, so it is required for us to have such set o programs at hand for our day-to-day development and debug. I event [made an docker image](https://hub.docker.com/r/labbsr0x/mysql-cluster-programs/) with this set o tooling (https://github.com/labbsr0x/mysql-cluster-programs), but it wasn't enough because some of the ndb programs must be a Node to the cluster.

So, I'd like to know what do you think about building a NDB Node with the MySQL-Cluster full version and all ndb_* programs? So in a development environment you would have this alternative.

Currently I'm working on a fork to provide this and I'm separating the version folder into two other folders: `minimal` and `full`.

Waiting for some thoughts here to help me with the fork... 

Thanks!
:)

**Comment by tiagostutz** [comment]
Just published an Docker image:

https://hub.docker.com/r/labbsr0x/mysql-cluster-full/

Check the README for some details like the image size

**Comment by ltangvald** [comment]
Hi!

Firstly, this is about upstream's mysql/mysql-cluster image, while this is the repo for the docker-maintained MySQL image, so it would be great if you could report your thoughts to bugs.mysql.com (there's a category for repo packages and docker images).

Secondly, the minimal packages used for the ndb images are quite new, so we basically just added in the utilities we thought most useful, and may have missed some that users want. Most of the size savings come from stripping out debug symbols and not removing individual binaries, so suggestions on adding useful tools are welcome  :)

**Comment by tiagostutz** [comment]
That's awesome!
It looks like that it is not a bug on the MySQL packages but rather a natural improvement of the image as you said. Looking for MySQL Cluster tooling always lead me to https://dev.mysql.com/doc/mysql-cluster-excerpt/5.7/en/mysql-cluster-programs.html so I missed those programs on the image.
After reading your answear I decied to try another approach in which I bring up an Image with the Full MySQL server, copy all the MySQL Programs to a local folder and bring'em to the minimal image. I'll make some tests here and will update here asap.

To be fare what I was looking after was a way to check how the data was distributed in the Shards; I mean, I'd like to know which rows are in each Shard (Nodegroup?) for a given `SELECT`. I don't know already if NDB Programs has such a tool, but I noticed that they are such useful tools and it would be great to have them on hand.

**Comment by tiagostutz** [comment]
Hello, I just build and image that is derived from `mysql/mysql-cluster:7.5` but aggregates de *NDB Cluster Programs*. The image is about 230MB and is available at https://hub.docker.com/r/labbsr0x/mysql-cluster-programs. The github repo: http://github.com/labbsr0x/mysql-cluster-programs

I'd like to know what do you think about building this image with NDB Cluster Programas - if you think this is useful or not - and how would this be organized here, in the MySQL-Cluster branch.

**Comment by tianon** [comment]
Sorry for the delay here.

> Firstly, this is about upstream's mysql/mysql-cluster image, while this is the repo for the docker-maintained MySQL image, so it would be great if you could report your thoughts to bugs.mysql.com (there's a category for repo packages and docker images).

Closing, given that this isn't actually related to the image built via https://github.com/docker-library/mysql (which is https://hub.docker.com/_/mysql/).
