### ISSUE TITLE
Update MySQL 8 image to 8.0.4

### ISSUE THREAD

**Issue by florianreinhart** [docker-library/mysql#375]
MySQL 8.0.4 has been released on January 23: https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-4.html

The MySQL 8 image should be updated.

**Comment by tianon** [comment]
8.0.4 doesn't exist in the official upstream repository this image pulls from:

```console
$ docker pull mysql:8.0
8.0: Pulling from library/mysql
Digest: sha256:21cc59a132e029c688734a66b50bfa7e5b31af9f2f19267f463c247d51c67b5a
Status: Image is up to date for mysql:8.0

$ docker run -it --rm mysql:8.0 bash -c 'apt-get update -qq && apt-cache policy mysql-community-server-core'
mysql-community-server-core:
  Installed: 8.0.3-rc-1debian8
  Candidate: 8.0.3-rc-1debian8
  Version table:
 *** 8.0.3-rc-1debian8 0
        500 http://repo.mysql.com/apt/debian/ jessie/mysql-8.0 amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by tianon** [comment]
@ltangvald it looks like this is because we're currently using `jessie`, but https://repo.mysql.com/apt/debian appears to now include `stretch` -- should we update? :smile:

**Comment by tianon** [comment]
(which means https://dev.mysql.com/doc/refman/8.0/en/linux-installation-debian.html is outdated and should reference "Debian 9" instead of "Debian 8", unless not updating `jessie` was simply an oversight)

**Comment by ltangvald** [comment]
Gah! This was an oversight on my part (I'd forgotten this was based on Jessie).
8.0 support for some of the oldest platforms has been dropped as of 8.0.4, so no 8.0.4 packages will be released for  Debian 8. The image should be updated to use stretch instead.

**Comment by thaJeztah** [comment]
That’s a big change for a patch release?

**Comment by ltangvald** [comment]
Yeah, we would have liked to do it sooner, but it was a case of the older build tools available on Debian 8 (and Ubuntu 14.04) becoming problematic, and looking at their remaining lifetime compared to that of MySQL 8.0

**Comment by tianon** [comment]
8.0's also still pre-release, so IMO there's a load more leeway for this
sort of thing 👍

**Comment by thaJeztah** [comment]
Yes I spotted that later (pre release), was mislead by the 8.0 version and interpreted as “GA”; sorry for the noise :blush:
