### ISSUE TITLE
Skip SSL certificate generation

### ISSUE THREAD

**Issue by fvasco** [docker-library/mysql#379]
I use MySQL for local test, on each startup MySQL take some time to generate a random SSL certificate.

Is it possible to skip the SSL certificate generation?

**Comment by tianon** [comment]
Hmm, this is an interesting point -- we don't have a way to skip the `mysql_ssl_rsa_setup` line easily.

We _do_ check whether the command exists, so you could use that to work around the issue:

```dockerfile
FROM mysql:5.7
RUN rm -v "$(which mysql_ssl_rsa_setup)"
```

Or even hackier:

```console
$ docker run ... -v /dev/null:/usr/bin/mysql_ssl_rsa_setup ... mysql:5.7
```

**Comment by tianon** [comment]
Just to be clear, the section of code under discussion is the following:

https://github.com/docker-library/mysql/blob/30bf2b7ff3010d1f2ee89967dd1303d6a7230c51/5.7/docker-entrypoint.sh#L93-L100

**Comment by fvasco** [comment]
I seen that, your solution should work well, but maintain a MySQL image only for testing purpose is an extra cost.

Is it possible to add an environment variable like `MYSQL_INITDB_SKIP_TZINFO`?

Another interesting solution is the variable `MYSQL_SERVER_KEY_PEM`, so it is possible declare the certificate to use or -optionally- turn off SSL.

**Comment by scara** [comment]
Hello,
my +1 to an _env var_ approach (whatever), keeping care to disable any mounted certificate by explicitly passing `--ssl=0` too (https://github.com/docker-library/mysql/issues/256), just in case.

In the mean time I'm playing w/ the 1st work around described [above](https://github.com/docker-library/mysql/issues/379#issuecomment-368100615).

TIA,
Matteo

**Comment by tianon** [comment]
Took a different approach over in https://github.com/docker-library/mysql/pull/428 -- basically, if SSL is disabled, we skip the certificate generation (which is exactly what 8.0's initialization scripts seem to do as well).

**Comment by tianon** [comment]
If the user supplies their own certificates in the appropriate place, MySQL should transparently pick them up and should not create new ones.  If that behavior is not working, then we should look at fixing that separately.

**Comment by tianon** [comment]
With the solution in #428, I'm considering this closed and fixed.

If you wish to not have the image generate SSL certificates, you have two choices:

1. supply `--ssl=0` (this disables SSL in MySQL entirely, which may or may not be what you want)

2. supply `/var/lib/mysql/server-key.pem` (which will disable the invocation of `mysql_ssl_rsa_setup`, thus not generating new keys)
