### ISSUE TITLE
Docker build encountered an error.

### ISSUE THREAD

**Issue by axzhouzhou** [docker-library/mysql#384]
Docker build encountered an error.
![2018-02-28_104746](https://user-images.githubusercontent.com/36907736/36767373-341f5e3c-1c75-11e8-96df-d4316a21f15f.png)
[error.log](https://github.com/docker-library/mysql/files/1765432/error.log)

**Comment by yosifkit** [comment]
It is known that gpg servers are flaky. Run it a few more times or just pull the image from the Docker Hub.
