### ISSUE TITLE
Mysql starting with --skip-networking

### ISSUE THREAD

**Issue by lakshaykaushik2506** [docker-library/mysql#403]
My mysql docker container starts with:

 root@dd95d0278fc2:/# ps -ef| grep mysql
mysql        1     0  0 13:40 ?        00:00:00 /bin/bash /usr/local/bin/docker-entrypoint.sh mysqld
mysql       87     1  6 13:40 ?        00:00:01 mysqld --skip-networking --socket=/var/run/mysqld/mysqld.sock
mysql      139     1  0 13:40 ?        00:00:00 sleep 100000000000000
root       186   140  0 13:40 pts/0    00:00:00 grep mysql

Hence, it is not able to listen to 3306.

I need to do docker restart mysql to make it working.

After docker restart mysql:

oot@dd95d0278fc2:/# ps -ef| grep mysql
mysql        1     0  1 13:48 ?        00:00:00 mysqld
root        62    57  0 13:48 pts/0    00:00:00 grep mysql

This is posing an issue with ECS as i cannot restart the container after it has started.
Please check.

**Comment by yosifkit** [comment]
That is how it normally starts up though I am not sure where the `sleep 100000000000000` comes from.  Do you have a script in `docker-entrypoint-initdb.d` doing a huge sleep?

The entrypoint script starts mysqld with just the socket so the first initialization can be done (users specified by the [environment variables](https://github.com/docker-library/docs/tree/c5a1ae6208c1bd1b9ae2af2afee8968b662c76a5/mysql#environment-variables) and any scripts in [`/docker-entrypoint-initdb.d`](https://github.com/docker-library/docs/tree/c5a1ae6208c1bd1b9ae2af2afee8968b662c76a5/mysql#initializing-a-fresh-instance)) without external services being able to prematurely think it is ready.  Once initialization is done, the limited mysqld server is shutdown and then one listening on the IP address is started in the foreground with `exec`.

See the [entrypoint script](https://github.com/docker-library/mysql/blob/30bf2b7ff3010d1f2ee89967dd1303d6a7230c51/5.7/docker-entrypoint.sh) for the exact details of how this is accomplished.

**Comment by wglambert** [comment]
Since the proposed resolution was not answered in some time I'm assuming the issue is resolved
