### ISSUE TITLE
Data garbage collection issue when containers deleted using boot2docker?

### ISSUE THREAD

**Issue by psychemedia** [docker-library/mysql#41]
I'm not sure if this is an issue for this container, but if a container switch (*--boot2dockersafe* ?!) can be used to mollify its effect, it might be helpful?!

I've been running several MySQL containers using the recipe described in this [tutorial on how to use mysql with docker](http://www.luiselizondo.net/a-tutorial-on-how-to-use-mysql-with-docker/) and after a while I became unable to run any new containers because of a memory issue when running in boot2docker:

```
bash-3.2$ docker logs mot2013db
Running mysql_install_db ...
2015-01-13 11:22:01 12 [Note] InnoDB: Using atomics to ref count buffer pool pages
2015-01-13 11:22:01 12 [Note] InnoDB: The InnoDB memory heap is disabled
2015-01-13 11:22:01 12 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2015-01-13 11:22:01 12 [Note] InnoDB: Memory barrier is not used
2015-01-13 11:22:01 12 [Note] InnoDB: Compressed tables use zlib 1.2.7
2015-01-13 11:22:01 12 [Note] InnoDB: Using Linux native AIO
2015-01-13 11:22:01 12 [Note] InnoDB: Not using CPU crc32 instructions
2015-01-13 11:22:01 12 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2015-01-13 11:22:01 12 [Note] InnoDB: Completed initialization of buffer pool
2015-01-13 11:22:01 12 [Note] InnoDB: The first specified data file ./ibdata1 did not exist: a new database to be created!
2015-01-13 11:22:01 12 [Note] InnoDB: Setting file ./ibdata1 size to 12 MB
2015-01-13 11:22:01 12 [Note] InnoDB: Database physically writes the file full: wait...
2015-01-13 11:22:01 7fe33467a720 InnoDB: Error: Write to file ./ibdata1 failed at offset 0.
InnoDB: 1048576 bytes should have been written, only -1 were written.
InnoDB: Operating system error number 28.
InnoDB: Check that your OS and file system support files of this size.
InnoDB: Check also that the disk is not full or a disk quota exceeded.
InnoDB: Error number 28 means 'No space left on device'.
...
bash-3.2$boot2docker ssh
docker@boot2docker:~$ sudo su
root@boot2docker:/home/docker# df
Filesystem           1K-blocks      Used Available Use% Mounted on
rootfs                 1851004     87896   1763108   5% /
tmpfs                  1851004     87896   1763108   5% /
tmpfs                  1028332         0   1028332   0% /dev/shm
/dev/sda1             19049892  17272684    786484  96% /mnt/sda1
cgroup                 1028332         0   1028332   0% /sys/fs/cgroup
none                 975922976 225944640 749978336  23% /Users
/dev/sda1             19049892  17272684    786484  96% /mnt/sda1/var/lib/docker/aufs
```

In the *A garbage collection bug in Docker* section of [The Rabbit Hole of Using Docker in Automated Tests](http://gregoryszorc.com/blog/2014/10/16/the-rabbit-hole-of-using-docker-in-automated-tests/) the author comments (**my emphasis**):

>All of a sudden I get an error from Docker that it is out of space. ... At this point, I'm using boot2docker to host Docker. ... I SSH into it, run df, and sure enough, the VM is nearly out of space. But I looked at docker images -a and confirmed there's not enough data to fill the disk. ...  __When running Docker on aufs filesystems (like boot2docker does), Docker does not always remove data volumes containers when deleting a container.__ It turns out that the MySQL containers from the official Docker library were creating a data-only container to hold persistent MySQL data that outlives the container itself. These containers are apparently light magic. They are containers that are attached to other containers, but they don't really show up in the Docker interfaces. __When you delete the host container, these containers are supposed to be garbage collected. Except on aufs, they aren't.__ My MySQL containers were creating 1+ GB InnoDB data files on start and the associated data containers were sitting around after container deletion, effectively leaking 1+ GB every time I created a MySQL container, quickly filling the boot2docker disk. Derp.
>
>I worked around this problem by forking the official MySQL container. I didn't need persistent MySQL data (the containers only need to live for one invocation - for the lifetime of a single test), so I couldn't care less about persisted data volumes. So, I [changed](https://hg.mozilla.org/hgcustom/version-control-tools/rev/68eca557382b) the MySQL container to hold its data locally, not in a data volume container. The solution was simple enough. But it took me a while to identify the problem. Here I was seeing Docker do something extremely stupid. Surely my understanding of Docker was wrong and I was doing something stupid to cause it to leak data. I spent hours digging through the documentation to make sure I was doing things exactly as recommended. It wasn't until I started an Ubuntu VM and tried the same thing there did I realize this looked like a bug in boot2docker. A few Google searches later led me to a comment hiding at the bottom of an existing GitHub issue that pins aufs as the culprit. And here I thought Docker reached 1.0 and wouldn't have bad bugs like this. I certainly wouldn't expect boot2docker to be shipping a VM with a sub-par storage driver (shouldn't it be using devicemapper or btrfs instead). Whatever.*

**Comment by thaJeztah** [comment]
Does this answer your problem? https://github.com/docker-library/mysql/issues/40#issuecomment-69738884

**Comment by psychemedia** [comment]
Yes thanks...
