### ISSUE TITLE
multi-arch mysql image support

### ISSUE THREAD

**Issue by arm64b** [docker-library/mysql#415]
Recently I tried to pull a `mysql` image on linux/arm64 system, but seems there's no `arm64` support in the manifest:
```
# docker pull mysql:latest
latest: Pulling from library/mysql
no matching manifest for linux/arm64 in the manifest list entries
```
So can we add `arm64` support in the official mysql manifest?

**Comment by tianon** [comment]
Duplicate of https://github.com/docker-library/mysql/issues/318.
