### ISSUE TITLE
mysql 8.0.11 docker: mbind: Operation not permitted

### ISSUE THREAD

**Issue by himred** [docker-library/mysql#422]
The docker version of mysql 8.0.11 have the following error at startup

`mbind: Operation not permitted`

I understand this is specific to docker security and seccomp and not directly related to mysql.
But as you propose mysql as a container, this issue impact all docker users.

Is this error a problem, since the database seems to work ?
can we safely  ignore it ?
Or should I add CAP_SYS_NICE capability ?

Thanks.

**Comment by ltangvald** [comment]
Hi,

The error prevents certain NUMA operations from being carried out, for most use cases this won't impact the server (certain workflows get a performance improvement with NUMA).
Note that there is a bug in MySQL here; The server doesn't handle the missing permission, so the error message is directly from the os.

**Comment by mylonasg88** [comment]
So what was the solution on this? I am still getting this error on SequelPRO.

**Comment by tianon** [comment]
Adding "--cap-add sys_nice" should make the warning go away.

**Comment by neohunter** [comment]
@tianon On mysql 8 unknown option '--cap-add'.

**Comment by wglambert** [comment]
`--cap-add` is an option for Docker not a command for the image
https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

**Comment by chiqui3d** [comment]
I continue to have this problem and in addition to excessive memory consumption, I think I'm going to try MariaDB.

**Comment by tianon** [comment]
See also https://github.com/docker-library/mysql/issues/303, which is a very long discussion of this warning (the conclusion of which is that adding the `SYS_NICE` capability to your container is the simplest and cleanest way to adjust your container's seccomp profile to include the necessary rules to allow what MySQL is trying to do).
