### ISSUE TITLE
authentication mysql_native_password

### ISSUE THREAD

**Issue by Flexz9** [docker-library/mysql#424]
Hey,

Since I updated my MySQL docker, Owncloud broke. Anything else using this database is still running as expected.

I'm getting the following error when I try to open Owncloud in my browser:

> Exception occurred while logging exception: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

How can this be fixed? Found an issue that was opened on Owncloud was closed saying nothing is wrong on their and, and this is a MySQL error.

**Comment by ltangvald** [comment]
I assume you updated to 8.0?

MySQL 8.0 changed the default authentication plugin, and older client may not be able to connect.
Adding --default-authentication-plugin=mysql_native_password to the server config should resolve it (but existing users may need to be changed to it as well, if they have been created with caching_sha2_password

**Comment by Flexz9** [comment]
I indeed updated without thinking, because it's just my server at home.
And till now I never had any issues with it. Till now.

I'll try that option tonight, and get back to you if it works or not, any other possible solution is still welcome ofcourse.

**Comment by ltangvald** [comment]
Another note is that you must run mysql_upgrade after upgrading from 5.7 to 8.0 (from any major version to another, really). We're working on making that happen automatically, but need to refactor the scripts to make it robust

**Comment by ltangvald** [comment]
It's a known issue with certain third-party software. Generally the new default would only affect _new_ users, since 8.0 doesn't change any users already created with mysql_native_password. But some client software actually asks the server what the default is, and can't handle an unknown answer (I don't know for sure that's the case with Owncloud, though)

**Comment by Flexz9** [comment]
I'm sad to say nothing really worked.
new install of sql, new install of owncloud, it just didn't like MySQL 8.0.
I ended up running a MySQL docker on 5.7 and moved the database.
