### ISSUE TITLE
Fails to connect to docker container on ubuntu 18.04

### ISSUE THREAD

**Issue by luisgarciaalanis** [docker-library/mysql#426]
REPRO STEPS:

install ubuntu 18.04

From the host:
    docker pull mysql
    docker run --name aaaa -e MYSQL_ROOT_PASSWORD=SomePassword -p 3306:3306 -d mysql 
    mysql --u root -p
    Enter password: 
    ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

Issue:
    Seems to be that the mysql client 5.7.22 that comes with ubuntu can't connect to a mysql 8.0 container.

Expected:
    If it should connect then the expectation is for it to connect.
    if it can't connect then the expectation is to tell you the versions are not compatible instead of an obscure error.

**Comment by mymbrooks** [comment]
same here, I can't connect mysql 8.0 in docker.
I have to go back to mysql 5.7.22.

**Comment by wglambert** [comment]
MySQL 8 changed their password authentication method. You're looking for the mysql_native_password plugin
https://dev.mysql.com/doc/refman/8.0/en/native-pluggable-authentication.html

So you'll want to connect with `mysql --default-auth=mysql_native_password -p`

https://github.com/docker-library/mysql/issues/424#issuecomment-387403312
