### ISSUE TITLE
GnuPG intermittently fails to fetch pubkey from keyserver

### ISSUE THREAD

**Issue by qrkourier** [docker-library/mysql#431]
When the hard-coded keyserver in docker-entrypoint.sh is not available or too slow then GnuPG will fail to fetch the needed pubkey and build will fail with "cannot assign address". 

[Here's a workaround](https://github.com/docker-library/mysql/pull/429/files) to try several keyservers in turn that I found in another repo with the same issue.

**Comment by yosifkit** [comment]
My current opinion of this is expressed in https://github.com/docker-library/cassandra/pull/131#issuecomment-358444537.

Related issues: docker-library/tomcat#87, docker-library/tomcat#108, https://github.com/docker-library/mysql/issues/263#issuecomment-354025886,  https://github.com/docker-library/httpd/issues/66#issuecomment-316832441, docker-library/php#586, docker-library/postgres#443, docker-library/mariadb#108, docker-library/php#630, docker-library/python#280, docker-library/official-images#4252

**Comment by MichaelBrenden** [comment]
gnupg2 works better than gnupg
