### ISSUE TITLE
Unable to connect to MySQL Database from MySQL Workbench

### ISSUE THREAD

**Issue by MBurchard** [docker-library/mysql#444]
I recently updated my MySQL Docker image and it "jumped" from version 5 to version 8. Currently I have version 8.0.11.
I also installed MySQL Workbench 8 as Release Candiate, so I can connect to the new version at all.

Now it looks as if the connection is basically established. But I get this error message.

![grafik](https://user-images.githubusercontent.com/4256302/41607240-dd20eb96-73e5-11e8-9692-5863a63d186e.png)

I connect through an SSH tunnel and try to log in with the root user.

I already read that this user "mysql.infoschema" was deleted during the migration and this was probably not such a good idea.
Now I have tried to create the user again.
I had to use the Docker Shell to get into the MySQL container and then I failed.

mysql> create user 'mysql.infoschema'@'%';
ERROR 1146 (42S02): Table 'mysql.role_edges' doesn't exist

What can I do to get full access to my MySQL database again?

**Comment by wglambert** [comment]
With the error of the definer user not existing https://github.com/docker-library/mysql/issues/380#issuecomment-384135863
> . . . the solution, of course, is just to run mysql_upgrade

If that doesn't solve it could you provide the necessary commands and relevant contextual information for reproducing the issue

**Comment by MBurchard** [comment]
You are absolutely right... my fault, sorry...
