### ISSUE TITLE
MySQL Server 8.0, Release Candidate

### ISSUE THREAD

**Issue by diego-vieira** [docker-library/mysql#445]
The documentation at https://github.com/mysql/mysql-docker/tree/mysql-cluster states `MySQL Server 8.0, Release Candidate` is that still the case even though the website says GA?

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-11.html

Thanks

**Comment by TimWolla** [comment]
The README.md in the linked repository is 8 months old as indicated in the commit: https://github.com/mysql/mysql-docker/blob/mysql-cluster/README.md

Please note that link is from a different repository than the one you filed the issue for.

**Comment by diego-vieira** [comment]
@TimWolla my reason to raise this issue for the exact reason that the README is not up to date.
The second reason I filled in the "wrong" repository is that there is no way to post an issue on that repository since it's a fork of this repository.

Anyway, I will leave that to however cares.

Thanks
