### ISSUE TITLE
MySQL 5.6.22 image is broken

### ISSUE THREAD

**Issue by thaJeztah** [docker-library/mysql#45]
There seems to bee an issue with the MySQL 5.6.22 image on the registry.

This came to light while discussing another issue; https://github.com/docker-library/mysql/issues/44#issuecomment-71908696

To reproduce:
```bash
docker run -d -h mysql --name mysqltmount_all_dir -v $PWD/mysql/var/lib/mysql:/var/lib/mysql -v $PWD/mysql/etc/mysql:/etc/mysql -e MYSQL_ROOT_PASSWORD=test -e MYSQL_USER=mmx -e MYSQL_PASSWORD=mmx -e MYSQL_DATABASE=mmx mysql:5.6.22
```

And check the logs;
```bash
docker logs mysqltmount_all_dir

....

2015-01-28 21:08:53 1 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!

2015-01-28 21:08:53 1 [ERROR] Aborting

2015-01-28 21:08:53 1 [Note] Binlog end
2015-01-28 21:08:53 1 [Note] mysqld: Shutdown complete
```

I've pasted the full logs here:
https://gist.github.com/thaJeztah/62dc9d655e8e836414f7

**Comment by thaJeztah** [comment]
Also, `MySQL:5.6` seems to be an alias for `MySQL:5.6.21`, not `MySQL:5.6.22`

**Comment by yosifkit** [comment]
It complains about root because you bind mount over the config: https://github.com/docker-library/mysql/commit/12ffb2f321313dce32d24bff53a317f8f6b2e9c5#commitcomment-9444466

**Comment by thaJeztah** [comment]
Ah, you could be right. Was assisting someone with his use-case and didn't notice he was bind-mounting the config-dir as well.

Yes, simplifying to this works:

    docker run -d -h mysql --name mysqltmount_all_dir -v $PWD/mysql/var/lib/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=test -e MYSQL_USER=mmx -e MYSQL_PASSWORD=mmx -e MYSQL_DATABASE=mmx mysql:5.6.22

I'll close. Sorry for the mis-report
