### ISSUE TITLE
build mysql image by Dockerfile failed

### ISSUE THREAD

**Issue by lunbin** [docker-library/mysql#451]
when I build mysql image by Dockerfile(not using the latest Dockerfile). The following error occurred: 
E: Version '5.7.18-1debian8' for 'mysql-server' was not found. But using latest Dockerfile to build image ,do not occured this error

what should i do in the face of this problem?
thank you!

**Comment by ltangvald** [comment]
The repo at repo.mysql.com only offers the latest minor version, and it's recommended to use that. If you need to use a specific version you'll need to change the Dockerfile to use manually downloaded .deb files instead.
