### ISSUE TITLE
Cannot upgrade with apt-get in mysql:5.7 container

### ISSUE THREAD

**Issue by NateV** [docker-library/mysql#463]
# Problem:

I'm unable to upgrade with apt in a docker container based on mysql:5.7.

# Expected behavior:

This dockerfile should build

```
FROM mysql:5.7

RUN apt-get update && apt-get upgrade -y
```

# Actual behavior

`docker build .` fails with an error that includes the following

```
dpkg: error processing archive /var/cache/apt/archives/mysql-community-server_5.7.23-1debian9_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
```

If I try to use the docker container mysql:57, and run  `RUN apt-get update && apt-get upgrade -y`, the command fails with a dpkg error. 

If I run, from inside the container,  `apt-get upgrade`, I see

```
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 mysql-community-server : Depends: mysql-client (= 5.7.22-1debian9) but 5.7.23-1debian9 is installed
 mysql-server : Depends: mysql-community-server (= 5.7.23-1debian9) but 5.7.22-1debian9 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

Perhaps mysql-community-server depends on mysql-client 5.7.22, but mysql-server depends on mysql-community-server 5.7.23?

**Comment by wglambert** [comment]
The containers are designed to be immutable. See the docs for information https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get
>Avoid RUN apt-get upgrade and dist-upgrade, as many of the “essential” packages from the parent images cannot upgrade inside an unprivileged container.
