### ISSUE TITLE
Container does not catch signals and exit (Ctrl+C)

### ISSUE THREAD

**Issue by msumme** [docker-library/mysql#47]
If I start a database like this:

```
/usr/bin/docker run --name database -e MYSQL_ROOT_PASSWORD=whatever mysql:5.6
```
The container does not respond to Ctrl+c like most containers do - it simply will not exit until I manually kill the process from a different terminal.

Even if I add "-it" options, it is still the same.

This is on docker 1.4.1.

Other containers exhibit the expected behavior on the same docker version.

**Comment by yosifkit** [comment]
This is a limitation of docker and pid 1.  If the process doesn't implement a signal handler then the SIGINT is just lost because normally you would not want to kill your pid 1 which is your init system.  Redis has the same problem.

**Comment by msumme** [comment]
I figured that out and found a workaround.

It is possible to run mysqld in a wrapper that properly handles signals so that the instance can be monitored externally and shut down with normal signal handling.  

This can be accomplished by changing the last line from `exec "$@` to:
```
$@ &
PID=`jobs -p`

trap "kill -SIGQUIT $PID" INT
wait
```

I'm sure something more sophisticated could be accomplished, but it would be nice to be able to monitor your msyql container w/ systemd and other init systems.

**Comment by md5** [comment]
Systemd and other init systems don't use SIGINT, they use SIGTERM, so this
isn't a problem in those situations.​

**Comment by msumme** [comment]
Okay - well, I'll have to check again - but I couldn't seem to get it to work with systemd until I changed the script.

**Comment by vaab** [comment]
Here's how to use @msumme fix, without changing the entrypoint. This will work with a pristine image. Please, don't judge me.

```
docker run -ti \
    --entrypoint /bin/bash mysql -c '                                                                                          
    exec() {                                                                                                                     
        "$@" &                                                                                                                   
        pid="$!"                                                                                                                 
        trap "kill -SIGQUIT $pid" INT                                                                                            
        wait                                                                                                                     
    }                                                                                                                            
    export -f exec                                                                                                               
    /entrypoint.sh '

**Comment by jeremyVignelles** [comment]
Hi,
Same issue here, I was looking for a clean solution when I came across this thread.

I tried @vaab solution but I couldn't make it work...
I've ended up doing my own Dockerfile, like this one:

```
FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD password
ENV MYSQL_DATABASE databasename
ENV MYSQL_USER user
ENV MYSQL_PASSWORD password

# Entrypoint overload to catch the ctrl+c and stop signals
ENTRYPOINT ["/bin/bash", "/run.sh"]
CMD ["mysqld"]

COPY run.sh /run.sh
```

and the run.sh:
``` shell
#!/bin/bash
# A wrapper around /entrypoint.sh to trap the SIGINT signal (Ctrl+C) and forwards it to the mysql daemon
# In other words : traps SIGINT and SIGTERM signals and forwards them to the child process as SIGTERM signals

asyncRun() {
    "$@" &
    pid="$!"
    trap "echo 'Stopping PID $pid'; kill -SIGTERM $pid" SIGINT SIGTERM

    # A signal emitted while waiting will make the wait command return code > 128
    # Let's wrap it in a loop that doesn't end before the process is indeed stopped
    while kill -0 $pid > /dev/null 2>&1; do
        wait
    done
}
asyncRun /entrypoint.sh $@
```
A few things to note (from what I've tested):
- When a bash script launches a command synchronously, it does not receive signals.
- When a bash script launches a command asynchronously (with `&`) and calls `wait`, it will trigger the actions registered with the trap command. However, the wait command is aborted and returns with an error code > 128 (source : http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_12_02.html ), hence the need to wrap it in a loop.
- I first tried to replace the exec function as @vaab suggested, but then, the PID relative to the `exec` function would have received the `SIGINT` only when doing a `ctrl+c`, not when calling `docker stop`. (maybe I did something wrong in my tests though, can't guarantee that).
- This method catches the `SIGINT` and `SIGTERM` signals emitted by either `ctrl+c` and `docker stop`, and calls `kill` with `SIGTERM` to the PID launched previously. From the few tests that I made, this seems to work as expected, because, as @yosifkit said, only the PID 1 (here, the `run.sh` script) would get notified. The difference here is that both `SIGINT` and `SIGTERM` are transmitted to `entrypoint.sh` as `SIGTERM` signals.

Could this logic be implemented in the `entrypoint.sh` script?

**Comment by ryanmjt** [comment]
Yeah why is this closed? I can't use control-c to kill mysql on the current :latest image. Doesn't matter if I run with `-t` or `-i` or none.

**Comment by jeremyVignelles** [comment]
Official answer is : mysqld isn't killed by ctrl+C by design and the official docker image should not have a different behavior. (see above topics and pull request)

If you want to have this behavior implemented, wrap this image into your own using the instructions i gave above.

Also note that `docker stop` exits the container correctly. In other word, you can run it in the background and stop it manually.

**Comment by delitescere** [comment]
If you are running in non-detached mode, you may send a `SIGQUIT` signal to the process. This is typically mapped to your `Control-\` key combination.

**Comment by joaocc** [comment]
Will "docker stop" make mysql flush everything before terminating?

**Comment by yosifkit** [comment]
@joaocc, yes and no. Yes, mysql will receive the `SIGTERM` and begin cleaning up to exit. But if it takes too long (10 seconds by default) it will get a `SIGKILL` from [docker stop](https://docs.docker.com/engine/reference/commandline/stop/).  So if your database needs longer to clean up, either increase the timeout to `docker stop` or use `docker kill -s TERM` and do your own timeout process.

**Comment by joaocc** [comment]
Great. Thx

**Comment by joaocc** [comment]
Thx for the clarification. For me, the important thing is that the signals sent by docker stop and the ones that MySQL is listening for and acting on are aligned. The rest will always have to be tuned to a particular system. Thx

**Comment by klarkc** [comment]
> Hi,
> Same issue here, I was looking for a clean solution when I came across this thread.
> 
> I tried @vaab solution but I couldn't make it work...
> I've ended up doing my own Dockerfile, like this one:
> 
> ```
> FROM mysql:latest
> 
> ENV MYSQL_ROOT_PASSWORD password
> ENV MYSQL_DATABASE databasename
> ENV MYSQL_USER user
> ENV MYSQL_PASSWORD password
> 
> # Entrypoint overload to catch the ctrl+c and stop signals
> ENTRYPOINT ["/bin/bash", "/run.sh"]
> CMD ["mysqld"]
> 
> COPY run.sh /run.sh
> ```
> 
> and the run.sh:
> 
> ```shell
> #!/bin/bash
> # A wrapper around /entrypoint.sh to trap the SIGINT signal (Ctrl+C) and forwards it to the mysql daemon
> # In other words : traps SIGINT and SIGTERM signals and forwards them to the child process as SIGTERM signals
> 
> asyncRun() {
>     "$@" &
>     pid="$!"
>     trap "echo 'Stopping PID $pid'; kill -SIGTERM $pid" SIGINT SIGTERM
> 
>     # A signal emitted while waiting will make the wait command return code > 128
>     # Let's wrap it in a loop that doesn't end before the process is indeed stopped
>     while kill -0 $pid > /dev/null 2>&1; do
>         wait
>     done
> }
> asyncRun /entrypoint.sh $@
> ```
> 
> A few things to note (from what I've tested):
> 
> * When a bash script launches a command synchronously, it does not receive signals.
> * When a bash script launches a command asynchronously (with `&`) and calls `wait`, it will trigger the actions registered with the trap command. However, the wait command is aborted and returns with an error code > 128 (source : http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_12_02.html ), hence the need to wrap it in a loop.
> * I first tried to replace the exec function as @vaab suggested, but then, the PID relative to the `exec` function would have received the `SIGINT` only when doing a `ctrl+c`, not when calling `docker stop`. (maybe I did something wrong in my tests though, can't guarantee that).
> * This method catches the `SIGINT` and `SIGTERM` signals emitted by either `ctrl+c` and `docker stop`, and calls `kill` with `SIGTERM` to the PID launched previously. From the few tests that I made, this seems to work as expected, because, as @yosifkit said, only the PID 1 (here, the `run.sh` script) would get notified. The difference here is that both `SIGINT` and `SIGTERM` are transmitted to `entrypoint.sh` as `SIGTERM` signals.
> 
> Could this logic be implemented in the `entrypoint.sh` script?

I've just created [this image](https://hub.docker.com/repository/docker/klarkc/mysql-foreground) with this workaround.

**Comment by theothermattm** [comment]
I've put out a PR with the information from @jeremyVignelles workaround in it.  Suggestions are welcome.  We were hit by this issue hard! https://github.com/docker-library/docs/pull/1789
