### ISSUE TITLE
Running two MySQL servers that use the same data directory

### ISSUE THREAD

**Issue by MikiTesi** [docker-library/mysql#470]
## The situation
I have a persistent volume (provided by Gluster). 
I have two MySQL containers, deployed on two different machines. 
Both MySQL containers access the same data directory, which is stored on said persistent volume.

I'm aware that it is strongly discouraged to run two MySQL servers using the same data directory, but it's not an impossible thing to do, as long as one takes the right precautions. I have followed the steps suggested by the official documentation ( [https://dev.mysql.com/doc/refman/5.6/en/multiple-data-directories.html](url) ) in the paragraph named **Warning**. To sum it up:

- I'm using MySQL 5.6.
- I'm using MyISAM as my default engine.
- I specified log file names that are unique to each server.
- One server is going to be *read-write*, while the other server is going to be *read-only*.

So, I set everything up, I imported a test database and everything worked flawlessly. Both servers could read data from the same data directory.

## The problem
Now comes the problem. As soon as one server performs a write (by inserting a row into a table), the other server marks the table as corrupted for itself.
After looking into the problem for a while, I found out why this happened. Basically each server holds its own metadata describing each table. So, as soon as the first server updated a table, it also updated its own metadata, but it didn't update the metadata of the second server. As the second server checked the table, it noticed a mismatch between the current number of rows in the table  and the number of rows it had previously saved in its metadata, therefore it marked the table as corrupted. 
After some research, it turns out that the metadata is saved inside a default database named *information_schema*. At first, I thought of making the two server share the same *information_schema*, but this was nowhere to be found. As I later discovered, it's saved inside the memory of the program and there's no way you can manually update or access it.

## The questions
1. Since the documentation tells you exactly what precautions to take, I was expecting this to actually work...or else, what's the point of that guide?
2. Most importantly, do you know how to make this work? Or a workaround, maybe?
3. Otherwise, do you know of any other DBMSs that allow you to obtain this result (that is, running two servers that use the same data directory)?
 
All suggestions are welcome, thanks everyone for the help.

On a last note, I'm aware the problem is not directly related to MySQL being run in docker, I hope it's fine I posted this question here anyway.

**Comment by MikiTesi** [comment]
@yosifkit  It seems like you were right, as no one has answered yet. This was probably not the right place to ask such a question, therefore I'll ask somewhere else, maybe on dba-stackexchange. I hope that's a more appropriate site. Let me know if you have any other suggestions as to where I should ask, though. Thank you.

**Comment by yosifkit** [comment]
I'll close the issue since it is not directly related to the image.
