### ISSUE TITLE
RFE: omit timestamps from mysql logs

### ISSUE THREAD

**Issue by glensc** [docker-library/mysql#499]
docker supports prefixing logs with timestamps. mysql adds timestamps themselves to most of the messages.

i propose to stop mysql prefixing, let only docker do the prefixing.

benefits:
- no duplicate timestamping
- ability to see logs without timestamps
- all entries are either timestamped or not
- saving small amount cpu jiffies ;)

example:
```
# docker-compose logs --tail=10 -t
Attaching to quizmysql_mysql_1
mysql_1  | 2018-10-01T12:30:05.386024254Z 2018-10-01T12:30:05.385716Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1  | 2018-10-01T12:30:05.386344940Z 2018-10-01T12:30:05.386197Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
mysql_1  | 2018-10-01T12:30:05.386384593Z 2018-10-01T12:30:05.386261Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1  | 2018-10-01T12:30:05.386744043Z 2018-10-01T12:30:05.386657Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
mysql_1  | 2018-10-01T12:30:05.399196078Z 2018-10-01T12:30:05.398958Z 0 [Note] InnoDB: Buffer pool(s) load completed at 181001 12:30:05
mysql_1  | 2018-10-01T12:30:05.471855918Z 2018-10-01T12:30:05.471540Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
mysql_1  | 2018-10-01T12:30:05.471972148Z 2018-10-01T12:30:05.471707Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1  | 2018-10-01T12:30:05.659986561Z 2018-10-01T12:30:05.659728Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1  | 2018-10-01T12:30:05.660508342Z 2018-10-01T12:30:05.660348Z 0 [Note] mysqld: ready for connections.
mysql_1  | 2018-10-01T12:30:05.660539323Z Version: '5.7.23-23'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Percona Server (GPL), Release '23', Revision '500fcf5'
```

affected images:
- mysql:*
- percona:*

**Comment by yosifkit** [comment]
As far as I can tell, there is not a way to tell MySQL to log without a timestamp.

https://dev.mysql.com/doc/refman/8.0/en/server-logs.html
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_log_timestamps

**Comment by glensc** [comment]
indeed, seems the same variable affects other log files: slow log, query log. disabling timestamps there is unlikely to be wanted (those logs not streamed to docker io either).

**Comment by tianon** [comment]
@ltangvald this request is probably something you'll want to consider while adding even more timestamps to output in #471 :smile:

(I'm closing this though, since there's really nothing to change in the image here -- this is more of a feature request for MySQL upstream from what I can see.)
