### ISSUE TITLE
Indicator that Database Imports are Still Running

### ISSUE THREAD

**Issue by jksimoniii** [docker-library/mysql#507]
When setting up a MySQL container in a docker composition, it is easy for the MySQL container's logs to get lost in the noise of the others.  In some cases, it may be important to know that the MySQL container is actively running an import through it's entrypoint script.  I would like to see output from the MySQL container to inform me that database imports are still running.

**Comment by JamesonNetworks** [comment]
Opened a PR that does something along these lines.

**Comment by tianon** [comment]
Sorry for the delay. If you need additional output in your `initdb` scripts, that's something you should arrange for by using a `.sh` drop-in instead of a raw `.sql` file.
