### ISSUE TITLE
Push image for 8.0.13 to docker hub

### ISSUE THREAD

**Issue by slayer** [docker-library/mysql#510]
Hi

docker hub still has 8.0.12 as latest image: https://hub.docker.com/r/_/mysql/ 
Please push (or call build hook) 8.0.13 image to registry. 

Thanks

**Comment by wglambert** [comment]
https://github.com/docker-library/mysql#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

It's being pushed now https://github.com/docker-library/official-images/pull/4985
