### ISSUE TITLE
why run my local gpg is fails ?

### ISSUE THREAD

**Issue by ZRothschild** [docker-library/mysql#529]
Gpg: keyserver receive failed: No keyserver available or Gpg: keyserver receive failed: connot assign rquested address  but the dockerfile can run the labs.play-with-docker.com

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035

> TLDR; GPG servers are extremely flaky and we have yet to solve it reliably.
> 
> For automated testing, we usually just set our travis builds to repeat multiple times (like [php](https://github.com/docker-library/php/blob/c4f059d09d7eefcb73304d198faa7674610ed810/.travis.yml#L47)) since it is usually just gpg failures.
> 
> For builds on my local machine (which is were most build tests for official image PRs are done) I run an nginx reverse proxy server to man-in-the-middle apt, apk, and gpg requests and cache them.
> 
> For the servers that build and push the official images we take an eventually consistent approach and mark builds as "unstable" if one or more tags fail to build and just allow the build to run later. They also have multiple retries for each tag.
> 
> Related issues: https://github.com/docker-library/cassandra/pull/131#issuecomment-358444537, https://github.com/docker-library/tomcat/issues/87, https://github.com/docker-library/tomcat/pull/108, https://github.com/docker-library/mysql/issues/263#issuecomment-354025886,  https://github.com/docker-library/httpd/issues/66#issuecomment-316832441, https://github.com/docker-library/php/issues/586, https://github.com/docker-library/wordpress/pull/291
