### ISSUE TITLE
gpg: keyserver receive failed: Cannot assign requested address

### ISSUE THREAD

**Issue by katomel4** [docker-library/mysql#530]
gpg: keyserver receive failed: Cannot assign requested address
Only on Azure Devops build

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035

> TLDR; GPG servers are extremely flaky and we have yet to solve it reliably.
> 
> For automated testing, we usually just set our travis builds to repeat multiple times (like [php](https://github.com/docker-library/php/blob/c4f059d09d7eefcb73304d198faa7674610ed810/.travis.yml#L47)) since it is usually just gpg failures.
> 
> For builds on my local machine (which is were most build tests for official image PRs are done) I run an nginx reverse proxy server to man-in-the-middle apt, apk, and gpg requests and cache them.
> 
> For the servers that build and push the official images we take an eventually consistent approach and mark builds as "unstable" if one or more tags fail to build and just allow the build to run later. They also have multiple retries for each tag.
> 
> Related issues: https://github.com/docker-library/cassandra/pull/131#issuecomment-358444537, https://github.com/docker-library/tomcat/issues/87, https://github.com/docker-library/tomcat/pull/108, https://github.com/docker-library/mysql/issues/263#issuecomment-354025886,  https://github.com/docker-library/httpd/issues/66#issuecomment-316832441, https://github.com/docker-library/php/issues/586, https://github.com/docker-library/wordpress/pull/291

**Comment by esbiorn** [comment]
We faced this issue in our own docker builds and found another solution. 

Use the keyserver to add the key once, then use `apt-key export` to export the key to a file. Add that file to your code repo, copy it into docker, and then use `apt-key add` to add it. No need to download keys anymore! 

This way the builds will work well until the key is changed for some reason, which usually doesn't happen too often I hope.
