### ISSUE TITLE
After running mysql_tzinfo_to_sql, move . cnf

### ISSUE THREAD

**Issue by devnokiyo** [docker-library/mysql#531]
There is a request in docker-entrypoint.sh.
Currently it works as follows.
* Dockerfile
    ```Dockerfile
    COPY my.cnf /etc/mysql/conf.d
    ```
* my.cnf
    ```cnf
    default-time-zone=UTC
    ```

The following error occurs at initial startup.
```
[ERROR] Fatal error: Illegal or unknown default time zone 'UTC'
[ERROR] Fatal error: Failed to initialize ACL/grant/time zones structures or failed to remove temporary table files.
[ERROR] Aborting
```

It is due to specifying the time zone before tzinfo_to_sql is executed.
Is it possible to add .cnf to the target of the initialization file?

I am using it corrected.
https://github.com/devnokiyo/docker-library-mysql-lab/commit/2214cd82cb1109484a8f92e97921207191d92f2d#diff-17ed820d5141a5e8565a0431e5385dae

This fix has the problem that owner of cnf becomes mysql. So we decided to request the official repository for issues without PR.

Please consider.

**Comment by tianon** [comment]
The main issue I see with the approach in https://github.com/devnokiyo/docker-library-mysql-lab/commit/2214cd82cb1109484a8f92e97921207191d92f2d#diff-17ed820d5141a5e8565a0431e5385dae is that it won't persist if the container restarts or is rescheduled -- it'll only happen on the first start and later invocations will see that the database already exists and won't run anything there.

The solution presented there would be implemented more simply via a shell script in `/docker-entrypoint-initdb.d` (and then wouldn't require changes to this repository) if you're still OK with the caveat I've pointed out.

This is kind of a tricky one that I don't have a good solution for. :confused: :disappointed:

**Comment by devnokiyo** [comment]
Thank you for confirmation.

I thought it would be nice if I could set default-time-zone to UTC in the initial construction.
Therefore, I wanted to reflect the .cnf file in `docker-entrypoint-initdb.d`.
Persistence of cnf file is done by docker-compose, so I do not think it is a problem.

The shell script executed in docker-entrypoint-initdb.d operates under the authority of the mysql user. The file could not be moved to a path that requires root privileges.

```sh
#!/bin/bash

mv /docker-entrypoint-initdb.d/my.cnf /etc/mysql/conf.d
```

```
mv: cannot move '/docker-entrypoint-initdb.d/my.cnf' to '/etc/mysql/conf.d/my.cnf': Permission denied
```
I am modifying `docker-entrypoint.sh` to avoid it temporarily.

It seems to be a tricky fix, so we will use the provisional `docker-entrypoint.sh`, or modify the cnf file and restart MySQL as usual.
