### ISSUE TITLE
Fails to build: Version '5.7.24-1debian9' for 'mysql-server' was not found

### ISSUE THREAD

**Issue by JJonesAtAvaya** [docker-library/mysql#533]
E: Version '5.7.24-1debian9' for 'mysql-server' was not found

Is there a stable version of Debian I can use instead?

$ head Dockerfile
FROM debian:stretch-slim
....

**Comment by duyanghao** [comment]
@JJonesAtAvaya How did you resolve the issue?

**Comment by JJonesAtAvaya** [comment]
I just went with a straight 
FROM mysql:5.7
instead of hand-rolling it

**Comment by duyanghao** [comment]
@JJonesAtAvaya Thanks for your reply.
