### ISSUE TITLE
get error on building mysql image

### ISSUE THREAD

**Issue by KingWu** [docker-library/mysql#537]
Docker Engine : 18.09.01
Mac: 10.13.6

Get this error
gpg: keyserver receive failed: Cannot assign requested address

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035
>TLDR; GPG servers are extremely flaky . . .

This is what we do for GPG issues https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749
