### ISSUE TITLE
Option to turn off name resolution

### ISSUE THREAD

**Issue by mraxus** [docker-library/mysql#54]
Hi,

I would like to submit this feature request to add an option of disabling name resolution. (skip_name_resolve ON/OFF)

This would be great. Thanks!

//Marcus

**Comment by yosifkit** [comment]
Tis already there :wink:.  Any mysqld flags can just be passed in.
`docker run -it --rm -e MYSQL_ROOT_PASSWORD=123456 mysql --skip-name-resolve`

**Comment by mraxus** [comment]
Awesome!
Then I rest my case =)
