### ISSUE TITLE
Segmentation fault when try to prepare kolide/fleet db.

### ISSUE THREAD

**Issue by kolisayeed** [docker-library/mysql#542]
cd /work/src/github.com/kolide/fleet

sudo docker-compose up

mysql_test_1  | 2019-02-25T07:24:23.397702Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_test_1  | 2019-02-25T07:24:23.407420Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_test_1  | 2019-02-25T07:24:23.407761Z 0 [Note] mysqld: ready for connections.
mysql_test_1  | Version: '5.7.25-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
mailhog_1     | [APIv1] KEEPALIVE /api/v1/events
mailhog_1     | [APIv1] KEEPALIVE /api/v1/events
mailhog_1     | [APIv1] KEEPALIVE /api/v1/events
mailhog_1     | [APIv1] KEEPALIVE /api/v1/events
mailhog_1     | [APIv1] KEEPALIVE /api/v1/events

Then I run 👍 
./build/fleet prepare db
Segmentation fault

what is my wrong?

**Comment by tianon** [comment]
This looks like it's filed in the wrong repository?

**Comment by wglambert** [comment]
Yeah you're wanting https://github.com/kolide/fleet

Looks like their [Dockerfile](https://github.com/kolide/fleet/blob/master/Dockerfile) isn't derived from ours anyway so there's nothing we could help you with
```Dockerfile
FROM alpine
MAINTAINER Kolide Developers <engineering@kolide.co>

RUN apk --update add ca-certificates

COPY ./build/binary-bundle/linux/fleet ./build/binary-bundle/linux/fleetctl /usr/bin/

CMD ["fleet", "serve"]
```
