### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tianon** [docker-library/mysql#55]
In 7c7b50802e867b593bc2ee6290fe5a0afba1e179, we added GPL-2+ with the comment of "Upstream's license is complicated, but this gets us decent compatibility."

I don't think this is anywhere near a closed debate, and I'd really love to get some upstream suggestion on where we should go with this (even if just to remove the `+` and be strict GPL-2). :heart:

cc @ltangvald

**Comment by tianon** [comment]
As a further note, GPL-2+ wasn't completely out of the blue -- http://metadata.ftp-master.debian.org/changelogs//main/m/mysql-5.5/mysql-5.5_5.5.41-0+wheezy1_copyright (`debian/` in the Debian package is GPL-2+, and Debian folk are traditionally careful about choosing a license for `debian/` that's usptream-compatible so fixes made there can flow upstream if necessary).

**Comment by ltangvald** [comment]
The MySQL licenses are explained under the following URLs.
http://www.mysql.com/about/legal/licensing/oem/
http://www.mysql.com/about/legal/licensing/foss-exception/

However, it's not necessary for the Docker image files to follow MySQL license policy exactly.
It's nice if the license is easily understood for those used to the MySQL license, so having the same or something close should be a good way to go.

**Comment by tianon** [comment]
So, the conclusion is that `GPL-2+` is OK since it's understood and compatible with the MySQL license, or should we switch to something else after all?

**Comment by yngves** [comment]
@tianon My advice would be to align completely with the MySQL Community Server license (GPL v2 only), i.e. scratch the '+'. Makes for less confusion for contributors and could save us from potential issues in the future.

**Comment by tianon** [comment]
Ok, fair and easy! :+1:

Right now, the commit message is the only thing that's actually mentioning v2+ -- the file is actually a strict v2.  Not sure what the best way to make it clear we're strict v2 now. :confused:

**Comment by yngvesv** [comment]
I wouldn't worry too much. As long as a) the few people who contributed during the period where the license was (at least in some places) presented as v2+ are OK with the license of their contributions being clarified/changed to 2 only, and b) the actual license text from now on doesn't contain the "or later" clause, everything should be formally OK. I don't know if there are projects out there who spell out specifically that they are 2 only, but from what I have seen, you usually have to check the license text for that. So I really wouldn't be too worried about it.

**Comment by tianon** [comment]
:metal:
