### ISSUE TITLE
Add support for an env variable allowing to pass which privileges to give to MYSQL_USER 

### ISSUE THREAD

**Issue by renflo** [docker-library/mysql#552]
I have a use case where I'd benefit from being able to pass the list of privileges to the created MySQL user: we use the MySQL container at build time (integration tests) and it would be great to be able to control privileges given to the MySQL user as that would lead to better matching the privileges really used in production environments (where grant all is not a best practice).

Proposal:
This line contains the hardcoded variant currently relied upon: https://github.com/docker-library/mysql/blob/bb7ea52db4e12d3fb526450d22382d5cd8cd41ca/5.7/docker-entrypoint.sh#L187

What about relying on a new (optional) env variable that could be used to customize the list of privileges? if not set use today's grant all behavior, and if set use its value instead of "all".

**Comment by yosifkit** [comment]
I'd rather not add additional functionality to the entrypoint and instead suggest using `/docker-entrypoint-initdb.d/` for more complex user setup.

**Comment by tianon** [comment]
Agreed, adding more environment variables is a bit of a slippery slope that we've already fallen a bit far down. :sweat_smile:

If you really want an environment variable to control this, you should be able to drop a pretty simple `xyz.sh` script into `/docker-entrypoint-initdb.d/`, although if you've just got a static set of permissions you want for a specific user you want to create, you might have an easier time dropping in `xyz.sql` and just have a simple `CREATE USER` query run. :+1:
