### ISSUE TITLE
How to compile MySQL manually ?

### ISSUE THREAD

**Issue by axot** [docker-library/mysql#556]
I checked the Dockerfile which using a precompiled .deb file, I want to use a custom MySQL has compatibility with current MySQL docker image.

Other projects like PHP is building binary inside it's Dockerfile. https://github.com/docker-library/php/blob/master/7.3/stretch/cli/Dockerfile

**Comment by wglambert** [comment]
PHP is compiled from source because it's the upstream recommendation https://github.com/docker-library/php/issues/720
https://github.com/docker-library/faq#why-do-so-many-official-images-build-from-source

If you want an image of mysql built from source then it's possible someone has made or is maintaining one, otherwise you'd be building it yourself. 

Upstream's docs on building from source https://dev.mysql.com/doc/mysql-sourcebuild-excerpt/8.0/en/

**Comment by axot** [comment]
@wglambert Hello, I understand why MySQL use pre-built binary. As I said we want to use a custom MySQL has compatibility with current MySQL docker image, which meaning use exactly the same compile options and same file structure, advice?

**Comment by tianon** [comment]
That's really out of scope in this repository.  I'd suggest finding the source that builds the upstream `.deb` files we consume and copying or using what you need from there.

Closing since this isn't really directly related to (nor an issue we could fix) in this image.

**Comment by ltangvald** [comment]
Our apt repos supply source debs, which will have the same flags set as the ones used here.
If you configure the repo at repo.mysql.com (https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/),
you can use the command
  apt-get source mysql-server
Which will download the source. You should then have a build-ready directory named mysql-community-[version] or similar.
Run
  apt-get build-dep mysql-server
to install build-dependencies. There's one dependency this will not handle: MySQL requires a very specific version of boost to install, and is by default set to look for it in usr/share/global (which will tend to only be root-writable if it even exists). You can change the DWITH_BOOST flag in the debian/rules file to point to a more suitable location, and also add DDOWNLOAD_BOOST=1 to make it download the appropriate package.
After this, you should be able to simply run a variation of "debuild -uc -us " inside the source directory, and it will build the packages.

**Comment by axot** [comment]
@ltangvald Thank you for such a detailed explanation.
