### ISSUE TITLE
Error executing mysql docker container on macOS Mojave Version 10.14.4 [ Errcode: 13 - Permission denied ]

### ISSUE THREAD

**Issue by kauezanetti** [docker-library/mysql#559]
Good afternoon, 
I can not run the mysql container.

Version of the docker environment:
- docker desktop: 2.0.3.0
- engine: 18.09.3
- compose: 1.24.0-rc1
- machine: 0.16.1

When executing the command:
**$ docker-compose up nginx mysql phpmyadmin redis**

I receive the following message during the initialization of the mysql container:

**Initializing database
mysqld: Can not create / write to file '/ var / lib / mysql / is_writable' (Errcode: 13 - Permission denied)
[Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
[Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in the future release.
[Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
[ERROR] --initialize specified but the data directory exists and is not writable. Aborting.
[ERROR] Aborting**

**Comment by kauezanetti** [comment]
> Good afternoon,
> I can not run the mysql container.
> 
> Version of the docker environment:
> **
> 
> * docker desktop: 2.0.3.0
> * engine: 18.09.3
> * compose: 1.24.0-rc1
> * machine: 0.16.1
>   **
> 
> When executing the command:
> **$ docker-compose up nginx mysql phpmyadmin redis**
> 
> I receive the following message during the initialization of the mysql container:
> 
> **Initializing database mysqld: Can not create / write to file '/ var / lib / mysql / is_writable' (Errcode: 13 - Permission denied) [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details). [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in the future release. [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set. [ERROR] --initialize specified but the data directory exists and is not writable. Aborting. [ERROR] Aborting**

**Comment by kauezanetti** [comment]
I found a solution to this error on the link  [https://stackoverflow.com/questions/19265916/file-ib-logfile101-aio-write-returned-os-error-122](url)
and 
[https://github.com/docker-library/mysql/issues/371](url)

it was necessary to put **user: "1000: 50"** in file **docker-compose.yml**
after run appeared another error:
[InnoDB] Operating system error number 22 in a file operation.
[InnoDB] Error number 22 means 'Invalid argument'
[InnoDB] File ./undo_001: 'aio write' returned OS error 122. Can not continue operation
[InnoDB] Can not continue operation.

so i put **innodb_use_native_aio = 0** in the file **laradock / mysql / my.cnf**

**Comment by erlangp** [comment]
how to fix this sir @kauezanetti ?
