### ISSUE TITLE
Missing directories for a default installation

### ISSUE THREAD

**Issue by cezmunsta** [docker-library/mysql#562]
A standard installation of MySQL (both for Oracle MySQL and Percona Server for MySQL) will create the following directories:
- `/var/lib/mysql`
- `/var/lib/mysql-files`; default directory used for `secure_file_priv` is `/var/lib/mysql-files`, whereas this is disabled in this image for some reason.
- `/var/lib/mysql-keyring`; default `keyring_file_data` is `/var/lib/mysql-keyring/keyring`, which means that enabling the plugin immediately causes a warning and forces setting the keyring to be part of the MySQL datadir or similar

Additionally, the permissions for the datadir are inconsistent. Here are the default permissions for the installation:
```
=> docker exec oracle-mysql-8.0 ls -ld /var/lib/mysql{,-files,-keyring}
drwxr-x--- 1 mysql mysql 604 May  7 11:53 /var/lib/mysql
drwxr-x--- 1 mysql mysql   0 May  7 11:53 /var/lib/mysql-files
drwxr-x--- 1 mysql mysql   0 Jan 25 23:03 /var/lib/mysql-keyring
```
Here is the permission set for this image:
```
=> docker exec docker-mysql-8.0 ls -ld /var/lib/mysql
drwxr-xr-x 1 mysql mysql 522 May  7 12:09 /var/lib/mysql
```

**Comment by ltangvald** [comment]
Generally, these paths (datadir, keyring and secure-file-priv) need to be mounted outside the image to be useful (datadir is mounted by default as an anonymous volume) for anything besides simple testing. It's generally a bad idea to store state in the container, because it is ephemeral by nature. So having them created by default probably isn't very useful.

It might be a good idea to add some permission handling for these paths if they exist, since a common issue for Docker is that mounted paths don't have the correct permissions to be used from inside the container. e.g. the entrypoint script tries to ensure the mysql user owns datadir

**Comment by cezmunsta** [comment]
@ltangvald if you are suggesting that this is not an issue then I disagree - the `datadir` is created and managed, so do the same for the other default directories. If a user wants to test MySQL then they are forced to create these directories rather than just use them ephemerally with the relevant config options.

**Comment by tianon** [comment]
I don't think he's suggesting it's not an issue -- I think he's suggesting that it *could* be an issue depending on how folks are using it and how these directories get passed in from the host, so it might in fact make sense for us to do something with their permissions during container startup like we do for `/var/lib/mysql`.

**Comment by tianon** [comment]
In other words, this might need to be an expansion of the logic in https://github.com/docker-library/mysql/blob/3362baccb4352bcf0022014f67c1ec7e6808b8c5/8.0/docker-entrypoint.sh#L85-L92 to handle these other settings as well to ensure appropriate permissions on those directories if MySQL is configured to use them.

**Comment by cezmunsta** [comment]
> I don't think he's suggesting it's not an issue -- I think he's suggesting that it _could_ be an issue depending on how folks are using it and how these directories get passed in from the host, so it might in fact make sense for us to do something with their permissions during container startup like we do for `/var/lib/mysql`.

 OK, but..

> So having them created by default probably isn't very useful.

This is untrue, hence why I interpreted as "not an issue" - you can't create them afterwards without deviating from the image
