### ISSUE TITLE
Disable aio in MySQL image since if the host volume is on ZFS the image does not work  (Worse case expose it through a flag)

### ISSUE THREAD

**Issue by jk-shah** [docker-library/mysql#57]
https://answers.launchpad.net/ubuntu/+question/249586

Have to use 
innodb_use_native_aio = 0

to deploy it on ZFS

**Comment by yosifkit** [comment]
Did you try using `docker run -it mysql --innodb_use_native_aio=0` and that did not work? (since that is what the launchpad post has as not working)

I am not quite sure we want more env vars for things that should be in a custom my.cnf. @tianon?

**Comment by ioggstream** [comment]
I think we could provide a my-zfs.cnf

**Comment by yosifkit** [comment]
That seems reasonable, but how do they enable this config?

**Comment by tianon** [comment]
I'm +1 to better documenting how people can/should provide their own configuration files, but I'm very much -1 on making changes to the default configuration provided by upstream anywhere we can avoid it (especially just for something that's not likely to be extremely common, like running on top of ZFS).

With automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links), it's reasonably easy to have an up-to-date image built `FROM` this one with additional configuration included.

**Comment by ioggstream** [comment]
To enable the configuration just use --defaults-file=/my-zfs.cnf

Anyway you should take care of your fs specific settings
