### ISSUE TITLE
[minor] mysql config file with wrong tag name /etc/mysql/conf.d/mysql.cnf

### ISSUE THREAD

**Issue by 2811299** [docker-library/mysql#576]
I'm a FNG, please forgive me if my understanding is wrong, I've tried my best to think before submit.

After docker starts, it will generate config file under /etc/mysql in docker container.
>ls /etc/mysql
conf.d	my.cnf	my.cnf.fallback

in ```my.cnf```, it will include all the config files in ```/etc/mysql/conf.d``` folder.
while in ```/etc/mysql/conf.d/mysql.cnf``` it's like 
>[mysql]

but it's not working, I think it should be

>[mysqld]

according to doc https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html, 
it has ```[mysqld]``` but no ```[mysql]``` so why ```/etc/mysql/conf.d/mysql.cnf``` by default has a ```[mysql]``` tag?

**Comment by wglambert** [comment]
The Dockerfile adds in `/etc/mysql/mysql.cnf` and the `mysql.conf.d/`
https://github.com/docker-library/mysql/blob/079f14e683025c9dde02f20da575fa2f4149fe2d/8.0/Dockerfile#L69
Wherein the `my.cnf` is placed https://github.com/docker-library/mysql/blob/master/8.0/config in its default location
From https://dev.mysql.com/doc/refman/8.0/en/option-files.html#option-files-unix
```console
root@31a08aee9308:/etc/mysql/conf.d# grep -v '^#\|^$' /etc/mysql/my.cnf
[mysqld]
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
secure-file-priv= NULL
symbolic-links=0
!includedir /etc/mysql/conf.d/
```
The `!includedir` is what gives mysql knowledge of that config directory, I'm not entirely certain where that `conf.d/mysql.conf` is coming from but it's `[mysql]` directive is for the client, while `[mysqld]` is for the server

From the above docs page:
>the [mysqld] and [mysql] groups apply to the mysqld server and the mysql client program, respectively.

**Comment by 2811299** [comment]
> The Dockerfile adds in `/etc/mysql/mysql.cnf` and the `mysql.conf.d/`
> 
> https://github.com/docker-library/mysql/blob/079f14e683025c9dde02f20da575fa2f4149fe2d/8.0/Dockerfile#L69
> 
> Wherein the `my.cnf` is placed https://github.com/docker-library/mysql/blob/master/8.0/config in its default location
> From https://dev.mysql.com/doc/refman/8.0/en/option-files.html#option-files-unix
> 
> ```
> root@31a08aee9308:/etc/mysql/conf.d# grep -v '^#\|^$' /etc/mysql/my.cnf
> [mysqld]
> pid-file        = /var/run/mysqld/mysqld.pid
> socket          = /var/run/mysqld/mysqld.sock
> datadir         = /var/lib/mysql
> secure-file-priv= NULL
> symbolic-links=0
> !includedir /etc/mysql/conf.d/
> ```
> 
> The `!includedir` is what gives mysql knowledge of that config directory, I'm not entirely certain where that `conf.d/mysql.conf` is coming from but it's `[mysql]` directive is for the client, while `[mysqld]` is for the server
> 
> From the above docs page:
> 
> > the [mysqld] and [mysql] groups apply to the mysqld server and the mysql client program, respectively.

Thank you.
