### ISSUE TITLE
Init process fails after timeout if MYSQL_PWD environment variable is defined

### ISSUE THREAD

**Issue by ypereirareis** [docker-library/mysql#582]
Hi, thanks for this useful image and your work ! :smiley: 

## Problem

```
mysql-db      | 2019-08-01T09:37:02.135128786Z MySQL init process in progress...
mysql-db      | 2019-08-01T09:37:03.149603593Z MySQL init process in progress...
...
mysql-db      | 2019-08-01T09:37:21.345066347Z MySQL init process in progress...
mysql-db      | 2019-08-01T09:37:22.347455022Z MySQL init process failed.
```

### User

Do not define `MYSQL_PWD` environment variable in your docker configuration during the init process.

### Entrypoint

Maybe a fix/trick could be done in the entrypoint to break the `MYSQL_PWD` variable value before init process and redefine it just before starting `mysqld`.

Thx. Bye

**Comment by wglambert** [comment]
`MYSQL_PWD` isn't defined, when you have the `docker-entrypoint` initialize the database it does so with [`--initialize-insecure`](https://dev.mysql.com/doc/refman/5.7/en/data-directory-initialization.html#data-directory-initialization-procedure)

https://github.com/docker-library/mysql/blob/51f9523ad07abacbce90c43eb27390c1c1f76266/8.0/docker-entrypoint.sh#L110-L112

And when it later goes to connect, the script does so before it changes the root user password to the `MYSQL_ROOT_PASSWORD`
https://github.com/docker-library/mysql/blob/51f9523ad07abacbce90c43eb27390c1c1f76266/8.0/docker-entrypoint.sh#L125-L133

So you get a `Access denied for user 'root'@'localhost' (using password: YES)` 

---

What you could do is have the container initialize, and then stop/start the container with your `MYSQL_PWD` set

**Comment by yosifkit** [comment]
> This method of specifying your MySQL password must be considered extremely insecure and should not be used. Some versions of ps include an option to display the environment of running processes. On some systems, if you set MYSQL_PWD, your password is exposed to any other user who runs ps. Even on systems without such a version of ps, it is unwise to assume that there are no other methods by which users can examine process environments.
>
> \- https://dev.mysql.com/doc/refman/8.0/en/password-security-user.html

We are not going to adjust the entrypoint script to block a bad env var since that would open the gates for possibly doing the same for all [env vars used by `mysql` and `mysqld`](https://dev.mysql.com/doc/refman/8.0/en/environment-variables.html).
