### ISSUE TITLE
initing sql files hasnt been executed when build

### ISSUE THREAD

**Issue by yunfan** [docker-library/mysql#585]
according to https://hub.docker.com/_/mysql    chapter  "Initializing a fresh instance"

> When a container is started for the first time, a new database with the specified name will be created and initialized with the provided configuration variables. Furthermore, it will execute files with extensions .sh, .sql and .sql.gz that are found in /docker-entrypoint-initdb.d. Files will be executed in alphabetical order. 

but i found that .sql files i had put in that directory hasnt been executed.

and here is my repodution files, the files is very small, so i just use base64 to dump it

> H4sIAMUxXl0AA+1YbW/bNhD2Z/2Km2fA8TDZki3LgQx/8JIWGJAuW5OiGLZBpSTK5ixRqijZMer+
> 9x0lWXltsqFuim18PlgSea+84/HoeCveR3qQ+Cua6V6xGLQODwMxGY/l05yMjZvPPVrmaDycWCNj
> aNotwxxaptGC8Rew5R4KkZMMoPXnNnyU7qn5fyniu/H38+jQOp6Iv2lZd+M/Ms1JC4xDG/IQ/ufx
> //abgcf4QCw17af5qxczTAHt5/nFxaxtDkfW2G5r2snb01nnKN0EPc0ngkLHBMY1gICmUbLt4Ru+
> lwkEuJb+qp4AXfeTOE0E1UMW0ZpkP9bfxhF0pErkn041/E2LbEEfEJfFDSHAZillOTVV+QCIaJj7
> ScFztLNmTQXsYJHRFNqdD5L7o9vGkY0PetSr2VgIv0GnYQadvgcD/qhn8yXl9SuAl1Gyqr9CVr+I
> iKJ8s7aF08aTKFm45ca67Q3N1synclaAHl4bVpK2G+41zVhYr6uf8JwwTrNHPasE4LBfoBehCXrQ
> he4t5fSKoutMOglnJ+787Gx20n9z+VI/hk6jBEpBoBdZkiBl2q1yoCuZugWG3sN4UB5MQSyTDeTE
> i6iYdhvLUZBIIvpVTPcI5vDekO8qAdRfJtB+I8iCOr/zjlFn5q7MtF0TpV214rva/DoSVBBf0772
> /vzSuFf/72/Tz9Yhi7xtWZ+s/8ZwX/+HE2OEdKZtWENV/58DmPqCJdyB7qg/6WpaXaREVWHL7HCa
> KshiuZPq0eNmOKNyDXMHSLQhW9GMb5JsxfjCDVjmwD6xKM+zbZownuuMszzw+kHDQPmaZQmPkeZa
> qcSrXy9+OXNfn59fuvJwenv++tSBqjg9QHc6v5z/ML944ezrVUODWR0THjh4NgU0JEWU66SQhT5n
> PslxHfQ0KhaMz0oXXY5ja+qmRAj0JUCumFzh1uCc+pJazIaGIc+5JcmIn6N3gua6XEKsekUeHsee
> VR6DUVRJvz3lFpz5SUBdnzUWrpOoiPfLv4cO9TYlOXEGa5INIuYNyrE7dP1qdCCX1nlsybUbim4I
> /8/XO4XbuFf/q/w5qI6/f/8bTsbDkez/x7al7n/PgU/EX9aJgyXBP4m/bSOdaY1Htor/c+Cx+Muf
> Pn59ro4n+j+884/uxN+WfwOo/u8ZcPNWp2k+XnNzWl3s5PWY4zWQXjGRC3iHlNk7OAL5/DEA7Cag
> 4IItOA1KOl5EEaQZ9ojZFlZ0+z1gd7PiJKaAHYtskY5sq3dN2sN2D1stOmOcJ4E3Va2HgoKCgoKC
> goKCgoKCgoKCgoLCofEXQTsp+gAoAAA=

just use  `base64 -d` to decode it and save it as a .tar.gz file

the target enviroment is `docker warm`

after you extract the files

use `sudo ./ctl deploy` to deploying the service and  use `sudo ./ctl verify` to check the problem

**Comment by wglambert** [comment]
The entrypoint will only execute `/docker-entrypoint-initdb.d/*` files if it also creates the database. On your initial start the db is populated by the entrypoint script and so the `init.sql` is executed. On subsequent starts the database is already populated so the entrypoint doesn't overwrite it, apply any environment variables, or execute any files

https://github.com/docker-library/mysql/blob/68f5102a73d8df4d739c20c581518850350794f6/8.0/docker-entrypoint.sh#L100

First run:
```console
$ docker-compose up -d
Creating network "mysql-docker-bug_default" with the default driver
Creating volume "mysql-docker-bug_mysql-data" with default driver
Creating mysql-docker-bug_mysql_1 ... done

$ docker-compose logs | grep -i init.sql
mysql_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
```

Second run (with populated data directory):
```console
$ docker-compose down
Stopping mysql-docker-bug_mysql_1 ... done
Removing mysql-docker-bug_mysql_1 ... done
Removing network mysql-docker-bug_default

$ docker-compose up -d            
Creating network "mysql-docker-bug_default" with the default driver   
Creating mysql-docker-bug_mysql_1 ... done

$ docker-compose logs | grep -i init.sql

$ docker-compose logs 
Attaching to mysql-docker-bug_mysql_1
mysql_1  | 2019-08-22T17:02:31.434512Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.                                          
mysql_1  | 2019-08-22T17:02:31.434586Z 0 [System] [MY-010116] [Server]
mysql_1  | 2019-08-22T17:02:34.046380Z 0 [Warning] [MY-010068] [Server
mysql_1  | 2019-08-22T17:02:34.504300Z 0 [Warning] [MY-011810] [Serverath is accessible to all OS users. Consider choosing a different direc
mysql_1  | 2019-08-22T17:02:34.551634Z 0 [System] [MY-010931] [Server]un/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.     
mysql_1  | 2019-08-22T17:02:34.810349Z 0 [System] [MY-011323] [Server]address: '::' port: 33060
```

https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance
It's only when "Initializing a **fresh** instance", where the entrypoint is overwriting anything

**Comment by yunfan** [comment]
thanks the problem solved
