### ISSUE TITLE
Content of /tmp/mysql-first-time.sql shouldn't be added to bin-log

### ISSUE THREAD

**Issue by ioggstream** [docker-library/mysql#59]
The 5.6 image doesn't work with mysql-fabric. 

This is because - when you add a slave - it tries to replicate the content of /tmp/mysql-first-time.sql.

Starting  /tmp/mysql-first-time.sql. with the following, will solve the issue

        SET @@SESSION.SQL_LOG_BIN=0;

Further infos here http://vaunaspada.babel.it/blog/?p=883

**Comment by josephpage** [comment]
Closed by #60  @tianon
