### ISSUE TITLE
Allow running mysql_upgrade after database booted

### ISSUE THREAD

**Issue by zedtux** [docker-library/mysql#608]
When importing data from an older version of MySQL, this image should have an option, like `MYSQL_UPGRADE` in order to execute `mysql_upgrade --version-check` right after the data has been imported.
Also this `MYSQL_UPGRADE` variable could be set to `force` so that the `--force` flag is passed to `mysql_upgrade`.

I read from #592 that MySQL 8.0.16 and newer doesn't need this anymore, so a version check should also be used in order to run the upgrade for the right versions.

**Comment by tianon** [comment]
Duplicate of #130

**Comment by zedtux** [comment]
Duplicate ... not 100% but whatever.
