### ISSUE TITLE
Attempt to deploy 5.6 or 5.7 fails on COPY docker-entrypoint.sh

### ISSUE THREAD

**Issue by garnetr** [docker-library/mysql#609]
On a Mac, I am trying to prepare a docker for MySQL use with PhpStorm, and a project using Code Igniter. I am right clicking my docker-compose.yml file and selected "Run" from PhpStorm IDE.

Using MySQL containers based on MySQL 8 fail on login from tools like SequelPro with errors like: "caching_sha2_password image not found" .  So I am trying to create a container with an older MySQL that hasnt switched to that newer password hashing.

But when using a Dockerfile from 5.6 or 5.7 to build a container, I get this failure:

Step 14/18 : COPY docker-entrypoint.sh /usr/local/bin/
ERROR: Service 'mysql-5.6.46' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder144591432/docker-entrypoint.sh: no such file or directory
Failed to deploy 'Compose: docker-compose.yml': `docker-compose` process finished with exit code 1

**Comment by garnetr** [comment]
Solution:
Place the desired docker-entrypoint.sh in the same directory as the dockerfile.

**Comment by haltsir** [comment]
I'm experiencing the same issue, not sure why it was closed since it's not resolved.

@garnetr Where do I get the `docker-entrypoint.sh` file from?
