### ISSUE TITLE
MySQL Docker instance not acessible via tools

### ISSUE THREAD

**Issue by computamike** [docker-library/mysql#610]
I'm a bit of a noob when it comes to Docker / MySQL - but when I read the docs (https://hub.docker.com/_/mysql) 

> Starting a MySQL instance is simple:
> 
> $ docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag
> ... where some-mysql is the name you want to assign to your container, my-secret-pw is the password to be set for the MySQL root user and tag is the tag specifying the MySQL version you want

I assumed that the upshot would be a server that I would be capable of connecting to via MySQL tools (such as MySQL WorkBench).

However repeated attempts to do this have left me berreft of hair 

![Actual footage of me attempting to connect to a MySQL Docker Instance](https://media.giphy.com/media/11daZqJWhUZucE/giphy.gif)

Best way we (hat tip to @karl-roberts here) is to add the MYSQL_ROOT_HOST=% as part of the container creation command.

Might be worth adding this or some similar supporting notes to the documentation?  

If I have an existing container though I am a little unsure about how to update the configuration accordingly.

**Comment by computamike** [comment]
And - followoing a morning we've found that I just needed to expose 3306 - so passing in -p3306:6603 allows a 'useable' docker instance : 

`docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -p 3306:3306 -d mysql:5.7.28`

**Comment by wglambert** [comment]
We generally don't include Docker documentation in the specific image documentation, it would be either too verbose or insufficient, and out of place.

https://docs.docker.com/config/containers/container-networking/#published-ports
>By default, when you create a container, it does not publish any of its ports to the outside world. To make a port available to services outside of Docker, or to Docker containers which are not connected to the container’s network, use the --publish or -p flag. This creates a firewall rule which maps a container port to a port on the Docker host.

Additionally using a custom config file would ensure you have appropriate settings in the container
https://github.com/docker-library/docs/tree/master/mysql#using-a-custom-mysql-configuration-file

**Comment by yosifkit** [comment]
Just to make it also clear `MYSQL_ROOT_HOST=%` is the default when you don't specify it:
https://github.com/docker-library/mysql/blob/75f81c8e20e5085422155c48a50d99321212bf6f/.template.Debian/docker-entrypoint.sh#L173
https://github.com/docker-library/mysql/blob/75f81c8e20e5085422155c48a50d99321212bf6f/.template.Debian/docker-entrypoint.sh#L21-L24

**Comment by yosifkit** [comment]
Closing since this seems to be solved ('twas a networking problem).
