### ISSUE TITLE
 The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!

### ISSUE THREAD

**Issue by xuping110** [docker-library/mysql#611]
i had use docker on windows 10 with shared disk,when I run code with -V ,the mariadb create succeed,but start with errors:
InnoDB: The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!

**Comment by wglambert** [comment]
Are you using a pre-populated volume or is the entrypoint initializing your databases?

I would make an issue over at https://github.com/docker/for-win/issues since this seems related to your environment and not necessarily an issue with the image

**Comment by wglambert** [comment]
There was also this answer to the same error in a different thread https://github.com/docker-library/mariadb/issues/95#issuecomment-372762289
>the `VOLUME` line you declare is probably not doing what you think it is doing (see [volumes](https://docs.docker.com/engine/reference/builder/#volume)). It is creating a folder at the path `/data:/var/lib/mysql/` in the container.  `VOLUME` in a Dockerfile can only declare a directory as a volume and cannot pre-seed where to mount that volume on run.
>
>To use the [already defined volume](https://github.com/docker-library/mariadb/blob/0ab4688d0e6d3a81d7cd19e04db44fb499c49d6a/10.2/Dockerfile#L114) on Docker for Windows you have to use a named volume like tianon suggested in the comments above yours.
>
>```console
>$ docker run -d -p 3306:3306 --name mariadb -v mysql-data:/var/lib/mysql stevenwillett/mariadb
>$ # to see the volume
>$ docker volume ls
>```
>
>Unfortunately, you cannot mount the folder for MariaDB to the host using Docker for Windows because it presents the shared files/folders permissions to the Linux container as root owned with writable only by root (755). 
>
>See also https://github.com/docker-library/percona/issues/42#issuecomment-298109103.

And this as well https://github.com/docker-library/mariadb/issues/95#issuecomment-407839431
>We recently added #168 which should make sharing a directory from a windows host possible.  Try the following (I don't have a host with Docker for Windows at the moment, but it worked when I last checked):

>```console
>$ # also updated to specify a version of mariadb so that things don't break when latest becomes 10.4
>$ docker run --name mariadb -d -v D:\Projects\docker\docker-qub:/var/lib/mysql -e MYSQL_USER=user -e MYSQL_PASSWORD=password -e MYSQL_DATABASE=address -e >MYSQL_ROOT_PASSWORD=password mariadb:10.3 --innodb-flush-method=fsync
>```
>
>For future users that are using docker-compose it would be adding `--innodb-flush-method=fsync` to the `command`.

Going to close since this is an issue with Docker for Windows

**Comment by ju5t** [comment]
@wglambert for the record, I have this issue on MacOS too. This is a relevant part of the `docker-compose.yml`.

```
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
```

**Comment by ibrahimawadhamid** [comment]
I'm facing the same issue on Ubuntu 20.04

**Comment by sign0** [comment]
Same issue on Debian 10 ...

**Comment by dEROZA** [comment]
Try to configure more correctly your volumes in compose.yml file

**Comment by felixhao28** [comment]
In my case, I ran out of disk space and this happened.

**Comment by materialsmoke** [comment]
For future users this is my experience:

I faced the same error and the problem was my local volume didn't exist.

```
version: "3.7"

services:
  mysql-db:
    image: mariadb:10.8
    container_name: mysql-db
    restart: unless-stopped
    tty: true
    ports:
      - "4407:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./db:/var/lib/mysql/
```
the folder `./db` did not exist.

after I make the folder, the error has been gone.

**Comment by snzhaoyua** [comment]
in my case, i ran mysql on a ntfs disk.
i changed it to a ext4 disk and problem solved.
