### ISSUE TITLE
Connect from host?

### ISSUE THREAD

**Issue by claudiu-cristea** [docker-library/mysql#62]
I created my container with:

```
$ docker run —­name db -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d mysql:latest
```

On my OS X, I used `boot2docker ip` to get the IP and I got `192.168.59.103`. Then I tried to connect from host:
```
$ mysql -u root -h 192.168.59.103
```

But I'm getting:

ERROR 2003 (HY000): Can't connect to MySQL server on '192.168.59.103' (61)

What I'm doing wrong?

**Comment by yosifkit** [comment]
For boot2docker you will need to have `-p 3306:3306` on the `docker run` so that it will be exposed to your Mac from the Linux VM.

**Comment by claudiu-cristea** [comment]
True. Forgot about that. Thank you!
