### ISSUE TITLE
Tag new version 8.0.19

### ISSUE THREAD

**Issue by kambo-1st** [docker-library/mysql#626]
Hello,

i just want to ask when the new version (8.0.19) of image will be tagged and how I can help to speed up the process.

Thank you in advance!

**Comment by yosifkit** [comment]
https://github.com/docker-library/mysql#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

So the images will be built and pushed once https://github.com/docker-library/official-images/pull/7274 merges.
