### ISSUE TITLE
is it normal to get two root users in the user table ?

### ISSUE THREAD

**Issue by beppe9000** [docker-library/mysql#631]
![image](https://user-images.githubusercontent.com/6625123/73222879-a3458a00-4164-11ea-90ab-ae6ad66fdb87.png)

The only difference is the host. Is this expected?

**Comment by wglambert** [comment]
Yes, the `root@localhost` doesn't require a password to connect, and `root@%` is added by the entrypoint on database initialization for external connections such as connecting from other containers

Every `user@host` gets a user entry

**Comment by beppe9000** [comment]
thanks for the info !
