### ISSUE TITLE
Alterting a big table on leads to "table xxx is full"

### ISSUE THREAD

**Issue by Gamesh** [docker-library/mysql#632]
I have a big table ~700MB running on docker when ever i attempt to change the primary key i get this message saying "table is full"
mysql:8 volume is mounted to macOS which has 200GB space free so it should be an issue. 

Feels like something inside docker container has too little space, perhaps it's not a good default and should be adjusted

**Comment by Gamesh** [comment]
it seems that /dev/sda1        15G   14G  151M  99% /etc/hosts
runs out of space while a temporary table is being created

**Comment by tianon** [comment]
There's nothing in the image which *can* define "free space" -- this is a function of the runtime (sometimes enforced by other external runtime constraints, such as the underlying storage or the graph driver in use).

**Comment by tianon** [comment]
I'd suggest checking your Docker Desktop or VM settings to ensure there's an appropriate amount of storage available to your container runtime.

**Comment by Gamesh** [comment]
you're right, docker has a 15GB of space reserved in docker desktop, didn't know about it
