### ISSUE TITLE
From Node.js app I get Access denied for user (using password: YES)

### ISSUE THREAD

**Issue by robogeek** [docker-library/mysql#638]
I have read a bunch of stackoverflow advice, the MySQL documentation, and several similar issue threads on this project.  I am trying to update a section in my Node.js book where it shows how to use a Node.js app with a Docker MySQL container.  

There are two containers connected to a common network (each started with `--network authnet`).  Container 1 is `db-userauth` and is created using `docker run` and a bunch of options on the command line.  Container 2 is `svc-userauth` and is created using a Dockerfile.  That container has a simple REST service that uses Sequelize in a Node.js app.  Sequelize tells me to use the `mysql2` package for Node.js.

The code works perfectly outside of Docker.  And it worked perfectly two years ago the last time I updated this book.

I am connecting using a user ID, `userauth`, that has ALL privileges for the `userauth` table and nothing else.  I do not want my app to connect to the database using `root` because the `root` user needs to be left as only usable from `localhost` for security reasons.

* I can connect using `mysql` command inside the database container, and `root` connects fine as would any user registered with `localhost`
* I can launch a second `mysql` container, using the `mysql` command there, and connect using desired user ID (`userauth`) using its password and type SQL commands
* I cannot connect using the Node.js app from its container

There are no other containers configured or running for this system.  The host computer is a Mac OS X laptop.

The MySQL container is started with:

```
docker run --name db-userauth  \
   --mount type=bind,src=`pwd`/sql-scripts/,dst=/docker-entrypoint-initdb.d/  \
   --mount type=bind,src=`pwd`/userauth-data,dst=/var/lib/mysql \
   --network authnet -p 3306:3306 \
   --env MYSQL_ROOT_PASSWORD=w0rdw0rd \
   --env DATABASE_HOST=db-userauth  \
   mysql:5.7 --bind_address=0.0.0.0
```

I have an initdb directory mounted into the container, and this includes a script `create-users.sql` containing:

```
CREATE DATABASE userauth;
/* CREATE USER 'userauth'@'localhost' IDENTIFIED BY 'userauth'; */
/* CREATE USER 'userauth'@'172.%.%.%' IDENTIFIED BY 'userauth'; */
CREATE USER 'userauth'@'%' IDENTIFIED BY 'userauth';
/* GRANT ALL PRIVILEGES ON userauth.* TO 'userauth'@'localhost' WITH GRANT OPTION; */
/* GRANT ALL PRIVILEGES ON userauth.* TO 'userauth'@'172.%.%.%' WITH GRANT OPTION; */
GRANT ALL PRIVILEGES ON userauth.* TO 'userauth'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
```

I did this rather than set MYSQL_USERNAME and those other environment variables, because the environment variables only added userauth@localhost.  I understand that to authenticate connection from a remote I need a userauth@% entry, and that there are several variants of this which can be used.

To emulate a remote connection to the MySQL instance, I can run this:

```
$ docker run -it --rm --network authnet mysql:5.7  mysql -u userauth -h db-userauth -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.29 MySQL Community Server (GPL)

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| userauth           |
+--------------------+
2 rows in set (0.13 sec)

mysql> ^DBye
```

Hence - this is a MySQL from a remote container successfully connecting to the `db-userauth` instance and running SQL commands.

Connecting a session using `docker exec -it db-userauth mysql -u root -p` I get the following:

```
...
mysql> use mysql;
...
mysql> select user,host from user;
+---------------+-----------+
| user          | host      |
+---------------+-----------+
| root          | %         |
| userauth      | %         |
| mysql.session | localhost |
| mysql.sys     | localhost |
| root          | localhost |
+---------------+-----------+
5 rows in set (0.00 sec)
...
mysql> show grants for userauth@'%';
+--------------------------------------------------------------------------+
| Grants for userauth@%                                                    |
+--------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'userauth'@'%'                                     |
| GRANT ALL PRIVILEGES ON `userauth`.* TO 'userauth'@'%' WITH GRANT OPTION |
+--------------------------------------------------------------------------+
2 rows in set (0.00 sec)

mysql> show grants for userauth@'172.20.0.3';
ERROR 1141 (42000): There is no such grant defined for user 'userauth' on host '172.20.0.3'
mysql> 
...
mysql> show create user 'userauth'@'%';
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CREATE USER for userauth@%                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CREATE USER 'userauth'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*E42080C77C398C9F75A841BF6A26CDFE9977BD95' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> show create user 'userauth'@'172.20.0.3';
ERROR 1396 (HY000): Operation SHOW CREATE USER failed for 'userauth'@'172.20.0.3'
mysql> 

```

But -- if I run the query through my server, I get this:

```
2020-02-18T04:14:12.664723Z 5 [Note] Access denied for user 'userauth'@'172.20.0.3' (using password: YES)
```

Some details from the log of the server:

```
2020-02-18T04:03:18.988Z users:model-users Sequelize params {
  dbname: 'userauth',
  username: 'userauth',
  password: 'userautn',
  params: { host: 'db-userauth', port: 3306, dialect: 'mysql' }
}
2020-02-18T04:03:19.250Z users:error /list SequelizeAccessDeniedError: Access denied for user 'userauth'@'172.20.0.3' (using password: YES)
    at /userauth/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:125:19
```

**Comment by wglambert** [comment]
Your `userauth-data` folder that's mounted to `/var/lib/mysql` isn't empty so the entrypoint thinks there's an existing database and won't touch it or run the `docker-entrypoint-initdb.d/` scripts

So the `MYSQL_ROOT_PASSWORD=w0rdw0rd` also won't be interpreted by the entrypoint when the database is already present on startup

https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance
You should populate your database by mounting a SQL dump into `docker-entrypoint-initdb.d/`

**Comment by robogeek** [comment]
No, I should have said this earlier.  I have been deleting the `userauth-data` directory (rm -rf) and creating an empty directory (mkdir) on every experiment.  Changes to the script in initdb directory have been reflected in the database that's generated each time.

I dumped all the grants and other things for you.

Given this grant:

```
mysql> show grants for userauth@'%';
+--------------------------------------------------------------------------+
| Grants for userauth@%                                                    |
+--------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'userauth'@'%'                                     |
| GRANT ALL PRIVILEGES ON `userauth`.* TO 'userauth'@'%' WITH GRANT OPTION |
+--------------------------------------------------------------------------+
2 rows in set (0.00 sec)
```

Then why can't a program on another container access the `userauth` account with the password `userauth`?  In fact, from another container I can use the `mysql` program with that identity and it works, but from another container it is failing when using Node.js code that has worked fine in other contexts.

The described purpose of the initdb directory is to run SQL scripts.  Therefore there are tutorials available showing to use initialization scripts like what I've done.  You're suggesting that it's purpose is to fully initialize a database.  But the reality is that many are recommending to people this exact thing, which is to customize the creation of initial accounts and permissions in a way that's not supported by the standard MySQL Docker container.

The goal I have is how does one initialize a MySQL container so that software in another container can access the database.  The user defined in the database needs a GRANT of the sort I showed, but I don't see how to configure the container to generate that GRANT.  So then, how is one to automate the setup of that USER and GRANT?

**Comment by wglambert** [comment]
```
2020-02-18T04:03:18.988Z users:model-users Sequelize params {
  dbname: 'userauth',
  username: 'userauth',
  password: 'userautn',
```

Is the password supposed to be `userautn`

**Comment by robogeek** [comment]
AAAAARGH!  Thank you for your help.  You're right.  I had a mistake in a configuration file.
