### ISSUE TITLE
Continue on error during initialisation

### ISSUE THREAD

**Issue by sambeckingham** [docker-library/mysql#648]
I have a large database dump I'm placing into /docker-entrypoint-initdb.d, but it's got an error in it (duplicate key) - Is it possible to somehow run with the `--force` tag so we can replicate behaviour similar to the command line or MySQL Workbench?

**Comment by yosifkit** [comment]
I'm assuming that your dump is just a series of `.sql` files.  We don't have a way to change how it processes each file. You can see the loop here:

https://github.com/docker-library/mysql/blob/d284e15821ac64b6eda1b146775bf4b6f4844077/.template.Debian/docker-entrypoint.sh#L50-L69

And the part running the sql:

https://github.com/docker-library/mysql/blob/d284e15821ac64b6eda1b146775bf4b6f4844077/.template.Debian/docker-entrypoint.sh#L186-L202

So my best suggestion would be to put the sql files elsewhere (like a subdirectory) and then drop your own import script (`.sh`) into `/docker-entrypoint-initdb.d/` to process them as you like.

**Comment by yosifkit** [comment]
Closing old issue.
