### ISSUE TITLE
MySQL data is not stored in data-only container

### ISSUE THREAD

**Issue by arun-gupta** [docker-library/mysql#65]
Creating a data-only container as `docker create -v /var/lib/mysql --name mysql_data mysql:latest`

Running a MySQL container as:

`docker run --name mysqldb --volumes-from mysql_data -e MYSQL_USER=mysql -e MYSQL_PASSWORD=mysql -e MYSQL_DATABASE=sample -e MYSQL_ROOT_PASSWORD=supersecret -it -p 3306:3306 mysql`

The data is not stored in the data-only container. This is verified by looking at the empty `/var/lib/mysql` directory on Boot2Docker host. This is also confirmed by logging into MySQL container and looking at `/var/lib/mysql`, which shows:

```
root@d69cb6430d9e:/var/lib/mysql# ls
auto.cnf  ib_logfile0  ib_logfile1  ibdata1  mysql  performance_schema	sample
```

I was expecting this to show up on the volume mounted by data-only container.

**Comment by itraor** [comment]
How about directly mounting the host volume into the container, as in:

... -v /var/lib/mysql:/var/opt/data/mysql

then mysql is made to point to '/var/opt/data/mysql'

?

**Comment by md5** [comment]
You didn't do anything to make the host directory be used. Your `docker create` command for the data container is not mounting anything, so it's using an "anonymous" volume that is mounted at `/var/lib/mysql` inside the container. You would need to do something like `-v /var/lib/mysql:/var/lib/mysql` to get what you're expecting.

If your goals is to have data on `/var/lib/mysql` on the Boot2docker VM, then you don't need a data container. You can just mount `/var/lib/mysql` into the actual MySQL server container with `-v /var/lib/mysql:/var/lib/mysql`.

However, I will warn you that `/var/lib/mysql` is not a directory that will be persisted after a boot2docker reboot, so it may not be the most reliable setup. You'll have better luck mounting it on the data drive (i.e. `/mnt/sda1`).

**Comment by thaJeztah** [comment]
If you want to know where the anonymous volume is created on the host; use `docker inspect [containername]`. In the output, you can find the path of the volume.

**Comment by arun-gupta** [comment]
@md5 that's the explanation I was looking for, thanks! Mounting on `/mnt/sda1` seems to be the right thing as opposed to `/var/lib/mysql`.

@thaJeztah I've been inspecting the volumes and was getting different directories, but is fine now.
