### ISSUE TITLE
CREATE TABLE with data type INT(11) ... Do not work properly  !

### ISSUE THREAD

**Issue by valterpinhopp** [docker-library/mysql#650]
Using mysql:8.0.19 docker image ...

Creating a table using :
```console
CREATE TABLE `mytable8` (
    **`id` int(11)** NOT NULL AUTO_INCREMENT,
    **`int11` int(11) ,**
    `int11zf` int(11) ZEROFILL,
    PRIMARY KEY (`id`) );
```
and describing it
```console
mysql> describe mytable8;

| Field   | Type                      | Null | Key | Default | Extra          |
| id      | **int**                       | NO   | PRI | NULL    | auto_increment |
**| int11   | int**                       | YES  |     | NULL    |                |
| int11zf | int(11) unsigned zerofill | YES  |     | NULL    |                |
```
int(11) only gets the proper type definition if using zerofill. On **MAC OS mysql version 8.0.18** the same stament creates the table properly ...
```console
Field	Type	Null	Key	Default	Extra
id	**int(11)**	NO	PRI		auto_increment
int11	**int(11)**	YES			
int11zf	int(11) unsigned zerofill	YES			
```

**Comment by wglambert** [comment]
https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html
>As of MySQL 8.0.17, the ZEROFILL attribute is deprecated for numeric data types, as is the display width attribute for integer data types. Support for ZEROFILL and display widths for integer data types will be removed in a future MySQL version. Consider using an alternative means of producing the effect of these attributes.

**Comment by wglambert** [comment]
Closing since this doesn't seem to be an issue with the image
