### ISSUE TITLE
Host independent data-only container for MySQL

### ISSUE THREAD

**Issue by arun-gupta** [docker-library/mysql#66]
Continuing from #65 

@md5

If `/var/lib/mysql` directory is used with data-only container, that would be host-specific solution as well. Is there a way to make it host independent?

Would `docker export` and `docker load` save the data dump as well?

Export tar size is slightly bigger after creating a simple table in MySQL database. But that still requires the directory to be created on the different host. What is the host independent solution?

**Comment by md5** [comment]
`docker export` does not export the content of volumes, regardless of whether they're explicitly mounted to a host directory or not. Until there is first-class support for volumes in Docker, I'd recommend the [`docker-volumes`](https://docker.com/cpuguy83/docker-volumes) tool, specifically the `docker-volumes export` subcommand.

I don't think the "data-only container" pattern really buys you anything. For a "host independent" solution in the Boot2Docker, the defaults are fine. The `mysql` container will create an anonymous volume at `/var/lib/mysql`. Like all anonymous volumes, this directory will reside somewhere under `/var/lib/docker` outside the container, which in the B2D case is actually `/mnt/sda1/var/lib/docker` on the VM's data disk (and thus suitable for long-term use as a data volume location).

If you need direct access to `/var/lib/mysql` inside your container for some reason, use `--volumes-from my-mysql-server`. You will need to be careful not to delete your `my-mysql-server` container without somehow preserving the data in its volume, but that's no different than the "data container" case. In fact, it's just one less container to worry about.

**Comment by md5** [comment]
And actually, I'd probably never work with the `/var/lib/mysql` volume directly if I could avoid it. I would just use normal `mysqldump` and `mysql` commands to backup and restore.

**Comment by arun-gupta** [comment]
"data-only container" creates a named volume as opposed to anonymous volume, and thus can be used by other containers. Anonymous volume scope is to a container only, isn't it?

Agreed on `mysqldump` and `mysql' for backup and restore. These would be used by connecting to the as `docker exec -it <CONTAINER_ID> bash` and then using the tools. correct?

**Comment by md5** [comment]
Any container can use another container's volumes with `--volumes-from`. It doesn't matter whether its explicitly mapped to a host directory or not.

As for running `mysqldump`, I would not use `docker exec` for that, but would instead link the other container with `--link my-mysql-server:mysql` and demonstrated in the docs: https://github.com/docker-library/docs/blob/master/mysql/README.md#connect-to-mysql-from-the-mysql-command-line-client

**Comment by arun-gupta** [comment]
So the directories are always host dependent? And that seems fine for now, until Docker natively provide some way?

And back/restore are used to move data across hosts?

**Comment by md5** [comment]
I don't understand your question or what you mean by “host dependent".

**Comment by arun-gupta** [comment]
I mean volumes are created on Docker host, which is Boot2Docker VM on Mac, correct? And they cannot, rather should not, be touched/moved around directly?

**Comment by md5** [comment]
Yes, that's right.

If you'd like to read more about how volumes may evolve in future versions of Docker, this is a good starting point: docker/docker#6496

**Comment by arun-gupta** [comment]
Understood, thanks once again!

**Comment by md5** [comment]
:metal:

**Comment by baozilala** [comment]
docker run -it -d -p 80:80 -v /Users/xxx/Docker/lamp/data/mysql:/var/lib/mysql -v /Users/xxx/Docker/lamp/www:/var/www/html 293ef2f50d98

_if i run command without " -v /Users/xxx/Docker/lamp/www:/var/www/html ", mysql could run normally_

I used 
     `docker run -it -d -p 80:80 -v /Users/xxx/Docker/lamp/data/mysql:/var/lib/mysql -v /Users/xxx/Docker/lamp/www:/var/www/html 293ef2f50d98`
to load host folder to container and mysql service couldn't run correctly ,error code is:
[....] Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . .[FAI failed!

i tried mysql -uroot -p i got error:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

also i checked  /var/lib/mysq permissions:
drwxrwxrwx  6 root root  204 Jul 11 03:11 mysql

when i use command: service mysql start, /var/lib/mysql folder will generate 3 log files.
ib_logfile0    -  5.2mb
ib_logfile1    -  5.2mb
ibdata1    -  18.9mb

and I searched many many websites but can't find a solution. anyone know what's going on here?

**Comment by yosifkit** [comment]
@baozilala, it looks like you are running it on OSX or Windows; you'll need to run mysql as the user of the VirtualBox shared filesystem.  It is usually user/group of 1000:50, so the following should work on the official image:

```console
$ docker run -it -d -p 80:80 -v /Users/xxx/Docker/lamp/data/mysql:/var/lib/mysql --user 1000:50 mysql
```

**Comment by baozilala** [comment]
Docker beta now support Mac and windows locally

**Comment by baozilala** [comment]
I give up to build my own mysql container now i pull from dockerhub, it works great. thanks.
