### ISSUE TITLE
cannot connect with sequel pro with mysql:latest

### ISSUE THREAD

**Issue by sebalaini** [docker-library/mysql#661]
making reference to a this [question](https://stackoverflow.com/questions/61275521/mysql-docker-cannot-connect-from-outside-container) in SO I'm unable to connect to the container if I'm running a version 8 of mysql while if I change to a version 5.7 everything works perfectly and I can connect from the app and sequel pro

**Comment by wglambert** [comment]
You might need to add `--default-auth=mysql_native_password` to your `command: `

Mysql:8 uses caching_sha2_password by default https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
https://github.com/docker-library/mysql/issues/454#issuecomment-406711790

**Comment by sebalaini** [comment]
Oh I see, I didn't check the upgrade guide and there are no guides yet about docker and Mysql 8 images
