### ISSUE TITLE
mysqli::real_connect(): (HY000/2002): Connection refused - mysql:8.0 docker image

### ISSUE THREAD

**Issue by snithyanantham** [docker-library/mysql#662]
Trying to use mysql 8.0 from https://hub.docker.com/layers/mysql/library/mysql/8.0/images/sha256-01455370d830fcd33cd61e4f82a9e2057f3e36aba40cc49b8b9b40207ee67663?context=explore

I am getting mysqli::real_connect(): (HY000/2002): Connection refused but with same configuration mysql:latest works fine.

Not Working :

mysql:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

Working fine :
mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

**Comment by wglambert** [comment]
Can you show the full log output?

https://www.digitalocean.com/community/questions/has-anyone-solved-this-error-a-php-error-was-encountered-severity-warning-msg-mysqli-real_connect-hy000-2002-connection-refused
>My guess would be that the server ran out of space and MySQL crashed

**Comment by snithyanantham** [comment]
> Can you show the full log output?
> 
> https://www.digitalocean.com/community/questions/has-anyone-solved-this-error-a-php-error-was-encountered-severity-warning-msg-mysqli-real_connect-hy000-2002-connection-refused
> 
> > My guess would be that the server ran out of space and MySQL crashed

@wglambert you may right. I am not able to reproduce this issue now. Let me close this issue will reopen if i get the proper logs again
