### ISSUE TITLE
What is the input parameter when deploying mysql-cluster container on openshift 4.3 

### ISSUE THREAD

**Issue by doyoungim999** [docker-library/mysql#670]
Hi , 

I am deploying mysql-cluster container on openshift ( https://hub.docker.com/r/mysql/mysql-cluster/) 

from the command for docker: 
docker run -d --net=cluster --name=management1 --ip=192.168.0.2 mysql/mysql-cluster ndb_mgmd

What is the input parameter format for ndb_mgmd ? 
I am trying to create like the following , but input parameter  is not working properly. 

[user2@codeReady ]$ oc new-app   -e ndb-mgmd mysql/mysql-cluster  --name=mysqlmgmt1
error: invalid parameter assignment in "ndb-mgmd", []

**Comment by wglambert** [comment]
That `mysql-cluster` image isn't maintained by us https://github.com/mysql/mysql-docker/tree/mysql-cluster
