### ISSUE TITLE
Can't load .sql file with volume loaded.

### ISSUE THREAD

**Issue by sweetsugarh** [docker-library/mysql#674]
Hello, Im triying to charge a .sql file from the directory /docker-entrypoint-initdb.d/ like the documentation says. The problem is that it only works the first time that i create the container. After the first time, the info saved in the volume overwrites the new data modified by the .sql file.

If I remove the volume i can start a new container with a .sql file and it works correctly. But after the firstime it overwritten again by the volume content.

```
- mariadb2:
-       image: 'mariadb:10.3'
-       container_name: mariadb2
-       volumes:
-         - './01-databases.sql:/docker-entrypoint-initdb.d/01-databases.sql'
-         - 'mysqldb:/var/lib/mysql'
-       environment:
-        - MYSQL_ROOT_PASSWORD=root
```

` CREATE DATABASE IF NOT EXISTS "testDatabase";`

For example. If I made two databases through .sql file and is the first time that I start the container, it works. But after that, if the container is removed and the .sql file is modified and try to create one new database, it doesn't work. For make it works I have to remove the actual volume and release the container again.

The documentation means that it only works with a fresh release, but it doesn't mean nothing about the volumes.

**Comment by wglambert** [comment]
https://github.com/docker-library/mysql/issues/585#issuecomment-523996549
The entrypoint will only execute `/docker-entrypoint-initdb.d/*` files if it also creates the database. 
So if `mysqldb` remains populated when starting a new container then the entrypoint won't modify its data. Specifically the execution of this block
https://github.com/docker-library/mysql/blob/a769034ab13634027413257584e921b4d50f5a3d/8.0/docker-entrypoint.sh#L351-L365
