### ISSUE TITLE
[Warning] Ignoring user change to 'root' because the user was set to 'mysql' earlier on the command line

### ISSUE THREAD

**Issue by alexanderilyin** [docker-library/mysql#68]
I've set `root` user in `/etc/mysql/conf.d/boot2docker.cnf`
```
[mysqld]
user		= root
```
but mysql starts under `mysql` user.
```
2015-05-01 06:12:23 0 [Warning] Ignoring user change to 'root' because the user was set to 'mysql' earlier on the command line
```
I want this dirty insecure hack because of problems with volumes when using `boot2docker` on OS X.

**Comment by alexanderilyin** [comment]
It works when user set in {{/etc/mysql/my.cnf}}.

**Comment by cocowool** [comment]
Any solution? i encountered such problem when i want to run mysql as a other user.

**Comment by yosifkit** [comment]
@cocowool, to run mysql as another user, just user the `--user` flag to `docker run`.  Be warned that permissions for `/var/lib/mysql` are now up to you to properly set; since the container does not start as root in this case, it cannot fix the permissions for you.

Something like this should work:

```console
$ mkdir sql-data
$ sudo chown 10000:10000 sql-data
$ docker run -d -e MYSQL_ROOT_PASSWORD=secret --user 10000:10000 -v "$PWD/sql-data":/var/lib/mysql mysql:8
```
