### ISSUE TITLE
Update example docker commands due to deprecated "--link" flag

### ISSUE THREAD

**Issue by MatanSilver** [docker-library/mysql#697]
In the single-process and multiiprocess links below, the example `docker` invokations use the "--link" flag, which is being deprecated by docker per [0]
https://github.com/huginn/huginn/tree/master/docker/single-process
https://github.com/huginn/huginn/tree/master/docker/multi-process

[0] https://docs.docker.com/network/links/

It seems based on docker's notice here that the recommended way to do this now would be either to connect to the database using a network and exposed port, or perhaps sharing `mysqld.sock` in a volume. Based on the error message I see when I remove the link flag, it appears that huginn is configured to use the socket directly, and might require some changes to connect to the database over the network? I'm not sure. Because of this I spent some time trying to get it to work with docker volumes to share `mysqld.sock` between the database container and the huginn container, but I haven't made much progress, so any pointers would be appreciated.

**Comment by wglambert** [comment]
Did you mean to make an issue over at https://github.com/huginn/huginn/issues?

The `mysql` image docs dropped the `--link` examples last year https://github.com/docker-library/docs/pull/1441 from the discussion in https://github.com/docker-library/mysql/issues/545#issuecomment-468761135

Also https://github.com/docker-library/faq/blob/master/README.md#--link-is-deprecated
>The documentation for "legacy container links" (--link) include a large warning about --link potentially going away at some point, but there is no timeline given and this "soft deprecation" has been going strong for a very long time. Their usage is definitely discouraged, but we expect Docker will continue to support them for quite some time.

**Comment by MatanSilver** [comment]
Oh you are correct! I must have opened it in the wrong tab. My apologies and thanks for your time
