### ISSUE TITLE
Copying jenkins.mysql.cnf to conf.d directory does not load configuration even though it ends in .cnf

### ISSUE THREAD

**Issue by joshunger** [docker-library/mysql#70]
Copying a file called jenkins.mysql.cnf to the conf.d directory does not load the configuration even though it ends in .cnf.  According to the documentation - "The MySQL startup configuration is specified in the file /etc/mysql/my.cnf, and that file in turn includes any files found in the /etc/mysql/conf.d directory that end with .cnf" 

This is my file content -

    [mysqld]
    local-infile=1
    group_concat_max_len=16777215

This seems like an odd bug.  Perhaps because I have two periods?

**Comment by md5** [comment]
I don't think the two periods are the issue. The code that checks filenames is here: https://github.com/mysql/mysql-server/blob/7e58ce8e69de5a4e941d913999cbbf905fe8f444/mysys_ssl/my_default.cc

It calls, `fn_ext` to get the extension for each file in the `!includedir` and checks it against the list of allowed extensions (`.cnf` on Unix, `.cnf` and `.ini` on Windows). The [`fn_ext` function](https://github.com/mysql/mysql-server/blob/f964f6b37337b98d467c1e9fb7914c1655a08e84/mysys/mf_fn_ext.c#L36) has this description:
>  The extension is defined as everything after the last extension character (normally '.') after the directory name.

**Comment by yngves** [comment]
Could it be that your jenkins.mysql.cnf is world-writable?

Quoting the MySQL manual at https://dev.mysql.com/doc/refman/5.6/en/option-files.html:
"On Unix platforms, MySQL ignores configuration files that are world-writable. This is intentional as a security measure."

**Comment by edmorley** [comment]
@joshunger, could you pastebin the startup log? if the file is world-writable a warning will be shown within it.

**Comment by tianon** [comment]
Closing old issue -- if this is still a problem (and can be easily reproduced), please open a new issue! (alternatively, the [Docker Forums](https://forums.docker.com) and the `#docker` IRC channel on Freenode are available for general help)
