### ISSUE TITLE
New MySQL (5.7) Docker Container: --initialize specified but the data directory has files in it. Aborting.

### ISSUE THREAD

**Issue by TurboCooler** [docker-library/mysql#700]
So, I did search and found other issues with the same topic --initialize specified but the data directory has files in it. Aborting.

I am new to Docker so the issue could very well be me.  Those solutions did not help me.  I have been fighting this issue for days.  

This is my docker compose file.  I am using the latest Docker for Windows.  I am using Linux containers.  I have given docker permission to the folder on my local file system.  I have 64gb free for Docker VM.

I looked at this file 
https://github.com/docker-library/mysql/blob/a6b87c55ecdf9426d42ff7814be7e9b1fc33b292/5.7/Dockerfile

It seems I am pointing to the correct internal volume.   I want to map the internal files to my local windows file system so I can persist data between sessions.  This is a laptop for development.

version: '3.3'
services:
  db:
    image: mysql:5.7
    command: --explicit_defaults_for_timestamp
    restart: always
    environment:
      MYSQL_DATABASE: 'ctestdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ctestuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ctestdbpwd'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysqlctestroot'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ../localdata/mysql_docker_data_files:/var/lib/mysql

**Comment by wglambert** [comment]
Maybe there's hidden files that you're not seeing in the default view, but `mysql` is detecting something there that's not a database

This thread might be helpful for you
https://github.com/docker-library/mysql/issues/290#issuecomment-297921843
>The entrypoint script checks if DATADIR/mysql exists. If not, it runs --initialize, but if DATADIR/ contains any files other than ones starting with . or specified with --ignore-db-dir, --initialize will fail with that error message.
>So the directory you map to :/var/lib/mysql should either contain an existing MySQL database or be completely empty

You could also try using a [named volume](https://success.docker.com/article/different-types-of-volumes) instead

**Comment by TurboCooler** [comment]
@wglambert -- thanks for the help.   That quoted answer helped but it was unclear.  In my mind, and apparently others because I have seen other posts like the above, DATADIR/mysql I assumed was related to the INTERNAL container file system.  I did not put 2 and 2 together to understand that when you map, it now refers to your local directory.   My local directory had a .ignore file that I could not see because of my explore properties.   Removing that file made everything work as-is with the docker-compose file listed in my original post.

Now, it would be nice to know if there is a command to have mysql initialize the directory or ignore files in that directory.  Anyway, that did the trick.  A better error msg or maybe a check of the directory would have save me so much pain. 

A simple, target directory (xxxxxxxxxxx) is not empty and must be empty to complete install would have save me and many others a lot of pain
