### ISSUE TITLE
Remove "latest" tag

### ISSUE THREAD

**Issue by Dragas** [docker-library/mysql#702]
Many a time developers are encouraged to use "latest" tag without researching what particular version does that tag correspond to. Later it gets propagated to build scripts, causing non-reproducable builds over time, docker-compose or general "tutorials" about how to use particular services from docker.

I urge you to remove the tag, as well as tags changing which builds they correspond to over time (ex. 8 corresponding to 8.0.21 and perhaps later versions).

**Comment by yosifkit** [comment]
Related comment on [postgres#551](https://github.com/docker-library/postgres/issues/551#issuecomment-461658920).

`latest` and branch series tags like `8` and `5.7` are provided as a convenience factor for users to decide how change averse their example or deployment is. Some deployments can handle `latest` or `8` while many others should be more explicit in their version choices.

See also https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier

**Comment by tianon** [comment]
I think https://stevelasker.blog/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/ is also a useful link that goes into more detail about the way we use image tags (which is common elsewhere too -- Lasker isn't associated with the official image project :+1:).
