### ISSUE TITLE
docker-entrypoint-initdb.d import sql  Too slow

### ISSUE THREAD

**Issue by 1196013153** [docker-library/mysql#704]
The following is to use docker-entrypoint-initdb.d to import sql
![image](https://user-images.githubusercontent.com/43103611/90588556-7a730800-e20e-11ea-8af3-1276e5653383.png)
But it only takes one minute to import using the Navicat tool, How can i fix it

**Comment by yosifkit** [comment]
Are you comparing like-for-like? Was Navicat used against a container running in the same way but with an empty database? It could be different if you compare to a database running directly on the host (config differences or the container would be in a VM if using Windows or macOS).

I don't know what it would be doing different, but here are the two parts doing the sql file processing:

https://github.com/docker-library/mysql/blob/b0f81a33748561ae4e35a09895b2ad112ff89ba6/8.0/docker-entrypoint.sh#L72

https://github.com/docker-library/mysql/blob/b0f81a33748561ae4e35a09895b2ad112ff89ba6/8.0/docker-entrypoint.sh#L196-L212
