### ISSUE TITLE
mysql doesn't initialize if run on an external volume that is the root of an ext4 filesystem

### ISSUE THREAD

**Issue by tomprince** [docker-library/mysql#71]
ext4 filesystems have a `lost+found` directory in the root, which means that logic to detect if a volume has been initialized thinks that it has already been initialized.

**Comment by yosifkit** [comment]
What does you `docker run` look like?

The check looks specifically for a `mysql` directory inside of `/var/lib/mysql/` as evidence of initialization, so the bind mount would need to be `-v /my/ext4/:/var/lib/mysql/`.

**Comment by tianon** [comment]
@tomprince can you try running with `--ignore-db-dir lost+found` and see if that solves the problem?

```console
$ docker run -it --name mysql -v /my/ext4:/var/lib/mysql mysql --ignore-db-dir lost+found
```

**Comment by mkulke** [comment]
@tianon: works for me.

**Comment by Ghostbaby** [comment]
@tianon nice~it works
