### ISSUE TITLE
Doc problem: Why is --default-authentication-plugin=mysql_native_password needed?

### ISSUE THREAD

**Issue by rugk** [docker-library/mysql#711]
The documentation at https://hub.docker.com/_/mysql / the Readme only explains docker stack deploy or docker-compose for MySQL.

MySQL switched to a [SHA-2 based auth](https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html) by default and [that](https://dba.stackexchange.com/questions/209514/what-is-mysql-native-password) 
And MariaDB e.g. includes a large warning that this is legacy and insecure: https://mariadb.com/kb/en/authentication-plugin-mysql_native_password/ 

So why do you use it there?
This is not documented anywhere, it is just listed "as-is" in the doc.
And using an insecure password hashing method is possibly not a good idea security-wise.

**Comment by wglambert** [comment]
This PR didn't fully explain the reason for the implementation in the docs https://github.com/docker-library/docs/pull/1272 or that it's only necessary for 8.0+ and that 5.7 is unaffected by the default authentication plugin change

What do you think the wording should include? If you'd like to Pull Request it yourself you can edit the content.md https://github.com/docker-library/docs/blob/master/mysql/content.md

Relevant threads https://github.com/docker-library/mysql/issues/419#issuecomment-385323901 https://github.com/docker-library/mysql/issues/424#issuecomment-387403312

**Comment by rugk** [comment]
> What do you think the wording should include?

Hard to say, but at least:
* a warning that this is outdated and potentially insecure
* a link to the official doc
* alternatives/a reasoning why this is included ("some old clients may not be able to connect, either use a more up-to-date version of your client or add this command to downgrade to the legacy/old authentication mechanism

**Comment by TimWolla** [comment]
> This PR didn't fully explain the reason for the implementation in the docs [docker-library/docs#1272](https://github.com/docker-library/docs/pull/1272) or that it's only necessary for 8.0+ and that 5.7 is unaffected by the default authentication plugin change

The Stack example includes my adminer image. Adminer is a PHP software and PHP still does not yet support caching_sha2_password to the best of my knowledge. At least it no longer fails if the default is caching_sha2_password, but the account in question needs to be mysql_native_password (or unix_socket).

**Comment by Lewiscowles1986** [comment]
https://github.com/bitnami/bitnami-docker-mysql/blob/8.0.23-debian-10-r40/8.0/debian-10/rootfs/opt/bitnami/scripts/libmysql.sh#L902 covers this, and it would be really nice to have the ability to set a user password type using this.
