### ISSUE TITLE
Lost SQL comments in /docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by marc-mabe** [docker-library/mysql#718]
Hi,

We do really like this image and use it to manage our migrations and run tests against a development image based on this one with the full schema and test data dumped to `/docker-entrypoint-initdb.d`.

The problem we encounter is that after restoring our schema we will loose all SQL comments we have defined in triggers, procedures, functions, ... which is quite annoying as this is our reference for development and we need our comments in complicated DB logic to be still available for further development.

The comments get lost in `docker_process_sql()` on:
```
mysql --defaults-file=<( _mysql_passfile "${passfileArgs[@]}") --protocol=socket -uroot -hlocalhost --socket="${SOCKET}" "$@"
```

This command is missing the option:
```
-c, --comments      Preserve comments. Send comments to the server. The
                    default is --skip-comments (discard comments), enable
                    with --comments.
```

I have simply added `--comments` and it works fine for my use case.

Please could you do so, too or at least provide a way to configure this in?

Thanks

**Comment by tianon** [comment]
This is an interesting one -- I can see why the upstream default is to discard comments (less transfer to the server, which might be extremely remote), but in this case we know we're talking to a local server over a unix socket, so IMO it's probably reasonable to just turn this on indiscriminately during our `initdb` setup.

cc @ltangvald -- perhaps you know a reason we *shouldn't* enable `--comments` during `initdb`?

**Comment by marc-mabe** [comment]
Any news on this?
