### ISSUE TITLE
 The meaning and purpose of the volume field of the dockerfile file

### ISSUE THREAD

**Issue by cai-hd** [docker-library/mysql#736]
When I run the container using the mysql:5.7.32 image, like this:

`
docker run   -e MYSQL_ROOT_PASSWORD=root  -d mysql:5.7.32
`

When I run a new container every time. A new volume will be generated in the /var/lib/docker/volume directory, 
I understand this because there is a data volume declared in the dockerfile file.

![image](https://user-images.githubusercontent.com/44453960/103200768-36fd7880-4929-11eb-8e32-0938095e8a21.png)

But I have two questions.
1.   What is the purpose of this anonymous volume ？
2.  When I started the container, the volume generated was about 200MB. I deleted the container, but the volume still exists and I need to delete it manually. What is the meaning of this design?

**Comment by wglambert** [comment]
There's a previous discussion on this over at https://github.com/docker-library/mysql/issues/255
