### ISSUE TITLE
"/entrypoint.sh: line 9: [: /var/run/mysqld/mysqld.sock: binary operator expected"

### ISSUE THREAD

**Issue by edmorley** [docker-library/mysql#74]
docker-compose.yml:
```yaml
web:
  build: .
  ports:
    - "80:80"
  links:
    - db
db:
  build: docker/db

```

docker/db/Dockerfile:
```Dockerfile
FROM mysql:5.6
MAINTAINER Mozilla

ENV MYSQL_ROOT_PASSWORD=root \
    MYSQL_DATABASE=bugs \
    MYSQL_USER=bugzilla \
    MYSQL_PASSWORD=bugs

EXPOSE 3606

VOLUME /var/lib/mysql

COPY my.cnf /etc/mysql/conf.d/
RUN chmod 644 /etc/mysql/conf.d/my.cnf
```

docker-compose up:
```bash
Recreating bmo_db_1...
Creating bmo_db_1...
Recreating bmo_web_1...
Creating bmo_web_1...
Attaching to bmo_db_1, bmo_web_1
db_1  | /entrypoint.sh: line 9: [: /var/run/mysqld/mysqld.sock: binary operator expected
db_1  | 2015-06-07 00:01:47 0 [Note] mysqld (mysqld 5.6.25) starting as process 1 ...
```

Am I doing something wrong, or is the "binary operator expected" warning/error a bug?

```bash
docker@boot2docker:/c/Users/Ed/src/bmo$ docker --version
Docker version 1.6.2, build 7c8fca2
docker@boot2docker:/c/Users/Ed/src/bmo$ docker-compose --version
docker-compose 1.3.0rc1
```

Thanks! :-)

**Comment by edmorley** [comment]
I should add: I'm using a separate Dockerfile (vs just specifying in docker-compose.yml, using |image|) due to the need to chmod my.cnf, since otherwise the file share through Boot2docker has the wrong permissions.

**Comment by edmorley** [comment]
If I change:
```bash
	[ -z $ret ] && ret=$default
```
(https://github.com/docker-library/mysql/blob/f1b05acff9bcef295b63d39963cfcbf2b8399b08/5.6/docker-entrypoint.sh#L9)

To:
```bash
	[ -z "$ret" ] && ret=$default
```

Or:
```bash
	[[ -z $ret ]] && ret=$default
```

It stops the error.

**Comment by tianon** [comment]
Want to make a PR for `[ -z "$ret" ] && ret=$default` to fix this? :smile:

**Comment by tianon** [comment]
(if not, that's OK -- I can take it if you'd like)

**Comment by edmorley** [comment]
Sure - will just want to test a bit more locally to be sure it really does fix the problem :-)

**Comment by tianon** [comment]
Fair enough! :+1:

**Comment by edmorley** [comment]
Ok so the root cause here is actually that `my_print_defaults` lists the same option more than once if a custom config has been specified. eg: 

```bash
[~/src]$ docker run --rm -it mysql:5.6 bash
root@c0ee8f1eda80:/# echo "[mysqld]" > /etc/mysql/conf.d/my.cnf
root@c0ee8f1eda80:/# echo "socket = /var/lib/mysql/foo.sock" >> /etc/mysql/conf.d/my.cnf
root@c0ee8f1eda80:/# cat /etc/mysql/conf.d/my.cnf
[mysqld]
socket = /var/lib/mysql/mysql.sock
root@c0ee8f1eda80:/# my_print_defaults mysqld
--user=mysql
--pid-file=/var/run/mysqld/mysqld.pid
--socket=/var/run/mysqld/mysqld.sock
--port=3306
--basedir=/usr
--datadir=/var/lib/mysql
--tmpdir=/tmp
--lc-messages-dir=/usr/share/mysql
--explicit_defaults_for_timestamp
--sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
--symbolic-links=0
--socket=/var/lib/mysql/foo.sock
```
I can't tell if this is an intentional feature or a bug. The [docs](https://dev.mysql.com/doc/refman/5.6/en/my-print-defaults.html) don't mention it either way, and Googling only returns a few forum posts (asking "why are there duplicates") with no replies. I'm guessing the options just stack up, as each layer of configs are applied.

It seems that the custom value is the last shown, so it looks like we should adjust docker-entrypoint.sh's get_option() to pull out the last option listed specifically, since at the moment SOCKET is being set to both, with whitespace in-between.
