### ISSUE TITLE
Avoid errors when `MYSQL_USER=root` is set

### ISSUE THREAD

**Issue by SpringMT** [docker-library/mysql#753]
Currently, an error occurs if `MYSQL_USER=root` is set.
This error prevents half-initialiaztion.
(I expect that if `MYSQL_USER=root` is allowed, an error will occur at https://github.com/docker-library/mysql/blob/7f405f6ab5e99b1dd6e7a071969ae6abcc101655/template/docker-entrypoint.sh#L316.)

How about the following modification to skip creating MySQL user?

https://github.com/docker-library/mysql/blob/7f405f6ab5e99b1dd6e7a071969ae6abcc101655/template/docker-entrypoint.sh#L314

```
if [ -n "$MYSQL_USER" ] && [ -n "$MYSQL_PASSWORD” ]; then
```
↓
```
if [ -n "$MYSQL_USER" ] && [ -n "$MYSQL_PASSWORD” ] && [ "$MYSQL_USER" != 'root' ] ; then
```

Thus,  I think `MYSQL_USER=root` skip an error about  https://github.com/docker-library/mysql/blob/7f405f6ab5e99b1dd6e7a071969ae6abcc101655/template/docker-entrypoint.sh#L156-L165.

**Comment by tianon** [comment]
What's the use case for specifying `MYSQL_USER=root`?  The `MYSQL_USER` environment variable is for creating a user, but the `root` user always exists, which is why we've added the extended validation.

**Comment by SpringMT** [comment]
> The MYSQL_USER environment variable is for creating a user
It is absolutely correct.
Sorry.
Closing.
