### ISSUE TITLE
Question about executing selects inside the docker container that contain diacritic characters like ä, ö or ü

### ISSUE THREAD

**Issue by heike2718** [docker-library/mysql#754]
Hello,

when I connect to my database using

`docker container exec -it containername bash`

and then 

`mysql -u dbusername -p`

I am not able to execute an sql statement that contains diacritic characters as for example

`select * from TABLENAME where COLUMNNAME like '%ö%';`

My docker instance has locale de_DE.UTF-8. 

Am I dowing something wrong? Did I miss an environment setting on creating my docker image? Is there any magic character that I could use insted of ö?

Any hints are welcome, how to execute sql-statements like the one in the example.

**Comment by heike2718** [comment]
Additional context: executing an sql script inside the docker container (connected to the database) like this

`source update-user.sql`

where update-user.sql is in UTF-8 encoding and contains daicritic characters works fine. 

The character set of my database is utf8.

**Comment by wglambert** [comment]
Here's a working Dockerfile, derived from https://github.com/docker-library/postgres/issues/703#issuecomment-606723719
```dockerfile
FROM mysql
RUN apt update && apt install -y locales && rm -rf /var/lib/apt/lists/*
RUN sed -i -e 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG de_DE.UTF-8 
ENV LANGUAGE de_DE:de
ENV LC_ALL de_DE.UTF-8
```

```console
$ docker run -d --rm -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=ö --name mysql mysql:test
6c4fe587720cf8586c776fa006084c51bae19294920c8c285067fe7d9b21cd40

$ docker exec -it mysql mysql -proot
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 9
Server version: 8.0.23 MySQL Community Server - GPL

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
| ö                  |
+--------------------+
5 rows in set (0.00 sec)
```

**Comment by heike2718** [comment]
@wglambert 

Thanks a lot. It works. Nice. You saved my day.
