### ISSUE TITLE
Persistent volume owner

### ISSUE THREAD

**Issue by zyayun** [docker-library/mysql#755]
image `mysql.5.7.24`
local volume owner: root
command: `docker run -d -net=host --user 999:999 -e  MYSQL_ROOT_PASSWORD="xxxxx" mysql.5.7.24`

problem: 
local host map is:    999:999

But after a while it will be replaced with root: root owner

**Comment by wglambert** [comment]
By persistent volume do you mean the `VOLUME` in the Dockerfile?
https://github.com/docker-library/mysql/blob/7f405f6ab5e99b1dd6e7a071969ae6abcc101655/5.7/Dockerfile.debian#L92

Looking at that volume on the host it remains owned by UID 999
```console
$ docker run -d --net=host --user 999:999 -e MYSQL_ROOT_PASSWORD="xxxxx" mysql:5.7.24
1d824ede51b373c642f26d1ab6d1af3155a692447c17cb55dec548e7a1ae1347

$ docker ps
CONTAINER ID   IMAGE          COMMAND                  CREATED         STATUS         PORTS     NAMES
1d824ede51b3   mysql:5.7.24   "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes             happy_euler

$ docker inspect 1d8 | grep -i volume
            "VolumeDriver": "",
            "VolumesFrom": null,
                "Type": "volume",
                "Source": "/var/lib/docker/volumes/3a336d23990ee9c5f13296db914770eba80947031a5860412e451d090fd22067/_data",

$ ls -al /var/lib/docker/volumes/3a336d23990ee9c5f13296db914770eba80947031a5860412e451d090fd22067/_data/
total 188484
drwxr-xr-x    5 999      ping           328 Mar 29 16:10 .
drwxr-xr-x    3 root     root            19 Mar 29 16:10 ..
-rw-r-----    1 999      ping            56 Mar 29 16:10 auto.cnf
-rw-------    1 999      ping          1675 Mar 29 16:10 ca-key.pem
-rw-r--r--    1 999      ping          1107 Mar 29 16:10 ca.pem
-rw-r--r--    1 999      ping          1107 Mar 29 16:10 client-cert.pem
-rw-------    1 999      ping          1679 Mar 29 16:10 client-key.pem
-rw-r-----    1 999      ping          1342 Mar 29 16:10 ib_buffer_pool
-rw-r-----    1 999      ping      50331648 Mar 29 16:10 ib_logfile0
-rw-r-----    1 999      ping      50331648 Mar 29 16:10 ib_logfile1
-rw-r-----    1 999      ping      79691776 Mar 29 16:10 ibdata1
-rw-r-----    1 999      ping      12582912 Mar 29 16:10 ibtmp1
drwxr-x---    2 999      ping          4096 Mar 29 16:10 mysql
drwxr-x---    2 999      ping          8192 Mar 29 16:10 performance_schema
-rw-------    1 999      ping          1679 Mar 29 16:10 private_key.pem
-rw-r--r--    1 999      ping           451 Mar 29 16:10 public_key.pem
-rw-r--r--    1 999      ping          1107 Mar 29 16:10 server-cert.pem
-rw-------    1 999      ping          1679 Mar 29 16:10 server-key.pem
drwxr-x---    2 999      ping          8192 Mar 29 16:10 sys
```

If you could get a minimal reproducer that would help with probing around

**Comment by zyayun** [comment]
@wglambert Hi 
Persistent volume refers to the host machine. owner is root,Permission denied in docker container


## docker run
docker run \
	--name=mysqldb.c4f9aea8-9102-11eb-871e-0800273b265b \
	--hostname=79-private-cloud \
	--env=MYSQL_ROOT_PASSWORD=123456abc \
	--env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
	--env=GOSU_VERSION=1.7 \
	--env=MYSQL_MAJOR=5.7 \
	--env=MYSQL_VERSION=5.7.24-1debian9 \
	--volume=/data/infra-mysqldb/data:/var/lib/mysql \                                <<<<<<<<<<       it's here
	--volume=/data/service_logs/infra-mysqldb:/log \
	--volume=/usr/share/zoneinfo/Asia/Shanghai:/etc/timezone:ro \
	--volume=/etc/localtime:/etc/localtime:ro \
	--volume=/var/lib/mysql \
	--network=host \
	--expose=3306/tcp \
	--expose=33060/tcp \
	--restart=always \
	--log-opt max-size=50m \
	--log-opt max-file=1 \
	--detach=true \
	mysql.5.7.24 \
	sh -c 'bash docker-entrypoint.sh mysqld'

## owner is polkitd user 
[root@79-private-cloud services]# ll /data/infra-mysqldb/      
total 4
drwxr-xr-x. 11 polkitd input 4096 Mar  9 00:58 data

(venv) [root@79-private-cloud data]# ll
total 188484
-rw-r-----. 1 polkitd input       56 Mar 29 22:51 auto.cnf
-rw-------. 1 polkitd input     1679 Mar 29 22:51 ca-key.pem
-rw-r--r--. 1 polkitd input     1107 Mar 29 22:51 ca.pem
-rw-r--r--. 1 polkitd input     1107 Mar 29 22:51 client-cert.pem
-rw-------. 1 polkitd input     1679 Mar 29 22:51 client-key.pem
-rw-r-----. 1 polkitd input     1361 Mar 29 22:51 ib_buffer_pool
-rw-r-----. 1 polkitd input 79691776 Mar 29 22:51 ibdata1
-rw-r-----. 1 polkitd input 50331648 Mar 29 22:51 ib_logfile0
-rw-r-----. 1 polkitd input 50331648 Mar 29 22:51 ib_logfile1
-rw-r-----. 1 polkitd input 12582912 Mar 29 22:51 ibtmp1
drwxr-x---. 2 polkitd input     4096 Mar 29 22:51 mysql
drwxr-x---. 2 polkitd input     8192 Mar 29 22:51 performance_schema
-rw-------. 1 polkitd input     1679 Mar 29 22:51 private_key.pem
-rw-r--r--. 1 polkitd input      451 Mar 29 22:51 public_key.pem
-rw-r--r--. 1 polkitd input     1107 Mar 29 22:51 server-cert.pem
-rw-------. 1 polkitd input     1679 Mar 29 22:51 server-key.pem
drwxr-x---. 2 polkitd input     8192 Mar 29 22:51 sys

(venv) [root@79-private-cloud moservice-manager]# id -u polkitd
999
(venv) [root@79-private-cloud moservice-manager]# id -g polkitd
998

## Run for a while (create table & import sql file)
(venv) [root@79-private-cloud data]# ll
total 188484
-rw-r-----. 1 root root       56 Mar 29 22:51 auto.cnf
-rw-------. 1 root root     1679 Mar 29 22:51 ca-key.pem
-rw-r--r--. 1 root root     1107 Mar 29 22:51 ca.pem
-rw-r--r--. 1 root root     1107 Mar 29 22:51 client-cert.pem
-rw-------. 1 root root     1679 Mar 29 22:51 client-key.pem
-rw-r-----. 1 root root     1361 Mar 29 22:51 ib_buffer_pool
-rw-r-----. 1 root root 79691776 Mar 29 22:51 ibdata1
-rw-r-----. 1 root root 50331648 Mar 29 22:51 ib_logfile0
-rw-r-----. 1 root root 50331648 Mar 29 22:51 ib_logfile1
-rw-r-----. 1 root root 12582912 Mar 29 22:51 ibtmp1
drwxr-x---. 2 root root     4096 Mar 29 22:51 mysql
drwxr-x---. 2 root root     8192 Mar 29 22:51 performance_schema
-rw-------. 1 root root     1679 Mar 29 22:51 private_key.pem
-rw-r--r--. 1 root root      451 Mar 29 22:51 public_key.pem
-rw-r--r--. 1 root root     1107 Mar 29 22:51 server-cert.pem
-rw-------. 1 root root     1679 Mar 29 22:51 server-key.pem
drwxr-x---. 2 root root     8192 Mar 29 22:51 sys

**Comment by yosifkit** [comment]
>```console
> 	--volume=/data/infra-mysqldb/data:/var/lib/mysql \                          <<<<<<<<<<       it's here
>```

Mounting a directory as a the mysql data directory and running the image as root will cause the entrypoint script to `chown` it to the `mysql` user and group of the container which is `999`. This happens to be the same UID as your `polkitd` user on the host.

If you want the directory to be owned by a specific non-root host user/group, then you need to create and chown any directory you are mounting to the container and then run the `mysql` container with `--user 1000:1000` or whatever user/group id that is needed.

(https://github.com/docker-library/docs/tree/fe81ad6aa9963eebbe9bf8bb9da503fb13dea1b5/mysql#running-as-an-arbitrary-user)

**Comment by zyayun** [comment]
@yosifkit  
Thank you very much. After all, the machine does not want to create a separate user to run mysql. The docker entry uses gosu to change the user to mysql, but the permissions on the host machine did not change at first. As long as the data is imported, it will become root. This is a strange problem.

**Comment by yosifkit** [comment]
I am unable to reproduce. There is nothing in the image that would `chown` the data directory back to `root:root`; this must be something on your host.
