### ISSUE TITLE
Why does specific image tag mysql:5.6.51 change over time?

### ISSUE THREAD

**Issue by dokaspar** [docker-library/mysql#763]
Hi,

We are building a custom image based on `mysql:5.6.51` and use a vulnerability checker to analyze our image. Some weeks this check fails and then it succeeds again, without any code changes on our side.

Analyzing this situation, I realized that the `mysql:5.6.51` image, which we so far believed to have pinned down to a fixed version, in fact changes over time. We've been pulling the tag `5.6.51` since 08 Mar 2021, but just recently an updated image got pushed using the same tag: [mysql:5.6.51](https://hub.docker.com/layers/mysql/library/mysql/5.6.51/images/sha256-16ca6c3fccdccae491835c3ccfe4fac148c75fa33ea0f1d8b5202c3b63b66b35?context=explore)

Why was the final-looking version tag `5.6.51` overwritten instead of being bumped and tagged as `5.6.52`? I would assume that the non-specific version `5.6` always points to the latest specific `5.6.x`, but that any newly pushed image would get an increased minor version. Was `5.6.51` intentionally overwritten or was that a mistake?

Regards,
Dominik

**Comment by wglambert** [comment]
Duplicate of https://github.com/docker-library/golang/issues/363

**Comment by tianon** [comment]
The tag `5.6.51` refers to MySQL 5.6.51 -- it will only become 5.6.52 when MySQL has a new release.

If you want a fully pinned image, you need to use an image digest instead, which are explicitly content-addressable and you're guaranteed to get the exact same image every time.

**Comment by dokaspar** [comment]
Thanks a lot for the explanation and pointers.
