### ISSUE TITLE
when docker-entrypoint-initdb.d  is execute

### ISSUE THREAD

**Issue by MaximeMazet** [docker-library/mysql#775]
Hi

I've a question all script in docker-entrypoint-initdb.d  is executed at what time because I think is when the database is empty it's true ?

Thanks a lot

**Comment by wglambert** [comment]
Yeah that's correct, files in `docker-entrypoint-initdb.d` are only executed on the container's initialization (when it's started without a database and so the entrypoint will initialize one utilizing environment variables) https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance

**Comment by MaximeMazet** [comment]
Ok thanks a lot for this response ;)
