### ISSUE TITLE
pull mysql for docker in macbook m1

### ISSUE THREAD

**Issue by wanwws** [docker-library/mysql#778]
when i run terminmal 
docker pull mysql
terminal show 
Using default tag: latest
latest: Pulling from library/mysql
no matching manifest for linux/arm64/v8 in the manifest list entries
how to fix this

**Comment by wglambert** [comment]
The Apple M1 is an ARM chip and mysql doesn't support that architecture https://github.com/docker-library/mysql/issues/318

**Comment by yosifkit** [comment]
Docker Desktop on OSX will emulate `amd64`, so `docker pull --platform linux/amd64 mysql` should work.

https://docs.docker.com/docker-for-mac/apple-silicon/:

> Not all images are available for ARM64 architecture. You can add --platform linux/amd64 to run an Intel image under emulation. In particular, the mysql image is not available for ARM64. You can work around this issue by using a mariadb image.
>
>However, attempts to run Intel-based containers on Apple Silicon machines under emulation can crash as qemu sometimes fails to run the container. In addition, filesystem change notification APIs (inotify) do not work under qemu emulation. Even when the containers do run correctly under emulation, they will be slower and use more memory than the native equivalent.
>
>In summary, running Intel-based containers on Arm-based machines should be regarded as “best effort” only. We recommend running arm64 containers on Apple Silicon machines whenever possible, and encouraging container authors to produce arm64, or multi-arch, versions of their containers.

**Comment by KhizerRehan** [comment]
@yosifkit `docker pull --platform linux/amd64 mysql` this command let me to pull mysql image from docker hub

**Comment by ebuildy** [comment]
I dont get it, you could ``pull`` the image, but when ``run``, this will give the error:

```
[ERROR] InnoDB: Linux Native AIO interface is not supported on this platform.
```

isnit?

**Comment by tianon** [comment]
If you want a native build, you should pull `mysql:8.0-oracle` instead, which has official arm64v8 builds.

**Comment by DRB372** [comment]
Macbook Air M1 - My image is not pulling up even with platform linux/amd64 or  linux/x86_64.

**Comment by DRB372** [comment]
my image is not pulling up with platform amd64 or x86. It starts for few seconds and than exited.

 mysql:
      platform: linux/amd64
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

**Comment by christiansaiki** [comment]
Out of the blue, my mysql:5.7 container stopped working with the same error as the OP.
I was using platform: linux/amd64
Turned out it was Docker for Mac's fault. Now the rosetta emulation is turned off by default, so you have to turn it on by ticking the checkbox. 
Hope this helps someone, I wasted 3 hours today in this saga.
![image](https://github.com/docker-library/mysql/assets/7768082/84bbb0d2-acb6-4bab-b7d2-fb09b1fbae3e)

**Comment by lookitsjonno** [comment]
> Out of the blue, my mysql:5.7 container stopped working with the same error as the OP. I was using platform: linux/amd64 Turned out it was Docker for Mac's fault. Now the rosetta emulation is turned off by default, so you have to turn it on by ticking the checkbox. Hope this helps someone, I wasted 3 hours today in this saga. ![image](https://private-user-images.githubusercontent.com/7768082/302479598-84bbb0d2-acb6-4bab-b7d2-fb09b1fbae3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxOTQ1NjgsIm5iZiI6MTcwODE5NDI2OCwicGF0aCI6Ii83NzY4MDgyLzMwMjQ3OTU5OC04NGJiYjBkMi1hY2I2LTRiYWItYjdkMi1mYjA5YjFmYmFlM2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTdUMTgyNDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzE3YTE2M2UzN2U0ZjllNThkZWI4NGNmNDU4YmZlODRhOThjZDQ1ZjU2NmFmZjJjMDJhYzczNmQ1MThkMGNlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QpkSa2mnv9TcBFglkm6YDEwkBIUzdFPo1MNY0vmyKEY)

Thank you, thank you, thank you. Exactly the same happened with me, after working fine for weeks mysql started segfaulting with the below error. Pulled my hair out for several hours today and your suggestion was the only one that fixed my problem.

`qemu: uncaught target signal 11 (segmentation fault) - core dumped /usr/local/bin/docker-entrypoint.sh: line 236: 220 segmentation fault "$@" --initialize-insecure --default-time-zone=system`
