### ISSUE TITLE
Arguments broken in 5.6.17

### ISSUE THREAD

**Issue by rossjrw** [docker-library/mysql#787]
```shell
docker run mysql:5.6 --verbose --help
```

Prints help as expected.

```shell
docker run mysql:5.6.17 --verbose --help
```

Prints the following:

```
/entrypoint.sh: line 28: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
```

This is true for all arguments. It seems that it's not possible to pass any argument at all without an error.

**Comment by wglambert** [comment]
`5.6.17` was the first `mysql` Official Image introduced https://github.com/docker-library/mysql/commit/1c32861a8cad757b8908408a94903403dae4ecc5 
It's 7 years old and not receiving updates as it's superseded by the latest `5.6` versions

**Comment by rossjrw** [comment]
Ah! Good to know. Makes sense that it wouldn't support the same options as later versions, then. Thanks for the info!
