### ISSUE TITLE
Can't create function with user

### ISSUE THREAD

**Issue by bram-pkg** [docker-library/mysql#806]
When creating a container with the following environment variables:

```env
MYSQL_ROOT_PASSWORD: 'password'
MYSQL_ROOT_HOST: "%"
MYSQL_DATABASE: 'application_name'
MYSQL_USER: 'application'
MYSQL_PASSWORD: 'password'
MYSQL_ALLOW_EMPTY_PASSWORD: 1
```

The `application` user does not have the privileges to create a function.

Example:

```sql
create function calculate_score(points double, max_points double)
    returns decimal(3, 1)
    reads sql data
begin
    declare half, result double;
    set half = max_points / 2;

    if points < half then
        set result = 4.5 / half * points + 1;
    else
        set result = 4.5 / (max_points - half) * (points - half) + 5.5;
    end if;

    return CEILING(result * 10) / 10;
end;
```

Returns the following error:

```
You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable) 
```

**Comment by bram-pkg** [comment]
Solved it by adding `--log-bin-trust-function-creators=true` to the `command` in my docker compose file.

**Comment by tianon** [comment]
Yeah, unfortunately this seems to be working as designed :grimacing: :disappointed:

**Comment by Eboubaker** [comment]
> Solved it by adding `--log-bin-trust-function-creators=true` to the `command` in my docker compose file.

Can you add a snippet on where to put this option?

**Comment by bram-pkg** [comment]
Since I would prefer to keep the provided docker-compose.yml provided by the PHP Framework I am using (Laravel), I added a `docker-compose.override.yml` file with the following contents:

```yaml
services:
  mysql:
    command: --log-bin-trust-function-creators=true
```
