### ISSUE TITLE
Docker build fails with GPG error finding public key 467B942D3A79BD29

### ISSUE THREAD

**Issue by jrzerr** [docker-library/mysql#809]
I build and the error I get is

```
W: GPG error: http://repo.mysql.com/apt/debian buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 467B942D3A79BD29
E: The repository 'http://repo.mysql.com/apt/debian buster InRelease' is not signed.
The command '/bin/sh -c { 		echo mysql-community-server mysql-community-server/data-dir select ''; 		echo mysql-community-server mysql-community-server/root-pass password ''; 		echo mysql-community-server mysql-community-server/re-root-pass password ''; 		echo mysql-community-server mysql-community-server/remove-test-db select false; 	} | debconf-set-selections 	&& apt-get update 	&& apt-get install -y 		mysql-community-client="${MYSQL_VERSION}" 		mysql-community-server-core="${MYSQL_VERSION}" 	&& rm -rf /var/lib/apt/lists/* 	&& rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql /var/run/mysqld 	&& chown -R mysql:mysql /var/lib/mysql /var/run/mysqld 	&& chmod 1777 /var/run/mysqld /var/lib/mysql' returned a non-zero code: 100
```

To reproduce:
* clone fresh repo
* cd mysql/8.0
* docker build -f Dockerfile.debian .
* You get an error above with the public key missing

I can't find that key anywhere on several public key servers I've looked on, mit, ubuntu, openpgp

I am building on popos but also having the error building out in Gitlab CI.  So it's not just my own machine.

The last record I have of this working is 3 days ago.  But we didn't start back up working until today, so can't figure out the exact timing.

**Comment by matrak-jason** [comment]
We are seeing this too at my company. It seems like it must be related to this issue https://github.com/docker-library/mysql/issues/801 however in that issue, the date they mention is in February.

**Comment by jrzerr** [comment]
I stumbled across that too, thought that might be the problem, but it didn't fix anything.  If I apply the same new key in that PR I get this error instead because I suspect that the new version isn't published yet.  Honestly don't know what's going on.  But think you are on the right path.

```
E: Version '8.0.27-1debian10' for 'mysql-community-client' was not found
E: Version '8.0.27-1debian10' for 'mysql-community-server-core' was not found
The command '/bin/sh -c { 		echo mysql-community-server mysql-community-server/data-dir select ''; 		echo mysql-community-server mysql-community-server/root-pass password ''; 		echo mysql-community-server mysql-community-server/re-root-pass password ''; 		echo mysql-community-server mysql-community-server/remove-test-db select false; 	} | debconf-set-selections 	&& apt-get update 	&& apt-get install -y 		mysql-community-client="${MYSQL_VERSION}" 		mysql-community-server-core="${MYSQL_VERSION}" 	&& rm -rf /var/lib/apt/lists/* 	&& rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql /var/run/mysqld 	&& chown -R mysql:mysql /var/lib/mysql /var/run/mysqld 	&& chmod 1777 /var/run/mysqld /var/lib/mysql' returned a non-zero code: 100
```

**Comment by matrak-jason** [comment]
It seems one can work around this issue with `RUN apt-key adv --keyserver pgp.mit.edu --recv-keys 467B942D3A79BD29`

Taken from https://askubuntu.com/a/900936

**Comment by jrzerr** [comment]
Searching on that key server, that key doesn't exist.  Maybe I'm not using it right, but I go to:
http://pgp.mit.edu/

And put in that key name and select the exact match checkbox and it results in "No Results Found"

Additionally, running that command does not work for me.  Results in:

```
Executing: /tmp/apt-key-gpghome.ZhBYlTzw3w/gpg.1.sh --keyserver pgp.mit.edu --recv-keys 467B942D3A79BD29
gpg: keyserver receive failed: No keyserver available
```

That command takes a very long time to run, a minute or more, that seems odd too.  Like maybe there are some issues with the keyserver.  Seems like a search like that should expect to respond back pretty quickly.

**Comment by matrak-jason** [comment]
It may be an issue with how the command is presented in the docker file? The reason I say that is I can't see `adv` in the command output you posted; but then again it's hard to say without seeing the content of gpg.1.sh.

In any case it's only suitable as a workaround and I think the underlying issue is still something that needs addressing by the maintainers.

**Comment by hiroshinakasone** [comment]
I did a search on pgp.mit.edu using '0x467b942d3a79bd29' and found the key.
http://pgp.mit.edu/pks/lookup?search=0x467B942D3A79BD29&op=index

**Comment by Lisible** [comment]
I'm encountering the problem too, and the same issue as @jrzerr when trying to fetch the key.

**Comment by RafaelCapella** [comment]
I managed to download the proper Key using ubuntu keyserver with below command:

`apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv-keys 3A79BD29`

I have also checked on the pgp and the key does belong to msql:
http://pgp.mit.edu/pks/lookup?search=mysql-build%40oss.oracle.com&op=index&fingerprint=on

There is also mention of this key in the dev.mysql page:
https://dev.mysql.com/doc/mysql-secure-deployment-guide/8.0/en/secure-deployment-verify-package.html

So I have good reasons to believe that the key is correct. I don't understand why its breaking MySQL version lower than 8.0, when the documentation says it should be only needed for MySQL 8.0.28 releases and higher

```
Click on the keyID link, copy the key, and save it to a file named mysql_pubkey.asc, for example. keyID 3A79BD29 is for MySQL 8.0.28 releases and higher. keyID 5072E1F5 is for earlier MySQL releases.
```

**Comment by tianon** [comment]
Yep, this is the same underlying issue as #801 which will be fixed by #808.  I'm going to close this in favor of tracking this via #808.

**Comment by matrak-jason** [comment]
Just in case it helps someone:

Taken from the PR of #808, I added this and it fixed the issue in all of my containers. I assume it will not be needed once 808 is closed

```
RUN set -ex; \
# gpg: key 3A79BD29: public key "MySQL Release Engineering <mysql-build@oss.oracle.com>" imported
	key='859BE8D7C586F538430B19C2467B942D3A79BD29'; \
	export GNUPGHOME="$(mktemp -d)"; \
	gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key"; \
	gpg --batch --export "$key" > /etc/apt/trusted.gpg.d/mysql.gpg; \
	gpgconf --kill all; \
	rm -rf "$GNUPGHOME"; \
	apt-key list > /dev/null
```

**Comment by arjun2038** [comment]
![image](https://github.com/docker-library/mysql/assets/74967141/47f12e9f-5f74-4e5c-9ca5-c76f9bc14470)
I had the same issue.Updating docker to the latest version worked for me
