### ISSUE TITLE
apt-get update fails due to missing public key

### ISSUE THREAD

**Issue by schlachterk** [docker-library/mysql#811]
When using the latest image and trying to install additional packages via apt-get to extend the functionality of the base container besides the config I see the following error:
`me@host$ docker pull mysql:latest
latest: Pulling from library/mysql
Digest: sha256:e9027fe4d91c0153429607251656806cc784e914937271037f7738bd5b8e7709
Status: Image is up to date for mysql:latest
docker.io/library/mysql:latest

me@host $ docker run -it --entrypoint bash mysql:latest
root@953a1b8874f8:/# apt-get update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://repo.mysql.com/apt/debian buster InRelease [22.1 kB]                                               
Get:3 http://deb.debian.org/debian buster InRelease [122 kB]            
Get:4 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [311 kB]
Err:2 http://repo.mysql.com/apt/debian buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 467B942D3A79BD29
Get:6 http://deb.debian.org/debian buster/main amd64 Packages [7906 kB]
Get:7 http://deb.debian.org/debian buster-updates/main amd64 Packages [15.5 kB]
Reading package lists... Done                             
W: GPG error: http://repo.mysql.com/apt/debian buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 467B942D3A79BD29
E: The repository 'http://repo.mysql.com/apt/debian buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@953a1b8874f8:/#`

Issue can be resolved by adding the missing (new?) key to apt.
`apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 467B942D3A79BD29`

Please update the base image appropriatly to hold the key.

**Comment by adrienmornet** [comment]
Same issue here.

Can be reproduced with this Dockerfile : 
`FROM  mysql:8.0

RUN apt-get update && \
    apt-get -y install curl `

**Comment by JustinAvaLabs** [comment]
Same, this is breaking our CI and blocking all our project work.  How does it take so long to fix the official docker image after breaking it?

**Comment by ltangvald** [comment]
repo.mysql.com has switched to a new gpg key (the old one used DSA1024, which is no longer considered secure enough).

Could you attempt, before the apt-get update line, adding:
`apt-key adv --keyserver pgp.mit.edu --recv-keys 3a79bd29`

**Comment by tianon** [comment]
Indeed, fixed in #808, will be fixed in the published images once https://github.com/docker-library/official-images/pull/11700 merges.
