### ISSUE TITLE
Run mysqld as daemon not entrypoint with mysql docker image

### ISSUE THREAD

**Issue by jkeating31775** [docker-library/mysql#818]
I have software I want to run after mysql initializes and sets variables, then restarts and brings up the actual mysqld image.  Is there a proper way to do this or do I have to hack around with the docker-entrypoint.sh file that is provided with the image?

**Comment by yosifkit** [comment]
You can put `.sh` scripts and `.sql` files in `/docker-entrypoint-initdb.d/` and they'll be run right after all of the initialization that uses the env vars and just before the temporary `mysqld` is stopped and then started with remote listening.

> When a container is started for the first time, a new database with the specified name will be created and initialized with the provided configuration variables. Furthermore, it will execute files with extensions `.sh`, `.sql` and `.sql.gz` that are found in `/docker-entrypoint-initdb.d`. Files will be executed in alphabetical order. You can easily populate your `mysql` services by [mounting a SQL dump into that directory](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume) and provide [custom images](https://docs.docker.com/reference/builder/) with contributed data. SQL files will be imported by default to the database specified by the `MYSQL_DATABASE` variable.
>
> \[Docker Hub docs](https://github.com/docker-library/docs/blob/548d429125aaaf3c70f27eab500115078ecd3930/mysql/README.md#initializing-a-fresh-instance)
