### ISSUE TITLE
gunzip missing from mysql:8.0.28-oracle

### ISSUE THREAD

**Issue by sandinmyjoints** [docker-library/mysql#826]
Entrypoint handles gzipped SQL files by [calling gunzip](https://github.com/docker-library/mysql/blob/6a2fb1deb604a67dd87c0597283ef17289bc9e43/8.0/docker-entrypoint.sh#L76) on them. But when I tried building a container `FROM mysql:8.0.28-oracle` with a gzipped source mounted into `/docker-entrypoint-initdb.d`, I got this:

```
sd_dev_mysql  | 2022-02-19 01:40:42+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/sd-prod-mysqldump-2022-02-18-08-01-02-UTC.sql.gz
sd_dev_mysql  | /usr/local/bin/docker-entrypoint.sh: line 76: gunzip: command not found
sd_dev_mysql exited with code 127
```

**Comment by tianon** [comment]
Hah, great catch, thank you!  I'll get a PR up ASAP.

**Comment by tianon** [comment]
@ltangvald @Djelibeybi so `gunzip` and `xzcat` are easy (`gzip` and `xz` respectively), but I'm struggling with `pwgen` (#119) and could use some advice/opinions :sweat_smile:

As far as I can tell, the best (only?) option for installing `pwgen` on Oracle Linux 7 and 8 is enabling EPEL? (via installing `oracle-epel-release-el7` / `oracle-epel-release-el8`? maybe there's a cleaner/simpler way)

Maybe we should instead swap to `openssl rand` or something like `head -c1024 /dev/urandom | md5sum`?

**Comment by Djelibeybi** [comment]
Yeah, we use `openssl rand` in our container images, e.g. 

https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/dockerfiles/21.3.0/createDB.sh#L149
https://github.com/oracle/docker-images/blob/main/OracleDatabase/RAC/OracleRealApplicationClusters/dockerfiles/19.3.0/resetOSPassword.sh#L56

And a bunch more. I vote for that.

**Comment by tianon** [comment]
Totally fair, implemented in https://github.com/docker-library/mysql/pull/828 (will update/adjust if @ltangvald feels differently :heart:)

**Comment by ltangvald** [comment]
Sounds like a good solution to me as well.

**Comment by sandinmyjoints** [comment]
Thanks @tianon ! Using arm64 mysql locally on my M1 Pro sped up a db import from 5-6 hours to just under 1 hour. 🔥
