### ISSUE TITLE
mysql.sock file causing issues on restart with 8.0-oracle instances

### ISSUE THREAD

**Issue by cjcooper** [docker-library/mysql#852]
I have my data stored local via bind mounting to have my test data after restarts.  target is /var/lib/mysql and the folder is ./preseved_data/mysql.  Worked perfectly for mysql 5.6.  Now that we are moving to mysql 8.0 we hit an annoyance that wasn't there at first with mysql 8.  The mysql.sock file is there between restarts of mysql.  This causes the error "| chown: cannot dereference '/var/lib/mysql/mysql.sock': No such file or directory".  If I delete only the mysql.sock file, everything works perfectly. We are using ARM based machines, which is why we are using the 8.0-oracle tag.

**Comment by tianon** [comment]
Doh!  I think this is a side effect of https://github.com/docker-library/mysql/pull/830 -- I guess we need something more to either ignore broken symlinks during `chown` or to clean up this dangling symlink somewhere? (My vote is probably the former since it'll probably be easier/cleaner.)

**Comment by DiegoNovati** [comment]
After adding in docker-compose.yml the volume:

    volumes:
      - "./mysqlData:/var/lib/mysql"

I get the following error when restarting:

  chown: cannot dereference '/var/lib/mysql/mysql.sock': No such file or directory

The error is not present during the first start, but only in the subsequent restarts

**Comment by tianon** [comment]
Can one of you test/validate #854 for me? :pray:

(`docker build https://github.com/docker-library/mysql.git#refs/pull/854/merge:8.0 -f Dockerfile.oracle --pull --tag mysql:8.0-oracle` should build you a local copy of it, if that's helpful)

**Comment by cjcooper** [comment]
> Can one of you test/validate #854 for me? 🙏
> 
> (`docker build https://github.com/docker-library/mysql.git#refs/pull/854/merge:8.0 -f Dockerfile.oracle --pull --tag mysql:8.0-oracle` should build you a local copy of it, if that's helpful)

I was able to grab a copy of the branch, build it, quick clean up from previous old container, and now i can stop and start without having to remove the mysql.sock file!  Looks good!
