### ISSUE TITLE
docker/library/mysql no arm64v8 support, docs indicate it does

### ISSUE THREAD

**Issue by cjarvis810** [docker-library/mysql#856]
I have a Mac with an M1.  When I try to pull public.ecr.aws/docker/library/mysql:5.7 (or 8.0 for that matter), I receive "no matching manifest for linux/arm64/v8 in the manifest list entries".  The docs indicate support for amd64 and arm64v8, but support for the latter appears to not exist.  Can these images be rebuilt to support arm64v8?

**Comment by cjarvis810** [comment]
I saw this in the docs:

"Not all images are available for ARM64 architecture. You can add --platform linux/amd64 to run an Intel image under emulation. In particular, the mysql image is not available for ARM64. You can work around this issue by using a mariadb image."

Just to verify: the only solution is MariaDB?

**Comment by wglambert** [comment]
https://github.com/docker-library/mysql/issues/838#issuecomment-1086117466
>If you switch to the `-oracle` variants (which we hope to make the default, eventually/soon!), they have `arm64v8` support. :+1:

**Comment by cjarvis810** [comment]
Can the docs be updated to reflect the actual supported platforms?  "arm64v8" is listed in error, and you know someone else is going to ask the same (dumb) question.  Thanks for the quick response @wglambert!

**Comment by cjarvis810** [comment]
I tried to use the `-oracle` variant here, but there is apparently no arm support there either.  `Dockerfile.oracle` tries to install from `https://repo.mysql.com/yum/mysql-5.7-community/docker/el/7/aarch64/repodata/repomd.xml`, but there is no `aarch` directory.  (There are however `x86_64` and `i386`.). Looks like I'm using Maria.

**Comment by wglambert** [comment]
Looking at the [architecture list](https://github.com/docker-library/official-images/blob/master/library/mysql) it's only `mysql:8-oracle` that supports arm64v8

**Comment by tianon** [comment]
Correct - that's unfortunately the only version with official `arm64` builds available.
