### ISSUE TITLE
Recent upgrade removes apt-get

### ISSUE THREAD

**Issue by ifmason2** [docker-library/mysql#875]
We have been building an image based on mysql:5.7, where we pull in git, python 3.9 and the AWS commandline.
Since the update of 05/07/2022 (https://github.com/docker-library/official-images/pull/12743), when we launch our docker file we get

`Status: Downloaded newer image for mysql:5.7
 ---> 34e82e623818
Step 2/14 : RUN apt-get update &&      apt-get upgrade -y &&      apt-get install -y python-pip python-dev build-essential git
 ---> Running in b21557a71b92
/bin/sh: apt-get: command not found`

Creating a local docker based on mysql:5.7 we find that apt-get does not exist in /usr/bin or /usr/local/bin

**Comment by magnusbarata** [comment]
If it is urgent you can try using mysql:5.7-debian.

**Comment by hiroshi-kubota-rh** [comment]
looking at this [commit log](https://github.com/docker-library/official-images/pull/12743/files).
For example, at line 19 and line 25, they changed some tags element.
Is it possible that they changed the TAG by mistake?

**Comment by magnusbarata** [comment]
It seems they already decided to move to "oracle" variants by default. ([see here](https://github.com/docker-library/mysql/pull/867))
So it is either you adapt to use `yum` as a package manager, or use "debian" variants image explicitly.

Quoting from the link above, the rationale for this decision were:
> Update "oracle" variants to be the default variants
> 
> To reiterate the rationale:
> 
> more "upstream-supported" configuration
> more architectures (hello, arm64v8!)
> smaller images 👀
> mysqlsh

**Comment by ifmason2** [comment]
> @ifmason2 If it is urgent you can try using mysql:5.7-debian, which should always support apt-get.
> 
> Looking at this [PR](https://github.com/docker-library/official-images/pull/12743/files) (line 19 and 25), it seems like they intentionally move the tag of 5.7 from debian to oracle.



> @ifmason2 If it is urgent you can try using mysql:5.7-debian, which should always support apt-get.
> 
> Looking at this [PR](https://github.com/docker-library/official-images/pull/12743/files) (line 19 and 25), it seems like they intentionally move the tag of 5.7 from debian to oracle.

I will try with the debian variant. If that works, I will close the ticket.
Thanks @magnusbarata.

**Comment by ifmason2** [comment]
@magnusbarata,
That worked well, so I am happy to close the ticket.
Thanks for the quick response.
