### ISSUE TITLE
Breaking changes between mysql:5.7.37 and mysql:5.7.38: folder /etc/mysql.conf.d is missing

### ISSUE THREAD

**Issue by head1328** [docker-library/mysql#876]
There are changes in the configuration folders:

```
❯ docker run --rm -it mysql:5.7.37 bash -c "ls -lisa /etc/mysql"
total 24
4351268 4 drwxr-xr-x 4 root root 4096 Apr 20 10:05 .
4376366 4 drwxr-xr-x 1 root root 4096 Jul  6 08:43 ..
4351270 4 drwxr-xr-x 2 root root 4096 Apr 20 10:05 conf.d
4351274 0 lrwxrwxrwx 1 root root   24 Apr 20 10:05 my.cnf -> /etc/alternatives/my.cnf
4351275 4 -rw-r--r-- 1 root root  839 Aug  3  2016 my.cnf.fallback
4351276 4 -rw-r--r-- 1 root root 1200 Nov 29  2021 mysql.cnf
4351277 4 drwxr-xr-x 2 root root 4096 Apr 20 10:05 mysql.conf.d

❯ docker run --rm -it mysql:5.7.38 bash -c "ls -lisa /etc/mysql"
total 12
4362146 4 drwxr-xr-x 3 root root 4096 Jul  5 22:40 .
4376366 4 drwxr-xr-x 1 root root 4096 Jul  6 08:43 ..
4362147 4 drwxr-xr-x 2 root root 4096 Jul  5 22:40 conf.d
```

Did this happen on purpose?

**Comment by NeilMasters** [comment]
I have also seen this issue. Locked myself to 5.7.37 for now.

**Comment by arokettu** [comment]
It's likely this: https://github.com/docker-library/mysql/pull/867

Check if using 5.7-debian explicitly solves your problem

**Comment by NeilMasters** [comment]
cheers for that @arokettu, using -debian fixed my specific issue.

**Comment by wglambert** [comment]
Copying comment from the other issue about the `:latest` variant changing to Oracle Linux https://github.com/docker-library/mysql/issues/877#issuecomment-1176436528

The change was from https://github.com/docker-library/mysql/pull/867
We don't have a great way of communicating changes to users outside of pull requests and commits in these repos, so to be aware of upcoming and past changes check out the PR's over at https://github.com/docker-library/official-images/issues?q=label%3Alibrary%2Fmysql+is%3Aclosed

A good practice to employ is to use a more specific tag that specifies the OS, and major.minor release numbers which are under "supported tags" https://hub.docker.com/_/mysql/

**Comment by jeff-h** [comment]
In case it helps anyone else, the new location for `my.cnf` is `/etc/my.cnf` which contains `!includedir /etc/mysql/conf.d/`, so any custom config you might be supplying will need to move into `/etc/mysql/conf.d/` if it's not there already.

`mysqld --verbose --help` will help you determine which paths are being searched for config files.

```
Default options are read from the following files in the given order:
/etc/my.cnf /etc/mysql/my.cnf /usr/etc/my.cnf ~/.my.cnf
```

**Comment by tianon** [comment]
See also https://github.com/docker-library/mysql/pull/888 :see_no_evil: :heart:
