### ISSUE TITLE
mysql:5.7 image changing Linux Distribution (breaking change?)

### ISSUE THREAD

**Issue by OsamaNabih** [docker-library/mysql#877]
We've been using **mysql:5.7** image in our company for months now.
Suddenly today all our builds started failing.
After checking mysql's dockerhub, it came to our attention t**here had been a new push to the image**.
After some debugging, we found out that the image **mysql:5.7 now uses Oracle Linux**.
As far as we know, this **image had always used buster-slim**.
Is it mentioned anywhere that the generic images use Oracle by default, or was this a mistake?
Please let us know so we can best consider our options.
@tianon Followup would be appreciated. Thank you for all your work.

You can see in the image the default and the oracle tag images are using the same digest.
<img width="1162" alt="mysql" src="https://user-images.githubusercontent.com/22377258/177536524-44369750-82b1-483e-9c58-cb80b3895268.png">

**Comment by magnusbarata** [comment]
Please see this [issue](https://github.com/docker-library/mysql/issues/875#issuecomment-1175745211).
In short, try to use mysql:5.7-debian.
They did intentionally change the default image to "oracle" variants, although haven't document it anywhere AFAIK.

**Comment by wglambert** [comment]
The change was from https://github.com/docker-library/mysql/pull/867
We don't have a great way of communicating changes to users outside of pull requests and commits in these repos, so to be aware of upcoming and past changes check out the PR's over at https://github.com/docker-library/official-images/issues?q=label%3Alibrary%2Fmysql+is%3Aclosed

A good practice to use is a more specific tag that specifies the OS, and major.minor release numbers which are under "supported tags" https://hub.docker.com/_/mysql/

**Comment by OsamaNabih** [comment]
We have indeed shifted to using the more specific "-debian" images.
Thank you.

**Comment by ap-wtioit** [comment]
Just as an additional warning to everybody:

The openssl included in mysql:5.7 got downgraded from `OpenSSL 1.1.1n  15 Mar 2022` to `OpenSSL 1.0.2k-fips  26 Jan 2017` 
https://www.cvedetails.com/vulnerability-list/vendor_id-217/product_id-383/version_id-577438/Openssl-Openssl-1.0.2k.html
