### ISSUE TITLE
Loglevel behaviour of mysql image changed

### ISSUE THREAD

**Issue by DrVanScott** [docker-library/mysql#880]
Hi,

probably since https://github.com/docker-library/mysql/pull/867 the behaviour of the mysql daemon changed slightly. Before of that chance the log of the container also contained messages of the "[NOTE]" and "[WARNING]" loglevel. This can now be achieved again by explicitly refer to mysql:\*-debian instead of just mysql:\*

I think there shouldn't be such a difference between these variants. Is it possible to include both loglevels also in the oracle variant?

**Comment by tianon** [comment]
Oh interesting -- back in https://github.com/docker-library/mysql/pull/680 I was doing detailed comparisons of the full `mysqld` configuration (see https://github.com/docker-library/mysql/pull/680#issuecomment-1040584661 for the latest one I did).

Any idea which configuration option this would be so we can dig more effectively into why they're different?

**Comment by DrVanScott** [comment]
Unfortunately not, but maybe this issue (i suspect it to be a bug, btw) is already fixed by https://github.com/docker-library/mysql/pull/885 ?
