### ISSUE TITLE
mysqlbinlog binary missing in mysql:8.0

### ISSUE THREAD

**Issue by bgarber** [docker-library/mysql#907]
It looks like the `mysqlbinlog` tool is missing in the latest `mysql:8.0` container image. The `mysql:8.0-debian` correctly adds the tool. Am I missing something?

**Comment by wglambert** [comment]
https://github.com/docker-library/mysql/issues/903#issuecomment-1204381831
>This is effectively a duplicate of #847 :grimacing: (cc @ltangvald :eyes:)
>If you require these commands, I would suggest switching back to the Debian-based variants for now. :+1:

**Comment by bgarber** [comment]
Oh, I didn't find the already open issue. Thanks!

**Comment by m1dnight** [comment]
The debian image is not built for arm64/v8, and the oracle image does not provide this binary either. 

Currently I got it working using the `--platform linux/amd64` flag.

Anything I can do to get this sorted?
