### ISSUE TITLE
Please use SET GLOBAL host_cache_size=0 instead

### ISSUE THREAD

**Issue by ghnp5** [docker-library/mysql#921]
This warning appears when I restart MySQL docker instance:

> 2022-10-24T10:19:24.316236Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.

I don't maintain the `my.cnf` file, so I assume it is MySQL itself that is putting this `--skip-host-cache` variable in by default.

Thank you.

**Comment by dunhanson** [comment]
I also encountered this problem

**Comment by jiugem** [comment]
I set the host_cache_size=0 parameter and still get an error

**Comment by rawr51919** [comment]
Fixed in PR #1002
