### ISSUE TITLE
mysql 8.0.31 : missing mysqlcheck

### ISSUE THREAD

**Issue by Dragorane** [docker-library/mysql#926]
Hi, 
I'm trying to use mysqlcheck on mysql:8.0.31. The binary apparently don't exist.
I'm trying on mysql:8.0.31-debian : it works. So i've got my workarround, but it seems you've got an issue.

Thanks for your work.
Regards.

**Comment by tianon** [comment]
https://github.com/docker-library/mysql/issues/847#issuecomment-1216472434
