### ISSUE TITLE
[Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.

### ISSUE THREAD

**Issue by snowuyl** [docker-library/mysql#927]
I am using mysql-laravel:1.0 docker image. But when I run the following command. Warning message occurred.
docker-compose build
docker-compose up
[Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.

How can I set root with non-empty password to remove warning message?

**Comment by wglambert** [comment]
`mysql-laravel` isn't maintained by us. The official image is just `mysql` https://hub.docker.com/_/mysql

But to set a non-empty password you use an environment variable. Using the official image as an example https://github.com/docker-library/docs/tree/master/mysql#how-to-use-this-image
So check with your image's docs to see how to use their variables
