### ISSUE TITLE
How to remove InnoDB warning messages?

### ISSUE THREAD

**Issue by snowuyl** [docker-library/mysql#928]
I am using mysql-laravel:1.0 Docker image. But when I run the following command. I can see warning messages of InnoDB from docker logs command.
 
docker-compose build
docker-compose up

2022-11-10T07:22:14.908684Z 0 [Warning] InnoDB: New log files created, LSN=45790
2022-11-10T07:22:15.947391Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.

How to remove InnoDB warning messages?

**Comment by wglambert** [comment]
See https://github.com/docker-library/mysql/issues/723#issuecomment-713730853
This is for the `mysql` image though so things might be different for the `mysql-laravel` image
