### ISSUE TITLE
How to remove warning messages related to time zone?

### ISSUE THREAD

**Issue by snowuyl** [docker-library/mysql#929]
I am using mysql Docker image. But when I run the following command. I can see warning messages related time zone from docker logs command.

docker-compose build
docker-compose up

Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.

How to remove warning messages related to time zone?

**Comment by wglambert** [comment]
You could try this https://github.com/docker-library/mysql/issues/229#issuecomment-636391910

**Comment by snowuyl** [comment]
Please refer to the attached file. It still shows warning messages.
docker logs 39bf1dadaee0 2>&1 | grep Warn
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.

**Comment by snowuyl** [comment]
[mysql.zip](https://github.com/docker-library/mysql/files/10080247/mysql.zip)

**Comment by yosifkit** [comment]
Those warnings are harmless and a consequence on importing the zoneinfo; if you don't need timezone information in your database, you can skip it by setting [`MYSQL_INITDB_SKIP_TZINFO` to a non-empty value](https://github.com/docker-library/docs/tree/60fae15b4da2d1838f1b1c3bf18d11710a7ae514/mysql#mysql_initdb_skip_tzinfo).

https://github.com/docker-library/mysql/blob/43450e73ddb98a9332c5ff2821d189928047ebb6/template/docker-entrypoint.sh#L283-L290
