### ISSUE TITLE
Error getting repository data for mysql-cluster76-minimal, repository not found

### ISSUE THREAD

**Issue by yuanfang1018** [docker-library/mysql#931]
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/119995067/206084084-52d0bd51-6330-49cd-9420-c4339b62dff1.png">

**Comment by yosifkit** [comment]
That build output is not from any of the images maintained in this repo. It looks to be from the fork: https://github.com/mysql/mysql-docker/blob/044356f9958bbeb9409265495035431a0e3ab8bb/mysql-cluster/7.6/Dockerfile#L26-L29, so you'd have to talk to those maintainers.
