### ISSUE TITLE
what's the difference between /etc/my.cnf.d/ and /etc/mysql/conf.d/

### ISSUE THREAD

**Issue by xiebruce** [docker-library/mysql#934]
```bash
bash-4.4# ls -l /etc/my
my.cnf    my.cnf.d/ mysql/
```

The last line of `/etc/my.cnf` is `!includedir /etc/mysql/conf.d/`, that means the configs in `/etc/mysql/conf.d/` will be included, but why there's a `/etc/my.cnf.d/` directory, what is it use for, it seems `/etc/my.cnf.d/` has the same functionality with `/etc/mysql/conf.d/`.

**Comment by wglambert** [comment]
https://serverfault.com/questions/954304/mysql-8-on-ubuntu-whats-the-difference-between-etc-mysql-conf-d-and-etc-mys
`/etc/mysql/mysql.conf.d` is for backwards compatibility
