### ISSUE TITLE
Can't run SQL files on /docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by pthreat** [docker-library/mysql#938]
I have some scripts which need to be run on initialization,  I'm mounting said scripts dir into the docker entrypoint dir

```text
  mysql:
    hostname: database
    container_name: "my-database"
    image: mysql:8.0.31-debian
    volumes:
      - sql_data:/var/lib/mysql
      - ./docker/container/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "12002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      
volumes:
  sql_data:
    external: false
```

I checked inside the container, the scripts are there, they don't run on startup or on the first run after pull (initialization)

**Comment by tianon** [comment]
Logs from the container's attempt to start would be helpful. :smile:

**Comment by yosifkit** [comment]
I would guess that it was permission related but cannot be sure without more information. The scripts and sql files mounted to `initdb.d/` need to be able to be read by the `mysql` user of the contianer.
