### ISSUE TITLE
Is there a reliable way to gauge whether mysql-server is fully loaded and ready to accept imports?

### ISSUE THREAD

**Issue by carn1x** [docker-library/mysql#94]
I was thinking of something along the lines of a mysql client to connect and run some definitive mysql command, or perhaps a `docker exec` to connect to the mysql server directly and check for some system state. The reason this is needed is because I find that there are 3 possibilities when I try and run an import via a mysql client connection to the mysql server container.
1. If I try immediately after starting mysql server, I get an error that I cannot connect
2. If I try once connection is possible, I find that my Drop/Create/Import script runs without error, however upon querying the server the database is non-existent.
3. If I wait for about 10 seconds, it is generally safe to run an import successfully and be able to query all data.

**Comment by yosifkit** [comment]
For our scripts that test the images, we just do a `SELECT 1` in a loop with a sleep and a max retries ([mysql-basics](https://github.com/docker-library/official-images/blob/6f1d0c4f8e48b82c857b0ade17f14df5136800b4/test/tests/mysql-basics/run.sh#L23-L46)). There is a similar loop in the wordpress image that uses php to try to connect ([`docker-entrypoint.sh`](https://github.com/docker-library/wordpress/blob/4f8894bb38d628e8105711d89363156e5706f2c3/apache/docker-entrypoint.sh#L116-L144)).

I would not recommend using `docker exec` as that could test the connection using the loopback interface and the server may not be available external to the container.

**Comment by ltangvald** [comment]
Waiting a set amount of time is generally not recommended, since it's vulnerable to changes in the software or system. For instance the 5.7 server will generally take significantly longer to start than 5.6.

As yosifkit mentions, running a SELECT is probably the most reliable way to do this.

**Comment by tianon** [comment]
Closing old issue, see #2 for further discussion on the same topic.
