### ISSUE TITLE
jemalloc

### ISSUE THREAD

**Issue by oeresundsgruppen** [docker-library/mysql#944]
Any chance you can amend docker-build to use jemalloc ?

apt-get install -y --no-install-recommends libjemalloc2
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2

**Comment by yosifkit** [comment]
We'd be unlikely to include or activate it by default with the same reason as https://github.com/docker-library/ruby/issues/182#issuecomment-1150253854:

> Without an explicit upstream recommendation for using `jemalloc` by default, I hesitate to make an actual image change here (especially given that there are really functional workarounds that allow users to enable `jemalloc` in a dependent image without too much trouble).

So, this should be done in your own Dockerfile that is `FROM` MySQL.

**Comment by oeresundsgruppen** [comment]
Sure I can give it a run, and let you know
