### ISSUE TITLE
Vulnerabilities reported by Windows Defender for registry

### ISSUE THREAD

**Issue by ajaest** [docker-library/mysql#946]
Hi, 

We tried to use the mariadb image in our internal AKS cluster and windows defender reported this errors to be present both in docker hub's official mysql and mariadb images:

* https://github.com/advisories/GHSA-39hc-v87j-747x
* https://github.com/advisories/GHSA-43fp-rhv2-5gv8
* https://github.com/opencontainers/runc/security/advisories/GHSA-f3fp-gc8g-vw66

![Screenshot from 2023-02-10 16-16-15](https://user-images.githubusercontent.com/4104164/218129242-132da732-ad9a-4c62-a0a0-917dc08df548.png)

**Comment by tianon** [comment]
I suspect this is probably a case of one of the things mentioned in https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves
