### ISSUE TITLE
mysqlbinlog binary missing in  the latest mysql:5.7 and 5.7.41.

### ISSUE THREAD

**Issue by xufengzhu113** [docker-library/mysql#959]
The mysqlbinlog tool is missing in the latest mysql:5.7 container image. It is also not found in version mysql:5.7.41.
This mysqlbinlog tool is always in the directory of /usr/bin.
Is this tool moved to another directory?

**Comment by tianon** [comment]
See https://github.com/docker-library/mysql/issues/847 :see_no_evil:

**Comment by vnMarcus** [comment]
> See #847 see_no_evil
But I don't see any Debian-based variants for mysql 5.7

**Comment by vnMarcus** [comment]
> See #847 see_no_evil
But I don't see any Debian-based variants for mysql 5.7

**Comment by yosifkit** [comment]
>But I don't see any Debian-based variants for mysql 5.7

https://www.mysql.com/support/eol-notice.html:
> Support EOL for Debian 10
> Per the MySQL Support Lifecycle policy regarding ending support for OS versions that are obsolete, have reached end of life, or have little usage pattern, we plan to discontinue building all MySQL binaries for Debian 10 on July 18, 2023.

Yeah, unfortunately we had to drop them early since Debian is no longer a supported target for the 5.7 MySQL packages. 5.7 is fully EOL in about 3 months (31 Oct 2023).

See also https://github.com/docker-library/mysql/pull/987
