### ISSUE TITLE
MYSQL_ROOT_HOST is not documented on docker hub

### ISSUE THREAD

**Issue by lkleen** [docker-library/mysql#968]
setting the environment variable MYSQL_ROOT_HOST=% is a simple way to make the container accessible with the root user from another container eg. phpmyadmin. Unfortunately it is not documented on dockerhub.

**Comment by tianon** [comment]
That's already the default value for that flag in our implementation. :sweat_smile:

**Comment by lkleen** [comment]
actually i had to set it to make it accessible with phpmyadmin. What I forgot to mention is that I'm referring to a specific tag (mysql-server:5.7). Here is my docker compose which does not work when omitting the MYSQL_ROOT_HOST environment variable
`
  roundcube_mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${ENV_MYSQL_ROOT_PASS}
      - MYSQL_ROOT_HOST=%
    restart: always
    networks:
      - roundcube

  roundcube_mysql_phpmyadmin:
    image: phpmyadmin:latest
    configs:
      - source: roundcube_mysql_config
        target: /etc/my.cnf
    environment:
      - PMA_HOST=roundcube_mysql
    networks:
      - roundcube
    ports:
      - 8082:80/tcp
`

**Comment by yosifkit** [comment]
`mysql/mysql-server` is not maintained from this repository. It is from over in https://github.com/mysql/mysql-docker. It does not have the same defaults:

https://github.com/mysql/mysql-docker/blob/99652d9954e6d1e3cebf7832b436c565b0696ae7/mysql-server/5.7/docker-entrypoint.sh#L129-L136

**Comment by lkleen** [comment]
ups, my mistake. sorry for the inconveniences. thanks pointing me to the correct repo.
