### ISSUE TITLE
mysql:5.7 image failing to start

### ISSUE THREAD

**Issue by xetrics** [docker-library/mysql#971]
Image 5.7 fails to start with the following barebones config:
```shell
~ docker run --name mysql2 -d \
-p 3306:3306 \
-e MYSQL_ROOT_PASSWORD=password \
--restart unless-stopped \
mysql:5.7
```

container continuously throws the same error:
```shell
2023-05-08 15:49:57+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.42-1.el7 started.
2023-05-08 15:49:59+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
	command was: mysqld --verbose --help --log-bin-index=/tmp/tmp.yrWVPwwrdU
```

This does not occur on mysql:latest

**Comment by tianon** [comment]
I can't reproduce; possibly related to #967 ?

**Comment by josenbaugh** [comment]
I have this same issue since about April 28th. `5.7` container will not start but `latest` will.

**Comment by no-reply** [comment]
i'm able to reproduce exactly as described in the original report:

```sh
~> docker run --name mysql2 -p 3306:3306 \
                      -e MYSQL_ROOT_PASSWORD=password \
                      --restart unless-stopped \
                      mysql:5.7
Unable to find image 'mysql:5.7' locally
5.7: Pulling from library/mysql
e83e8f2e82cc: Pull complete
0f23deb01b84: Pull complete
f5bda3b184ea: Pull complete
ed17edbc6604: Pull complete
33a94a6acfa7: Pull complete
f153bd2953e4: Pull complete
ab532edfb813: Pull complete
c76bdfe4f3d0: Pull complete
8a7ffe2f2551: Pull complete
857ada4fbbcc: Pull complete
b7c508404c3c: Pull complete
Digest: sha256:f57eef421000aaf8332a91ab0b6c96b3c83ed2a981c29e6528b21ce10197cd16
Status: Downloaded newer image for mysql:5.7
2023-05-18 16:56:57+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.42-1.el7 started.
2023-05-18 16:57:01+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
	command was: mysqld --verbose --help --log-bin-index=/tmp/tmp.jMbz2AXnzG
	
~ [1]> docker version
Client:
 Version:           23.0.3
 API version:       1.42
 Go version:        go1.20.2
 Git commit:        3e7cbfdee1
 Built:             Wed Apr  5 13:17:36 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.3
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.2
  Git commit:       59118bff50
  Built:            Wed Apr  5 13:17:36 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d.m
 runc:
  Version:          1.1.5
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by yosifkit** [comment]
I am unable to reproduce on WSL2 using Docker Desktop or on a regular Debian Bullseye machine.

A few possible avenues:

1. Perhaps related to the env value? Are you are using a different/unique password (not just `password`)? related issues: https://github.com/docker-library/mysql/issues/571, https://github.com/docker-library/mysql/pull/613, and https://github.com/docker-library/mysql/issues/776.
    > We currently don't escape any password characters since we didn't want to implement the equivalent of `mysql_real_escape_string` in bash and didn't want to burden the image with an install of a library/language just for this purpose.

1. Any differences between `docker info` on your two machines? Feel free to post both of them here if you can.

1. Are you out of space on the host or VM? Maybe a `docker system prune` would help and cautiously also add `--volumes` (this could delete volumes with important data, so use with care).

**Comment by ljj038** [comment]
same as @xetrics 
after temp server started, then fix the socket link. 
but failed to conn with socket.

https://github.com/docker-library/mysql/blob/e4bdff20153e6a05364a8fe80356dcfd502445bd/5.7/docker-entrypoint.sh#LL415C15-L415C15

**Comment by thaJeztah** [comment]
- Could be related to https://github.com/docker-library/mysql/issues/840

**Comment by bibstha** [comment]
I can confirm the exact same issue with host linux (amd64).
mysql:5.7.36 but mysql:5.7.37 and later does not work.
Steps to reproduce

This *does not* work (actually is flaky with failures most of the time). Even if it starts, the user and db are not created. `mysql -uuser -ppassword` fails.

```
version: '3.3'

services:
  mysql:
    image: mysql:5.7.37
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
```

This works!
```
version: '3.3'

services:
  mysql:
    image: mysql:5.7.36
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
```

Error

**Comment by tianon** [comment]
Unfortunately, MySQL 5.7 is now EOL upstream :bow: :heart:

https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-44.html

**Comment by MetalArend** [comment]
For future reference: check https://github.com/docker-library/mysql/issues/873#issuecomment-1909948195
