### ISSUE TITLE
while running mysql image it shows localhost didnt send any data and server stops immediately 

### ISSUE THREAD

**Issue by phoenix0706** [docker-library/mysql#979]
while running mysql image it shows localhost didnt send any data and server stops immediately 
![image](https://github.com/docker-library/mysql/assets/76466958/067e48f3-422b-4a75-b37e-ddd2db582a77)
![image](https://github.com/docker-library/mysql/assets/76466958/ed15961b-2565-4c69-a872-78c0c0865250)

**Comment by tianon** [comment]
MySQL doesn't support HTTP, as far as I'm aware :sweat_smile:
