### ISSUE TITLE
Syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead. 

### ISSUE THREAD

**Issue by Eleanaortegagm** [docker-library/mysql#990]
I cannot get rid of this warning and I tried to set global host cache size to 0 in a sql script.

**Comment by taco-chen** [comment]
Also met this issue.

**Comment by StefaniOSApps** [comment]
same

**Comment by rawr51919** [comment]
Fixed in PR #1002

**Comment by LaurentGoderre** [comment]
Duplicate of #921

**Comment by pushpa-01** [comment]
I am facing error while running db container "The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead" where should I set it ?
Anyone has idea about it?

**Comment by LaurentGoderre** [comment]
@pushpa-01 I believe this ios fixed in recent versions. If you can't upgrade to a new version yet, you can try to apply this change manually: https://github.com/docker-library/mysql/pull/1002/files
