### ISSUE TITLE
Unable to use /docker-entrypoint-initdb.d when platform is 'linux/amd64'

### ISSUE THREAD

**Issue by whizzzkid** [docker-library/mysql#993]
Using MySQL v5.7.43 and unable to pull in a dump using `/docker-entrypoint-initdb.d`

Source: https://github.com/docker-library/mysql/blob/c13cda9c2c9d836af9b3331e8681f8cc8e0a7803/5.7/Dockerfile.oracle

## What happens
The MySQL server starts and does not pull in dump. Dump can be manually imported after.

## What should happen
This should happen automatically.

Please Fix!

**Comment by ruudk** [comment]
> and unable to pull in a dump using

This issue does not contain any information that helps debug this issue.
